# Generated by Django 5.1.5 on 2025-03-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0086_denial_health_history_anonymized_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeMeter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("stripe_meter_id", models.CharField(max_length=300)),
                ("name", models.CharField(max_length=300)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="appeal",
            name="billed",
            field=models.BooleanField(default=False),
        ),
    ]
