# Generated by Django 5.1.6 on 2025-03-14 21:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0086_denial_health_history_anonymized_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appeal",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("d65e722d-285a-42db-adb0-96ad7a899654"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="denial",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("0ae2bdb4-12d7-477a-b5ef-5b631f77d66c"),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="faxestosend",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("cdae741e-6d97-45a7-858f-7694128d8384"),
                editable=False,
            ),
        ),
    ]
