# Generated by Django 5.1.5 on 2025-03-15 06:45

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0087_stripemeter_appeal_billed"),
    ]

    operations = [
        migrations.CreateModel(
            name="PubMedMiniArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pmid", models.TextField(blank=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("abstract", models.TextField(blank=True, null=True)),
                (
                    "created",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), null=True
                    ),
                ),
                ("article_url", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="denial",
            name="pubmed_ids_json",
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name="pubmedquerydata",
            name="created",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now(), null=True
            ),
        ),
        migrations.AddField(
            model_name="pubmedquerydata",
            name="since",
            field=models.TextField(null=True),
        ),
    ]
