# Generated by Django 5.1.5 on 2025-03-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "fighthealthinsurance",
            "0088_pubmedminiarticle_denial_pubmed_ids_json_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="appeal",
            name="pubmed_ids_json",
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="faxestosend",
            name="pmids",
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
