# Generated by Django 5.1.5 on 2025-03-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "fighthealthinsurance",
            "0089_alter_appeal_pubmed_ids_json_alter_faxestosend_pmids",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="generated_questions",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
