# Generated by Django 5.1.5 on 2025-03-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0090_denial_generated_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="flag_for_exclude",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="manual_deidentified_appeal",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="manual_deidentified_denial",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="manual_searchterm",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="verified_diagnosis",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="verified_procedure",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="denial",
            name="pubmed_ids_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
