# Generated by Django 5.1.5 on 2025-03-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0091_denial_flag_for_exclude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appeal",
            name="pubmed_ids_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="faxestosend",
            name="pmids",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
