# Generated by Django 5.1.5 on 2025-03-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0092_alter_appeal_pubmed_ids_json_alter_faxestosend_pmids",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="manual_deidentified_ocr_cleaned_denial",
            field=models.TextField(default="", null=True),
        ),
    ]
