# Generated by Django 5.1.5 on 2025-03-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0094_alter_appeal_appeal_text_alter_denial_appeal_result_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="denial",
            name="date_of_service",
            field=models.CharField(blank=True, default="", max_length=300, null=True),
        ),
    ]
