# Generated by Django 5.1.5 on 2025-03-20 22:46

import django.core.files.storage
import django.db.models.deletion
import django_encrypted_filefield.fields
import fighthealthinsurance.combined_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0095_alter_denial_date_of_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faxestosend",
            name="combined_document",
            field=models.FileField(
                blank=True,
                null=True,
                storage=fighthealthinsurance.combined_storage.CombinedStorage(
                    django.core.files.storage.FileSystemStorage(
                        location="localish_data"
                    ),
                    django.core.files.storage.FileSystemStorage(
                        location="/external_data"
                    ),
                    django.core.files.storage.FileSystemStorage(
                        location="external_data_b"
                    ),
                    None,
                ),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="faxestosend",
            name="combined_document_enc",
            field=django_encrypted_filefield.fields.EncryptedFileField(
                blank=True,
                null=True,
                storage=fighthealthinsurance.combined_storage.CombinedStorage(
                    django.core.files.storage.FileSystemStorage(
                        location="localish_data"
                    ),
                    django.core.files.storage.FileSystemStorage(
                        location="/external_data"
                    ),
                    django.core.files.storage.FileSystemStorage(
                        location="external_data_b"
                    ),
                    None,
                ),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="faxestosend",
            name="for_appeal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fighthealthinsurance.appeal",
            ),
        ),
        migrations.AlterField(
            model_name="faxestosend",
            name="name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
