# Generated by Django 5.1.5 on 2025-03-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0097_appeal_include_provided_health_history_in_appeal_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="denial",
            old_name="include_provided_health_history",
            new_name="include_provided_health_history_in_appeal",
        ),
    ]
