# Generated by Django 5.1.5 on 2025-03-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0098_rename_include_provided_health_history_denial_include_provided_health_history_in_appeal",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LostStripeSession",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("session_id", models.CharField(max_length=255)),
                ("payment_type", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cancel_url", models.CharField(max_length=255)),
                ("success_url", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("item", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
