# Generated by Django 5.1.5 on 2025-03-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0099_loststripesession"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeRecoveryInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("items", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
