# Generated by Django 5.1.5 on 2025-03-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0100_striperecoveryinfo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loststripesession",
            name="item",
        ),
        migrations.AlterField(
            model_name="loststripesession",
            name="session_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
