# Generated by Django 5.1.5 on 2025-04-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0102_alter_loststripesession_cancel_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LostStripeMeters",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("resubmitted", models.BooleanField(default=False)),
                ("error", models.CharField(max_length=300)),
            ],
        ),
    ]
