# Generated by Django 5.1.5 on 2025-04-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0103_loststripemeters"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeWebhookEvents",
            fields=[
                ("internal_id", models.AutoField(primary_key=True, serialize=False)),
                ("event_stripe_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=False)),
                ("error", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
