# Generated by Django 5.1.7 on 2025-04-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0104_stripewebhookevents"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="dental_claim",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="denial",
            name="good_appeal_example",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="denial",
            name="not_human_claim",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="denial",
            name="unique_claim",
            field=models.BooleanField(default=False),
        ),
    ]
