# Generated by Django 5.1.5 on 2025-04-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0106_denial_citation_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="pubmed_context",
            field=models.TextField(blank=True, null=True),
        ),
    ]
