# Generated by Django 5.1.5 on 2025-04-07 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0107_denial_pubmed_context"),
    ]

    operations = [
        migrations.RenameField(
            model_name="denial",
            old_name="citation_context",
            new_name="ml_citation_context",
        ),
    ]
