# Generated by Django 5.1.5 on 2025-04-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "fighthealthinsurance",
            "0108_rename_citation_context_denial_ml_citation_context",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="candidate_diagnosis",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="candidate_generated_questions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="candidate_ml_citation_context",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="candidate_procedure",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
