# Generated by Django 5.1.5 on 2025-04-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0109_denial_candidate_diagnosis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="date_of_service_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
