# Generated by Django 5.1.5 on 2025-04-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0110_denial_date_of_service_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="appeal",
            name="notes",
            field=models.TextField(blank=True, max_length=3000000000, null=True),
        ),
    ]
