# Generated by Django 5.1.5 on 2025-04-09 22:47

import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0111_appeal_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericContextGeneration",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("procedure", models.CharField(max_length=300)),
                ("diagnosis", models.CharField(max_length=300)),
                ("generated_context", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["procedure", "diagnosis"],
                        name="fighthealth_procedu_ac1633_idx",
                    )
                ],
                "unique_together": {("procedure", "diagnosis")},
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "GenericContextGeneration"
                ),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="GenericQuestionGeneration",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("procedure", models.CharField(max_length=300)),
                ("diagnosis", models.CharField(max_length=300)),
                ("generated_questions", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["procedure", "diagnosis"],
                        name="fighthealth_procedu_22e432_idx",
                    )
                ],
                "unique_together": {("procedure", "diagnosis")},
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "GenericQuestionGeneration"
                ),
                models.Model,
            ),
        ),
    ]
