# Generated by Django 5.1.5 on 2025-04-10 07:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "fighthealthinsurance",
            "0112_genericcontextgeneration_genericquestiongeneration",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="genericcontextgeneration",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="genericquestiongeneration",
            unique_together=set(),
        ),
    ]
