# Generated by Django 5.1.5 on 2025-04-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "fighthealthinsurance",
            "0113_alter_genericcontextgeneration_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="disability_claim",
            field=models.BooleanField(default=False),
        ),
    ]
