# Generated by Django 5.1.5 on 2025-05-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0114_denial_disability_claim"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="gen_attempts",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
