# Generated by Django 5.1.5 on 2025-05-03 19:00

import django.db.models.deletion
import django_prometheus.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0040_pendingprostripecheckoutsession"),
        ("fighthealthinsurance", "0115_denial_gen_attempts"),
    ]

    operations = [
        migrations.CreateModel(
            name="OngoingChat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chat_history", models.JSONField(blank=True, default=list, null=True)),
                ("summary_for_next_call", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fhi_users.userdomain",
                    ),
                ),
                (
                    "professional_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fhi_users.professionaluser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriorAuthRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("diagnosis", models.TextField()),
                ("treatment", models.TextField()),
                ("insurance_company", models.TextField()),
                ("patient_health_history", models.TextField(blank=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("guided", "Guided"), ("raw", "Raw")],
                        default="guided",
                        max_length=10,
                    ),
                ),
                ("questions", models.JSONField(blank=True, null=True)),
                ("answers", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initial", "Initial"),
                            ("questions_asked", "Questions Asked"),
                            ("questions_answered", "Questions Answered"),
                            ("prior_auth_requested", "Prior Auth Requested"),
                            ("completed", "Completed"),
                        ],
                        default="initial",
                        max_length=50,
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fhi_users.userdomain",
                    ),
                ),
                (
                    "professional_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fhi_users.professionaluser",
                    ),
                ),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("PriorAuthRequest"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ProposedPriorAuth",
            fields=[
                (
                    "proposed_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("selected", models.BooleanField(default=False)),
                (
                    "prior_auth_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.priorauthrequest",
                    ),
                ),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "ProposedPriorAuth"
                ),
                models.Model,
            ),
        ),
    ]
