# Generated by Django 5.1.5 on 2025-05-04 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0040_pendingprostripecheckoutsession"),
        ("fighthealthinsurance", "0116_ongoingchat_priorauthrequest_proposedpriorauth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="priorauthrequest",
            name="professional_user",
        ),
        migrations.AddField(
            model_name="priorauthrequest",
            name="created_for_professional_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_for_professional_user",
                to="fhi_users.professionaluser",
            ),
        ),
        migrations.AddField(
            model_name="priorauthrequest",
            name="creator_professional_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prior_auth_requests_creators",
                to="fhi_users.professionaluser",
            ),
        ),
    ]
