# Generated by Django 5.1.5 on 2025-05-05 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fhi_users", "0040_pendingprostripecheckoutsession"),
        (
            "fighthealthinsurance",
            "0117_remove_priorauthrequest_professional_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="priorauthrequest",
            name="patient_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="priorauthrequest",
            name="plan_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="priorauthrequest",
            name="created_for_professional_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prior_auth_requests_created_for",
                to="fhi_users.professionaluser",
            ),
        ),
    ]
