# Generated by Django 5.1.5 on 2025-05-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0118_priorauthrequest_patient_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="priorauthrequest",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
