# Generated by Django 5.1.5 on 2025-05-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0119_priorauthrequest_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="priorauthrequest",
            name="patient_dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="priorauthrequest",
            name="patient_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="priorauthrequest",
            name="proposal_type",
            field=models.CharField(
                choices=[("letter", "Letter"), ("case_note", "Case Note")],
                default="letter",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="priorauthrequest",
            name="urgent",
            field=models.BooleanField(default=False),
        ),
    ]
