# Generated by Django 5.1.5 on 2025-05-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0120_priorauthrequest_patient_dob_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="priorauthrequest",
            old_name="patient_id",
            new_name="member_id",
        ),
    ]
