# Generated by Django 5.1.5 on 2025-05-15 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0121_rename_patient_id_priorauthrequest_member_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="appeal",
            name="chat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appeals",
                to="fighthealthinsurance.ongoingchat",
            ),
        ),
        migrations.AddField(
            model_name="priorauthrequest",
            name="chat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prior_auths",
                to="fighthealthinsurance.ongoingchat",
            ),
        ),
    ]
