# Generated by Django 5.1.5 on 2025-05-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0123_ongoingchat_denied_item_ongoingchat_denied_reason_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ongoingchat",
            name="session_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
