# Generated by Django 5.1.5 on 2025-05-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0124_ongoingchat_session_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailinglistsubscriber",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
