# Generated by Django 5.1.5 on 2025-05-22 00:47

import uuid

from django.db import migrations, models

import django_prometheus.models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0125_mailinglistsubscriber_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatLeads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=32)),
                ("company", models.CharField(max_length=255)),
                ("consent_to_contact", models.BooleanField()),
                ("agreed_to_terms", models.BooleanField()),
                ("session_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Chat Lead",
                "verbose_name_plural": "Chat Leads",
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("ChatLeads"),
                models.Model,
            ),
        ),
    ]
