# Generated by Django 5.1.5 on 2025-05-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0126_chatleads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatleads",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
