# Generated by Django 5.1.5 on 2025-05-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0127_alter_chatleads_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ongoingchat",
            name="hashed_email",
            field=models.CharField(
                blank=True,
                help_text="Hashed email of the user",
                max_length=300,
                null=True,
            ),
        ),
    ]
