# Generated by Django 5.1.5 on 2025-05-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0128_ongoingchat_hashed_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoRequests",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, default="", max_length=300)),
                ("company", models.CharField(blank=True, default="", max_length=300)),
                ("role", models.CharField(blank=True, default="", max_length=300)),
                ("source", models.CharField(blank=True, default="", max_length=300)),
                ("signup_date", models.DateField(auto_now_add=True)),
                ("phone", models.CharField(blank=True, default="", max_length=300)),
            ],
        ),
    ]
