# Generated by Django 5.1.5 on 2025-06-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0129_demorequests"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatleads",
            name="drug",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
