# Generated by Django 5.1.5 on 2025-11-27

from django.db import migrations, models
import fighthealthinsurance.utils


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0130_chatleads_drug"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailinglistsubscriber",
            name="unsubscribe_token",
            field=models.CharField(
                default=fighthealthinsurance.utils.sekret_gen,
                max_length=100,
                unique=True,
            ),
        ),
    ]
