# Generated by Django 5.2.3 on 2025-12-01 03:47

import django.db.models.deletion
from django.db import migrations, models

import django_prometheus.models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0131_mailinglistsubscriber_unsubscribe_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChooserTask",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("appeal", "Appeal Letter"),
                            ("chat", "Chat Response"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("READY", "Ready"),
                            ("IN_USE", "In Use"),
                            ("EXHAUSTED", "Exhausted"),
                            ("DISABLED", "Disabled"),
                        ],
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                ("context_json", models.JSONField(blank=True, null=True)),
                ("source", models.CharField(default="synthetic", max_length=50)),
                ("num_candidates_expected", models.IntegerField(default=4)),
                ("num_candidates_generated", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chooser Task",
                "verbose_name_plural": "Chooser Tasks",
                "indexes": [
                    models.Index(
                        fields=["task_type", "status"],
                        name="fighthealth_task_ty_4ed58d_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="fighthealth_status_454180_idx",
                    ),
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("ChooserTask"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ChooserCandidate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("candidate_index", models.IntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("appeal_letter", "Appeal Letter"),
                            ("chat_response", "Chat Response"),
                        ],
                        max_length=30,
                    ),
                ),
                ("model_name", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="fighthealthinsurance.choosertask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chooser Candidate",
                "verbose_name_plural": "Chooser Candidates",
                "ordering": ["task", "candidate_index"],
                "unique_together": {("task", "candidate_index")},
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("ChooserCandidate"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ChooserVote",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("presented_candidate_ids", models.JSONField()),
                ("session_key", models.CharField(db_index=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chosen_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="fighthealthinsurance.choosercandidate",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="fighthealthinsurance.choosertask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chooser Vote",
                "verbose_name_plural": "Chooser Votes",
                "indexes": [
                    models.Index(
                        fields=["task"], name="fighthealth_task_id_e30295_idx"
                    ),
                    models.Index(
                        fields=["session_key"], name="fighthealth_session_bf411a_idx"
                    ),
                ],
                "unique_together": {("task", "session_key")},
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("ChooserVote"),
                models.Model,
            ),
        ),
    ]
