# Generated by Django 5.1.1 on 2025-12-02 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0132_choosertask_choosercandidate_chooservote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailinglistsubscriber",
            name="unsubscribe_token",
        ),
    ]
