# Generated by Django 5.1.1 on 2025-12-02 20:22

import fighthealthinsurance.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0133_remove_mailinglistsubscriber_unsubscribe_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailinglistsubscriber",
            name="unsubscribe_token",
            field=models.CharField(
                default=fighthealthinsurance.utils.sekret_gen, max_length=100
            ),
        ),
    ]
