# Generated by Django 5.2.9 on 2025-12-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0134_mailinglistsubscriber_unsubscribe_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="plan_documents_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
