# Generated by Django 5.1.5 on 2025-12-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0135_add_plan_documents_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatleads",
            name="subscribe",
            field=models.BooleanField(default=True),
        ),
    ]
