# Generated by Django 5.2.9 on 2025-12-14 07:38

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0139_add_indexes_to_microsite_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChooserSkip",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("session_key", models.CharField(db_index=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skips",
                        to="fighthealthinsurance.choosertask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chooser Skip",
                "verbose_name_plural": "Chooser Skips",
                "indexes": [
                    models.Index(
                        fields=["task"], name="fighthealth_task_id_ff9dab_idx"
                    ),
                    models.Index(
                        fields=["session_key"], name="fighthealth_session_d7ff3b_idx"
                    ),
                ],
                "unique_together": {("task", "session_key")},
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("ChooserSkip"),
                models.Model,
            ),
        ),
    ]
