# Generated by Django 5.1.1 on 2025-12-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0140_add_chooser_skip_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatleads",
            name="referral_source",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="chatleads",
            name="referral_source_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mailinglistsubscriber",
            name="referral_source",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="mailinglistsubscriber",
            name="referral_source_details",
            field=models.TextField(blank=True, default=""),
        ),
    ]
