# Generated by Django 5.2.9 on 2025-12-21 01:34

import django.core.files.storage
import django.db.models.deletion
import django_encrypted_filefield.fields
import django_prometheus.models
import fighthealthinsurance.combined_storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0041_professionaluser_credentials"),
        ("fighthealthinsurance", "0141_chatleads_referral_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceCallLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "call_date",
                    models.DateTimeField(help_text="Date and time of the call"),
                ),
                (
                    "call_type",
                    models.CharField(
                        choices=[
                            ("inquiry", "General Inquiry"),
                            ("prior_auth", "Prior Authorization"),
                            ("claim_status", "Claim Status"),
                            ("appeal_status", "Appeal Status"),
                            ("benefits", "Benefits Verification"),
                            ("complaint", "Complaint/Grievance"),
                            ("other", "Other"),
                        ],
                        default="inquiry",
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Department or queue contacted",
                        max_length=200,
                    ),
                ),
                (
                    "representative_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of representative spoken to",
                        max_length=200,
                    ),
                ),
                (
                    "representative_id",
                    models.CharField(
                        blank=True,
                        help_text="Employee ID or badge number if provided",
                        max_length=100,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Call reference/confirmation number",
                        max_length=100,
                    ),
                ),
                (
                    "case_number",
                    models.CharField(
                        blank=True,
                        help_text="Case or ticket number if assigned",
                        max_length=100,
                    ),
                ),
                (
                    "reason_for_call",
                    models.TextField(
                        help_text="Why you called - the question or issue"
                    ),
                ),
                (
                    "key_statements",
                    models.TextField(
                        blank=True,
                        help_text="Important statements made by the representative (quotes if possible)",
                    ),
                ),
                (
                    "promises_made",
                    models.TextField(
                        blank=True,
                        help_text="Any commitments or promises made by the representative",
                    ),
                ),
                (
                    "call_notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the call"
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pending/In Progress"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated"),
                            ("transferred", "Transferred"),
                            ("callback", "Callback Requested"),
                            ("denied", "Request Denied"),
                            ("approved", "Request Approved"),
                            ("no_resolution", "No Resolution"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, help_text="Date for follow-up if needed", null=True
                    ),
                ),
                (
                    "follow_up_notes",
                    models.TextField(
                        blank=True, help_text="Notes for follow-up action"
                    ),
                ),
                (
                    "call_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Approximate call duration in minutes",
                        null=True,
                    ),
                ),
                (
                    "wait_time_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Time spent on hold/waiting", null=True
                    ),
                ),
                (
                    "include_in_appeal",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to include this call log as evidence in appeals",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appeal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_logs",
                        to="fighthealthinsurance.appeal",
                    ),
                ),
                (
                    "denial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_logs",
                        to="fighthealthinsurance.denial",
                    ),
                ),
                (
                    "patient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_logs",
                        to="fhi_users.patientuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insurance Call Log",
                "verbose_name_plural": "Insurance Call Logs",
                "ordering": ["-call_date"],
                "indexes": [
                    models.Index(
                        fields=["patient_user", "-call_date"],
                        name="fighthealth_patient_e9efc4_idx",
                    ),
                    models.Index(
                        fields=["denial"], name="fighthealth_denial__327b5f_idx"
                    ),
                    models.Index(
                        fields=["appeal"], name="fighthealth_appeal__ffa4b2_idx"
                    ),
                    models.Index(
                        fields=["reference_number"],
                        name="fighthealth_referen_28dfee_idx",
                    ),
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("InsuranceCallLog"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="PatientEvidence",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("document", "Document/Letter"),
                            ("screenshot", "Screenshot"),
                            ("eob", "Explanation of Benefits"),
                            ("medical_record", "Medical Record"),
                            ("prescription", "Prescription"),
                            ("referral", "Referral"),
                            ("prior_auth", "Prior Authorization"),
                            ("correspondence", "Insurance Correspondence"),
                            ("research", "Research/Article"),
                            ("notes", "Personal Notes"),
                            ("other", "Other"),
                        ],
                        default="document",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title for this evidence", max_length=300
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this evidence shows"
                    ),
                ),
                (
                    "date_of_evidence",
                    models.DateField(
                        blank=True,
                        help_text="Date on the document or when evidence was created",
                        null=True,
                    ),
                ),
                (
                    "file",
                    django_encrypted_filefield.fields.EncryptedFileField(
                        blank=True,
                        null=True,
                        storage=fighthealthinsurance.combined_storage.CombinedStorage(
                            django.core.files.storage.FileSystemStorage(
                                location="localish_data"
                            ),
                            django.core.files.storage.FileSystemStorage(
                                location="/external_data"
                            ),
                            django.core.files.storage.FileSystemStorage(
                                location="external_data_b"
                            ),
                            None,
                        ),
                        upload_to="",
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=127)),
                (
                    "text_content",
                    models.TextField(blank=True, help_text="Text content or notes"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Where this evidence came from (e.g., 'MyChart portal', 'Insurance website')",
                        max_length=300,
                    ),
                ),
                (
                    "include_in_appeal",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to include this evidence in appeals",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appeal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_evidence",
                        to="fighthealthinsurance.appeal",
                    ),
                ),
                (
                    "denial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_evidence",
                        to="fighthealthinsurance.denial",
                    ),
                ),
                (
                    "patient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="fhi_users.patientuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Evidence",
                "verbose_name_plural": "Patient Evidence",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient_user", "-created_at"],
                        name="fighthealth_patient_c65577_idx",
                    ),
                    models.Index(
                        fields=["denial"], name="fighthealth_denial__949837_idx"
                    ),
                    models.Index(
                        fields=["appeal"], name="fighthealth_appeal__7cd116_idx"
                    ),
                    models.Index(
                        fields=["evidence_type"], name="fighthealth_evidenc_1a4e67_idx"
                    ),
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("PatientEvidence"),
                models.Model,
            ),
        ),
    ]
