# Generated by Django 5.1.1 on 2025-12-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0141_chatleads_referral_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglistsubscriber",
            name="referral_source",
            field=models.CharField(blank=True, default="", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="mailinglistsubscriber",
            name="referral_source_details",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
