# Generated by Django 5.2.9 on 2025-12-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0141_add_referral_source_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailinglistsubscriber",
            name="referral_source_details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="chatleads",
            name="referral_source_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
