# Generated by Django 5.2.9 on 2025-12-21 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0142_alter_mailinglistsubscriber_referral_source_and_more",
        ),
        ("fighthealthinsurance", "0142_insurancecalllog_patientevidence"),
    ]

    operations = []
