# Generated by Django 5.2.9 on 2025-12-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0142_add_referral_source_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="referral_source",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="referral_source_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
