# Generated by Django 5.2.9 on 2025-12-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "fighthealthinsurance",
            "0142_alter_mailinglistsubscriber_referral_source_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="asn",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="denial",
            name="asn_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="denial",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="denial",
            name="user_agent",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ongoingchat",
            name="asn",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="ongoingchat",
            name="asn_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="ongoingchat",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ongoingchat",
            name="user_agent",
            field=models.TextField(blank=True, default=""),
        ),
    ]
