# Generated by Django 5.2.9 on 2025-12-29 04:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fhi_users", "0042_auditlog"),
        (
            "fighthealthinsurance",
            "0143_denial_asn_denial_asn_name_denial_ip_address_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="denial",
            index=models.Index(fields=["hashed_email"], name="denial_hashed_email_idx"),
        ),
        migrations.AddIndex(
            model_name="denial",
            index=models.Index(fields=["created"], name="denial_created_idx"),
        ),
        migrations.AddIndex(
            model_name="faxestosend",
            index=models.Index(fields=["hashed_email"], name="fax_hashed_email_idx"),
        ),
        migrations.AddIndex(
            model_name="ongoingchat",
            index=models.Index(fields=["hashed_email"], name="chat_hashed_email_idx"),
        ),
        migrations.AddIndex(
            model_name="ongoingchat",
            index=models.Index(
                fields=["professional_user", "updated_at"],
                name="chat_pro_user_updated_idx",
            ),
        ),
    ]
