# Generated by Django 5.2.9 on 2025-12-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0144_denial_denial_hashed_email_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripewebhookevents",
            name="event_stripe_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
