# Generated by Django 5.2.9 on 2026-01-01 02:48

import django.db.models.deletion
import regex_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0145_stripe_webhook_events_unique_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceCompany",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Official name of the insurance company (e.g., Anthem, Blue Cross Blue Shield)",
                        max_length=300,
                        unique=True,
                    ),
                ),
                (
                    "alt_names",
                    models.TextField(
                        blank=True,
                        help_text="Alternative names or abbreviations, one per line (e.g., BCBS for Blue Cross Blue Shield)",
                    ),
                ),
                (
                    "regex",
                    regex_field.fields.RegexField(
                        blank=True,
                        help_text="Regular expression pattern to match this company in denial text",
                        max_length=800,
                    ),
                ),
                (
                    "negative_regex",
                    regex_field.fields.RegexField(
                        blank=True,
                        help_text="Pattern to exclude false matches",
                        max_length=800,
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Company's official website"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this insurance company",
                    ),
                ),
                (
                    "is_tpa",
                    models.BooleanField(
                        default=False,
                        help_text="True if company is primarily a third-party administrator (TPA) for self-funded plans",
                    ),
                ),
                (
                    "is_marketplace_focused",
                    models.BooleanField(
                        default=False,
                        help_text="True if company primarily offers ACA marketplace/individual plans (95%+ of business)",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Insurance Companies",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="denial",
            name="insurance_company_obj",
            field=models.ForeignKey(
                blank=True,
                help_text="Structured reference to insurance company",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="denials",
                to="fighthealthinsurance.insurancecompany",
            ),
        ),
        migrations.CreateModel(
            name="InsurancePlan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "plan_name",
                    models.CharField(
                        help_text="Specific plan name (e.g., Medicaid California, Gold PPO)",
                        max_length=300,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="Two-letter state code if plan is state-specific",
                        max_length=2,
                    ),
                ),
                (
                    "regex",
                    regex_field.fields.RegexField(
                        blank=True,
                        help_text="Regular expression pattern to match this specific plan",
                        max_length=800,
                    ),
                ),
                (
                    "negative_regex",
                    regex_field.fields.RegexField(
                        blank=True,
                        help_text="Pattern to exclude false matches",
                        max_length=800,
                    ),
                ),
                (
                    "plan_id_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Common prefix for plan IDs (helps with identification)",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this plan"
                    ),
                ),
                (
                    "insurance_company",
                    models.ForeignKey(
                        help_text="The insurance company that offers this plan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="fighthealthinsurance.insurancecompany",
                    ),
                ),
                (
                    "plan_source",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source of plan (Medicaid, Medicare, Employer, etc.)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fighthealthinsurance.plansource",
                    ),
                ),
                (
                    "plan_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of plan (HMO, PPO, etc.)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fighthealthinsurance.plantype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insurance Plan",
                "ordering": ["insurance_company__name", "plan_name"],
                "unique_together": {("insurance_company", "plan_name", "state")},
            },
        ),
        migrations.AddField(
            model_name="denial",
            name="insurance_plan_obj",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific insurance plan (e.g., Anthem Medicaid California)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="denials",
                to="fighthealthinsurance.insuranceplan",
            ),
        ),
    ]
