# Generated by Django 5.2 on 2026-01-31

import django.db.models.deletion
import django_encrypted_filefield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Merge migration that resolves the 0143 conflict and adds FuzzAttempt model.
    """

    dependencies = [
        ("fighthealthinsurance", "0143_add_policy_document_models"),
        (
            "fighthealthinsurance",
            "0146_insurancecompany_denial_insurance_company_obj_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FuzzAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of IP + salt",
                        max_length=64,
                    ),
                ),
                (
                    "ip_prefix",
                    models.CharField(
                        help_text="/24 for IPv4, /64 for IPv6",
                        max_length=45,
                    ),
                ),
                (
                    "raw_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Only stored if FUZZ_GUARD_STORE_RAW_IP=True",
                        null=True,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "is_authenticated",
                    models.BooleanField(default=False),
                ),
                (
                    "method",
                    models.CharField(max_length=10),
                ),
                (
                    "path",
                    models.CharField(max_length=2048),
                ),
                (
                    "status_returned",
                    models.PositiveSmallIntegerField(),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="JSON list of triggered rules",
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(db_index=True),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "encrypted_blob",
                    django_encrypted_filefield.fields.EncryptedFileField(
                        blank=True,
                        null=True,
                        upload_to="fuzz_captures/",
                    ),
                ),
                (
                    "encrypted_blob_size",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "key_version",
                    models.CharField(
                        default="v1",
                        help_text="Encryption key version for rotation",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuzz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fuzz Attempt",
                "verbose_name_plural": "Fuzz Attempts",
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_fuzz_capture", "Can view decrypted fuzz captures")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="fuzzattempt",
            index=models.Index(
                fields=["ip_hash", "created_at"],
                name="fuzz_ip_hash_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fuzzattempt",
            index=models.Index(
                fields=["ip_prefix", "created_at"],
                name="fuzz_ip_prefix_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fuzzattempt",
            index=models.Index(
                fields=["score", "created_at"],
                name="fuzz_score_created_idx",
            ),
        ),
    ]
