# Generated by Django 5.1.1 on 2026-01-06 06:54

import django.core.files.storage
import django.db.models.deletion
import django_encrypted_filefield.fields
import django_prometheus.models
import fighthealthinsurance.combined_storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0146_insurancecompany_denial_insurance_company_obj_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraLinkDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(db_index=True, max_length=2000, unique=True)),
                (
                    "url_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Document"),
                            ("docx", "Word Document"),
                            ("html", "HTML Page"),
                            ("txt", "Text Document"),
                            ("unknown", "Unknown Type"),
                        ],
                        default="unknown",
                        max_length=50,
                    ),
                ),
                ("content_type", models.CharField(blank=True, max_length=200)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("raw_text", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                (
                    "stored_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=fighthealthinsurance.combined_storage.CombinedStorage(
                            django.core.files.storage.FileSystemStorage(
                                location="localish_data"
                            ),
                            django.core.files.storage.FileSystemStorage(
                                location="/external_data"
                            ),
                            django.core.files.storage.FileSystemStorage(
                                location="external_data_b"
                            ),
                            None,
                        ),
                        upload_to="extralink_docs/",
                    ),
                ),
                (
                    "stored_file_enc",
                    django_encrypted_filefield.fields.EncryptedFileField(
                        blank=True,
                        null=True,
                        storage=fighthealthinsurance.combined_storage.CombinedStorage(
                            django.core.files.storage.FileSystemStorage(
                                location="localish_data"
                            ),
                            django.core.files.storage.FileSystemStorage(
                                location="/external_data"
                            ),
                            django.core.files.storage.FileSystemStorage(
                                location="external_data_b"
                            ),
                            None,
                        ),
                        upload_to="extralink_docs_enc/",
                    ),
                ),
                (
                    "fetch_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("fetching", "Fetching"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("fetch_error", models.TextField(blank=True)),
                ("first_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("fetch_attempts", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Extra Link Document",
                "verbose_name_plural": "Extra Link Documents",
                "indexes": [
                    models.Index(
                        fields=["url_hash"], name="fighthealth_url_has_3a4ee3_idx"
                    ),
                    models.Index(
                        fields=["fetch_status", "created_at"],
                        name="fighthealth_fetch_s_cd2f72_idx",
                    ),
                    models.Index(
                        fields=["document_type"], name="fighthealth_documen_a4c8e0_idx"
                    ),
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "ExtraLinkDocument"
                ),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ExtraLinkFetchLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("fetch_duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("deploy", "Deploy-time Actor"),
                            ("manual", "Manual Trigger"),
                            ("retry", "Automatic Retry"),
                            ("on_demand", "On-Demand Fetch"),
                        ],
                        default="deploy",
                        max_length=50,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fetch_logs",
                        to="fighthealthinsurance.extralinkdocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["document", "timestamp"],
                        name="fighthealth_documen_680b7f_idx",
                    ),
                    models.Index(
                        fields=["status", "timestamp"],
                        name="fighthealth_status_b96312_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MicrositeExtraLink",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "microsite_slug",
                    models.CharField(
                        db_index=True,
                        help_text="Slug from microsites.json",
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="E.g., 'Clinical Guidelines', 'Patient Resources', 'Research'",
                        max_length=100,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        help_text="Priority level: 0=highest, 1=medium, 2=low",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="microsite_links",
                        to="fighthealthinsurance.extralinkdocument",
                    ),
                ),
            ],
            options={
                "ordering": ["microsite_slug", "display_order"],
                "indexes": [
                    models.Index(
                        fields=["microsite_slug", "priority"],
                        name="fighthealth_microsi_ebebf7_idx",
                    ),
                    models.Index(
                        fields=["microsite_slug", "display_order"],
                        name="fighthealth_microsi_6ff1c4_idx",
                    ),
                ],
                "unique_together": {("microsite_slug", "document")},
            },
        ),
    ]
