# Generated by Django 5.2.9 on 2026-01-04 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0143_add_policy_document_models"),
        (
            "fighthealthinsurance",
            "0146_insurancecompany_denial_insurance_company_obj_and_more",
        ),
    ]

    operations = []
