# Generated by Django 5.2.10 on 2026-02-12 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0147_extralinkdocument_extralinkfetchlog_and_more"),
        ("fighthealthinsurance", "0147_merge_20260129_1021"),
    ]

    operations = []
