# Generated by Django 5.1.1 on 2026-01-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0147_extralinkdocument_extralinkfetchlog_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="extralinkdocument",
            name="fighthealth_url_has_3a4ee3_idx",
        ),
        migrations.AlterField(
            model_name="extralinkdocument",
            name="url_hash",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
