# Generated by Django 5.2.9 on 2026-01-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0147_insurancecalllog_patientevidence"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataDeletionRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=300)),
                ("hashed_email", models.CharField(max_length=300)),
                ("token", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed", models.BooleanField(default=False)),
                ("confirmed_at", models.DateTimeField(null=True)),
                ("ip_address", models.GenericIPAddressField(null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["token"], name="fighthealth_token_7aa19a_idx"),
                    models.Index(
                        fields=["hashed_email"], name="fighthealth_hashed__7a8f04_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="fighthealth_created_9134d2_idx"
                    ),
                ],
            },
        ),
    ]
