# Generated by Django 5.2.9 on 2026-02-02 08:02

import django.core.files.storage
import django.db.models.deletion
import django_encrypted_filefield.fields
import django_prometheus.models
import fighthealthinsurance.combined_storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0147_extralinkdocument_extralinkfetchlog_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FuzzAttempt",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "ip_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of IP address + salt",
                        max_length=128,
                    ),
                ),
                (
                    "ip_prefix",
                    models.CharField(
                        help_text="Network prefix (/24 for IPv4, /64 for IPv6)",
                        max_length=64,
                    ),
                ),
                (
                    "raw_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Raw IP only stored if FUZZ_GUARD_STORE_RAW_IP is True",
                        null=True,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("is_authenticated", models.BooleanField(default=False)),
                ("method", models.CharField(max_length=20)),
                ("path", models.CharField(max_length=2048)),
                ("status_returned", models.PositiveSmallIntegerField()),
                (
                    "reason",
                    models.TextField(
                        help_text="JSON list of triggered detection rules"
                    ),
                ),
                ("score", models.PositiveIntegerField(db_index=True)),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Request ID from X-Request-ID header or generated UUID",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "encrypted_blob",
                    django_encrypted_filefield.fields.EncryptedFileField(
                        blank=True,
                        help_text="Encrypted JSON containing full request details including headers",
                        null=True,
                        storage=fighthealthinsurance.combined_storage.CombinedStorage(
                            django.core.files.storage.FileSystemStorage(
                                location="localish_data"
                            ),
                            django.core.files.storage.FileSystemStorage(
                                location="/external_data"
                            ),
                            django.core.files.storage.FileSystemStorage(
                                location="external_data_b"
                            ),
                            None,
                        ),
                        upload_to="",
                    ),
                ),
                (
                    "encrypted_blob_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Size of encrypted blob in bytes",
                        null=True,
                    ),
                ),
                (
                    "key_version",
                    models.CharField(
                        default="v1",
                        help_text="Encryption key version for future rotation support",
                        max_length=32,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuzz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fuzz Attempt",
                "verbose_name_plural": "Fuzz Attempts",
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_fuzz_capture", "Can view decrypted fuzz captures")
                ],
                "indexes": [
                    models.Index(
                        fields=["ip_hash", "created_at"],
                        name="fighthealth_ip_hash_384fa3_idx",
                    ),
                    models.Index(
                        fields=["score", "created_at"],
                        name="fighthealth_score_04be94_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="fighthealth_created_e0ef3c_idx"
                    ),
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("FuzzAttempt"),
                models.Model,
            ),
        ),
    ]
