# Generated by Django 5.2 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0147_extralinkdocument_extralinkfetchlog_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ongoingchat",
            name="edited_chat_history",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Cleaned up / edited version of chat_history for review purposes",
                null=True,
            ),
        ),
    ]
