# Generated by Django 5.2.9 on 2026-03-03 07:43

import django.core.files.storage
import django.db.models.deletion
import django_encrypted_filefield.fields
import django_prometheus.models
import fighthealthinsurance.combined_storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0147_extralinkdocument_extralinkfetchlog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_enc",
                    django_encrypted_filefield.fields.EncryptedFileField(
                        null=True,
                        storage=fighthealthinsurance.combined_storage.CombinedStorage(
                            django.core.files.storage.FileSystemStorage(
                                location="localish_data"
                            ),
                            django.core.files.storage.FileSystemStorage(
                                location="/external_data"
                            ),
                            django.core.files.storage.FileSystemStorage(
                                location="external_data_b"
                            ),
                            None,
                        ),
                        upload_to="",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("summary_of_benefits", "Summary of Benefits"),
                            ("medical_policy", "Medical Policy"),
                            ("other", "Other Policy Document"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255)),
                (
                    "hashed_email",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Policy Document",
                "verbose_name_plural": "Policy Documents",
                "indexes": [
                    models.Index(
                        fields=["hashed_email"], name="fighthealth_hashed__941c87_idx"
                    ),
                    models.Index(
                        fields=["session_key"], name="fighthealth_session_78e69d_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="fighthealth_created_b293c0_idx"
                    ),
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("PolicyDocument"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="PolicyDocumentAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_question", models.TextField(blank=True)),
                ("exclusions", models.JSONField(default=list)),
                ("inclusions", models.JSONField(default=list)),
                ("appeal_clauses", models.JSONField(default=list)),
                ("summary", models.TextField(blank=True)),
                ("quotable_sections", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policy_analyses",
                        to="fighthealthinsurance.ongoingchat",
                    ),
                ),
                (
                    "policy_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="fighthealthinsurance.policydocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Document Analysis",
                "verbose_name_plural": "Policy Document Analyses",
                "indexes": [
                    models.Index(
                        fields=["policy_document"],
                        name="fighthealth_policy__a32f41_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="fighthealth_created_37c5eb_idx"
                    ),
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "PolicyDocumentAnalysis"
                ),
                models.Model,
            ),
        ),
    ]
