# Generated by Django 5.2.9 on 2026-01-05 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0148_datadeletionrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarReminder",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=300)),
                ("reminder_date", models.DateField()),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("2day", "2 Day Follow-up"),
                            ("30day", "30 Day Follow-up"),
                            ("90day", "90 Day Follow-up"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_sent_date", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "denial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fighthealthinsurance.denial",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["email", "reminder_date"],
                        name="fighthealth_email_7e62ee_idx",
                    ),
                    models.Index(
                        fields=["denial"], name="fighthealth_denial__3f771b_idx"
                    ),
                    models.Index(
                        fields=["reminder_sent", "reminder_date"],
                        name="fighthealth_reminde_08ec6a_idx",
                    ),
                ],
            },
        ),
    ]
