# Generated by Django 5.2.9 on 2026-01-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0149_calendarreminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="appeal",
            name="appeal_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent to Insurance"),
                    ("awaiting_decision", "Awaiting Decision"),
                    ("decision_received", "Decision Received"),
                ],
                default="draft",
                help_text="Current status of appeal (patient-tracked)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="appeal",
            name="decision_expected_date",
            field=models.DateField(
                blank=True,
                help_text="Date by which patient expects to hear decision (typically 30-60 days after sent)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appeal",
            name="decision_received_date",
            field=models.DateField(
                blank=True,
                help_text="Date patient received decision from insurance",
                null=True,
            ),
        ),
    ]
