# Generated by Django 5.2.9 on 2026-03-12 04:20

from django.db import migrations, models


def backfill_chat_type(apps, schema_editor):
    """Backfill chat_type from existing is_patient and professional_user fields."""
    OngoingChat = apps.get_model("fighthealthinsurance", "OngoingChat")
    # Patient chats
    OngoingChat.objects.filter(is_patient=True).update(chat_type="patient")
    # Professional chats (is_patient=False and has professional_user)
    OngoingChat.objects.filter(
        is_patient=False, professional_user__isnull=False
    ).update(chat_type="professional")
    # Trial professional chats (is_patient=False, no professional_user, no user,
    # and no hashed_email — rows with user or hashed_email are legacy patients)
    OngoingChat.objects.filter(
        is_patient=False,
        professional_user__isnull=True,
        user__isnull=True,
        hashed_email__isnull=True,
    ).update(chat_type="trial_professional")


def reverse_backfill(apps, schema_editor):
    """Reverse backfill: set is_patient from chat_type."""
    OngoingChat = apps.get_model("fighthealthinsurance", "OngoingChat")
    OngoingChat.objects.filter(chat_type="patient").update(is_patient=True)
    OngoingChat.objects.filter(
        chat_type__in=["professional", "trial_professional"]
    ).update(is_patient=False)


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0149_deletetoken_rename_email_to_hashed_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="ongoingchat",
            name="chat_type",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("trial_professional", "Trial Professional"),
                    ("professional", "Professional"),
                ],
                default="patient",
                help_text="Type of chat user: patient, trial professional, or full professional",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_chat_type, reverse_backfill),
    ]
