# Generated by Django 5.2.9 on 2026-03-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0150_pubmedarticlesummarized_authors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ongoingchat",
            name="edited_chat_history",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Cleaned up / edited version of chat_history for review purposes",
                null=True,
            ),
        ),
    ]
