# Generated by Django 5.2.11 on 2026-02-22 00:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "fighthealthinsurance",
            "0147_extralinkdocument_extralinkfetchlog_and_more",
        ),
        ("fighthealthinsurance", "0151_add_patient_performance_indexes"),
    ]

    operations = []
