# Generated by Django 5.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0152_ongoingchat_edited_chat_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsedDeleteToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("hashed_email", models.CharField(max_length=300)),
                ("used_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
