# Generated by Django 5.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0153_useddeletetoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="followuptype",
            name="template_name",
            field=models.CharField(blank=True, default="followup", max_length=100),
        ),
    ]
