# Generated by Django 5.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0155_populate_followup_types"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="followupsched",
            constraint=models.UniqueConstraint(
                condition=models.Q(("follow_up_type__isnull", False)),
                fields=("denial_id", "follow_up_type"),
                name="unique_denial_followup_type",
            ),
        ),
    ]
