# Generated by Django 5.2.9 on 2026-03-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0157_cleanup_empty_pubmed_query_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useddeletetoken",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
