# Generated by Django 5.2.9

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0158_alter_useddeletetoken_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatDocument",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("document_name", models.CharField(max_length=500)),
                ("full_text", models.TextField()),
                ("summary", models.TextField(blank=True)),
                ("chunk_summaries", models.JSONField(blank=True, default=list)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("char_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="fighthealthinsurance.ongoingchat",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["chat", "created_at"],
                        name="chatdoc_chat_created_idx",
                    ),
                ],
            },
        ),
    ]
