# Generated by Django 5.2.9 on 2026-03-30 05:09

import django.core.files.storage
import django.db.models.deletion
import django_encrypted_filefield.fields
import django_prometheus.models
import fighthealthinsurance.combined_storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0158_alter_useddeletetoken_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_enc",
                    django_encrypted_filefield.fields.EncryptedFileField(
                        null=True,
                        storage=fighthealthinsurance.combined_storage.CombinedStorage(
                            django.core.files.storage.FileSystemStorage(
                                location="localish_data"
                            ),
                            django.core.files.storage.FileSystemStorage(
                                location="/external_data"
                            ),
                            django.core.files.storage.FileSystemStorage(
                                location="external_data_b"
                            ),
                            None,
                        ),
                        upload_to="",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("summary_of_benefits", "Summary of Benefits"),
                            ("medical_policy", "Medical Policy"),
                            ("other", "Other Policy Document"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "plan_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("employer_erisa", "Employer Plan (ERISA)"),
                            (
                                "employer_non_erisa",
                                "Employer Plan (Non-ERISA, e.g. government/church)",
                            ),
                            (
                                "aca_marketplace",
                                "ACA Marketplace (Healthcare.gov / State Exchange)",
                            ),
                            ("medicare_traditional", "Medicare (Traditional/Original)"),
                            ("medicare_advantage", "Medicare Advantage (Part C)"),
                            ("medicaid_chip", "Medicaid / CHIP"),
                            ("tricare", "TRICARE (Military)"),
                            ("va", "VA Health Care"),
                            (
                                "individual_off_exchange",
                                "Individual Plan (Off-Exchange)",
                            ),
                            ("short_term", "Short-Term Health Plan"),
                            ("unknown", "I'm Not Sure"),
                        ],
                        default="unknown",
                        max_length=50,
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255)),
                (
                    "hashed_email",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Policy Document",
                "verbose_name_plural": "Policy Documents",
                "indexes": [
                    models.Index(
                        fields=["hashed_email"], name="fighthealth_hashed__941c87_idx"
                    ),
                    models.Index(
                        fields=["session_key"], name="fighthealth_session_78e69d_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="fighthealth_created_b293c0_idx"
                    ),
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("PolicyDocument"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="PolicyDocumentAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_question", models.TextField(blank=True)),
                ("exclusions", models.JSONField(default=list)),
                ("inclusions", models.JSONField(default=list)),
                ("appeal_clauses", models.JSONField(default=list)),
                ("summary", models.TextField(blank=True)),
                ("quotable_sections", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="fighthealthinsurance.policydocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Document Analysis",
                "verbose_name_plural": "Policy Document Analyses",
                "indexes": [
                    models.Index(
                        fields=["policy_document"],
                        name="fighthealth_policy__a32f41_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="fighthealth_created_37c5eb_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy_document", "user_question"),
                        name="unique_policy_analysis",
                    )
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "PolicyDocumentAnalysis"
                ),
                models.Model,
            ),
        ),
    ]
