# Generated by Django 5.2.9 on 2026-03-23 07:00

import django.db.models.deletion
import django_encrypted_filefield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0159_chatdocument"),
        ("fhi_users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceCallLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("call_date", models.DateTimeField()),
                (
                    "representative_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("call_outcome", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("follow_up_needed", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appeal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_logs",
                        to="fighthealthinsurance.appeal",
                    ),
                ),
                (
                    "patient_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_logs",
                        to="fhi_users.patientuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-call_date"],
            },
        ),
        migrations.CreateModel(
            name="PatientEvidence",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "file",
                    django_encrypted_filefield.fields.EncryptedFileField(
                        null=True, upload_to=""
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=127)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appeal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_evidence",
                        to="fighthealthinsurance.appeal",
                    ),
                ),
                (
                    "patient_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="fhi_users.patientuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
