# Generated by Django 5.2.9 on 2026-05-03 00:58

import django.core.files.storage
import django.db.models.deletion
import django.db.models.functions.datetime
import django_encrypted_filefield.fields
import django_prometheus.models
import fighthealthinsurance.combined_storage
import fighthealthinsurance.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0159_chatdocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="NICEGuidance",
            fields=[
                ("internal_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "guidance_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("title", models.TextField(blank=True)),
                ("url", models.TextField(blank=True)),
                ("guidance_type", models.CharField(blank=True, max_length=200)),
                ("summary", models.TextField(blank=True)),
                (
                    "created",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), null=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="denial",
            name="nice_context",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insurancecompany",
            name="appeal_address",
            field=models.TextField(
                blank=True,
                help_text="Default mailing address for written appeals (multi-line, free-form)",
            ),
        ),
        migrations.AddField(
            model_name="insurancecompany",
            name="appeal_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address for submitting appeals, if accepted",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="insurancecompany",
            name="appeal_fax_number",
            field=models.CharField(
                blank=True,
                help_text="Default fax number for appeals (e.g., 877-815-4827)",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="insurancecompany",
            name="appeal_phone_number",
            field=models.CharField(
                blank=True,
                help_text="Default member services / appeals phone number",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="insurancecompany",
            name="appeals_info_url",
            field=models.URLField(
                blank=True,
                help_text="Specific URL on the carrier's site that documents the appeals process (source for the values below)",
            ),
        ),
        migrations.AddField(
            model_name="insurancecompany",
            name="appeals_portal_url",
            field=models.URLField(
                blank=True,
                help_text="Online portal URL for submitting appeals electronically",
            ),
        ),
        migrations.AddField(
            model_name="insurancecompany",
            name="member_services_url",
            field=models.URLField(
                blank=True,
                help_text="Member services / contact-us page where appeal info is published",
            ),
        ),
        migrations.AddField(
            model_name="insurancecompany",
            name="parent_company",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent / umbrella company (e.g., Elevance Health for Anthem brands)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subsidiaries",
                to="fighthealthinsurance.insurancecompany",
            ),
        ),
        migrations.AddField(
            model_name="insuranceplan",
            name="appeal_address",
            field=models.TextField(
                blank=True,
                help_text="Plan-specific mailing address for appeals (overrides company default)",
            ),
        ),
        migrations.AddField(
            model_name="insuranceplan",
            name="appeal_email",
            field=models.EmailField(
                blank=True,
                help_text="Plan-specific email for submitting appeals (overrides company default)",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="insuranceplan",
            name="appeal_fax_number",
            field=models.CharField(
                blank=True,
                help_text="Plan-specific appeals fax number (overrides company default)",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="insuranceplan",
            name="appeal_phone_number",
            field=models.CharField(
                blank=True,
                help_text="Plan-specific appeals phone number (overrides company default)",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="insuranceplan",
            name="appeals_info_url",
            field=models.URLField(
                blank=True,
                help_text="URL documenting the appeals process for this specific plan (source)",
            ),
        ),
        migrations.AddField(
            model_name="insuranceplan",
            name="appeals_portal_url",
            field=models.URLField(
                blank=True, help_text="Plan-specific online appeals portal URL"
            ),
        ),
        migrations.AddField(
            model_name="loststripesession",
            name="secure_token",
            field=models.CharField(
                db_index=True,
                default=fighthealthinsurance.utils.sekret_gen,
                max_length=64,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="CMSCoverageCache",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("procedure", models.CharField(max_length=300)),
                ("diagnosis", models.CharField(max_length=300)),
                ("generic_citations", models.JSONField(default=list)),
                ("medicare_citations", models.JSONField(default=list)),
                ("generic_updated_at", models.DateTimeField(blank=True, null=True)),
                ("medicare_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["procedure", "diagnosis"],
                        name="fighthealth_procedu_3ccc23_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("procedure", "diagnosis"), name="cms_cov_proc_diag_uniq"
                    )
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("CMSCoverageCache"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ECRIGuideline",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "guideline_id",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                (
                    "source",
                    models.CharField(default="ECRI Guidelines Trust", max_length=64),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "developer_organization",
                    models.CharField(blank=True, max_length=300),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("last_updated", models.DateField(blank=True, null=True)),
                ("recommendations_summary", models.TextField(blank=True)),
                ("intended_population", models.TextField(blank=True)),
                ("intended_users", models.CharField(blank=True, max_length=300)),
                ("evidence_quality", models.CharField(blank=True, max_length=100)),
                ("procedure_keywords", models.JSONField(blank=True, default=list)),
                ("diagnosis_keywords", models.JSONField(blank=True, default=list)),
                ("topics", models.JSONField(blank=True, default=list)),
                ("url", models.URLField(blank=True, max_length=2000)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ECRI Clinical Guideline",
                "verbose_name_plural": "ECRI Clinical Guidelines",
                "ordering": ["-publication_date", "title"],
                "indexes": [
                    models.Index(
                        fields=["source", "is_active"],
                        name="fighthealth_source_012590_idx",
                    )
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("ECRIGuideline"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="NICEQueryData",
            fields=[
                ("internal_id", models.AutoField(primary_key=True, serialize=False)),
                ("query", models.TextField()),
                ("results", models.TextField(null=True)),
                (
                    "created",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), null=True
                    ),
                ),
                (
                    "denial_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fighthealthinsurance.denial",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolicyDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_enc",
                    django_encrypted_filefield.fields.EncryptedFileField(
                        null=True,
                        storage=fighthealthinsurance.combined_storage.CombinedStorage(
                            django.core.files.storage.FileSystemStorage(
                                location="localish_data"
                            ),
                            django.core.files.storage.FileSystemStorage(
                                location="/external_data"
                            ),
                            django.core.files.storage.FileSystemStorage(
                                location="external_data_b"
                            ),
                            None,
                        ),
                        upload_to="",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("summary_of_benefits", "Summary of Benefits"),
                            ("medical_policy", "Medical Policy"),
                            ("other", "Other Policy Document"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "plan_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("employer_erisa", "Employer Plan (ERISA)"),
                            (
                                "employer_non_erisa",
                                "Employer Plan (Non-ERISA, e.g. government/church)",
                            ),
                            (
                                "aca_marketplace",
                                "ACA Marketplace (Healthcare.gov / State Exchange)",
                            ),
                            ("medicare_traditional", "Medicare (Traditional/Original)"),
                            ("medicare_advantage", "Medicare Advantage (Part C)"),
                            ("medicaid_chip", "Medicaid / CHIP"),
                            ("tricare", "TRICARE (Military)"),
                            ("va", "VA Health Care"),
                            (
                                "individual_off_exchange",
                                "Individual Plan (Off-Exchange)",
                            ),
                            ("short_term", "Short-Term Health Plan"),
                            ("unknown", "I'm Not Sure"),
                        ],
                        default="unknown",
                        max_length=50,
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255)),
                (
                    "hashed_email",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Policy Document",
                "verbose_name_plural": "Policy Documents",
                "indexes": [
                    models.Index(
                        fields=["hashed_email"], name="fighthealth_hashed__941c87_idx"
                    ),
                    models.Index(
                        fields=["session_key"], name="fighthealth_session_78e69d_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="fighthealth_created_b293c0_idx"
                    ),
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("PolicyDocument"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="USPSTFRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uspstf_id", models.CharField(max_length=128, unique=True)),
                ("title", models.TextField()),
                ("grade", models.CharField(blank=True, default="", max_length=4)),
                (
                    "status",
                    models.CharField(blank=True, default="current", max_length=32),
                ),
                ("topic", models.TextField(blank=True, default="")),
                ("population", models.TextField(blank=True, default="")),
                ("short_description", models.TextField(blank=True, default="")),
                ("rationale", models.TextField(blank=True, default="")),
                ("clinical_considerations", models.TextField(blank=True, default="")),
                ("url", models.TextField(blank=True, default="")),
                (
                    "date_issued",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["grade"], name="fighthealth_grade_faa01b_idx"),
                    models.Index(fields=["topic"], name="fighthealth_topic_33a6ad_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PolicyDocumentAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_question", models.TextField(blank=True)),
                ("exclusions", models.JSONField(default=list)),
                ("inclusions", models.JSONField(default=list)),
                ("appeal_clauses", models.JSONField(default=list)),
                ("summary", models.TextField(blank=True)),
                ("quotable_sections", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="fighthealthinsurance.policydocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Document Analysis",
                "verbose_name_plural": "Policy Document Analyses",
                "indexes": [
                    models.Index(
                        fields=["policy_document"],
                        name="fighthealth_policy__a32f41_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="fighthealth_created_37c5eb_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy_document", "user_question"),
                        name="unique_policy_analysis",
                    )
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "PolicyDocumentAnalysis"
                ),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="RegulatorEscalation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("hashed_email", models.CharField(max_length=300)),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("doi", "State DOI / Insurance Commissioner"),
                            ("medical_director", "Plan Medical Director"),
                            ("dol_ebsa", "DOL EBSA (ERISA)"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("recipient_address", models.TextField(blank=True, default="")),
                (
                    "recipient_phone",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "recipient_url",
                    models.CharField(blank=True, default="", max_length=400),
                ),
                ("letter_text", models.TextField(blank=True, default="")),
                ("chosen", models.BooleanField(default=False)),
                ("edited", models.BooleanField(default=False)),
                ("sent", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("mod_date", models.DateTimeField(auto_now=True)),
                (
                    "for_denial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regulator_escalations",
                        to="fighthealthinsurance.denial",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["for_denial"], name="reg_escal_denial_idx"),
                    models.Index(fields=["hashed_email"], name="reg_escal_email_idx"),
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "RegulatorEscalation"
                ),
                models.Model,
            ),
        ),
    ]
