# Generated by Django 5.2.9

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0163_imrdecision_pg_trgm_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayerPriorAuthRequirement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "line_of_business",
                    models.CharField(
                        choices=[
                            ("commercial", "Commercial"),
                            ("medicare_advantage", "Medicare Advantage"),
                            ("medicaid", "Medicaid"),
                            ("exchange", "Exchange / Marketplace"),
                            ("dsnp", "Dual Special Needs Plan"),
                            ("other", "Other"),
                            ("all", "All Lines of Business"),
                        ],
                        db_index=True,
                        default="all",
                        max_length=30,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Two-letter state code if requirement is state-specific",
                        max_length=2,
                    ),
                ),
                (
                    "cpt_hcpcs_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Specific CPT or HCPCS code requiring PA (leave blank for ranges)",
                        max_length=10,
                    ),
                ),
                (
                    "code_range_start",
                    models.CharField(
                        blank=True,
                        help_text="Inclusive start of a CPT/HCPCS range (alphanumeric compare)",
                        max_length=10,
                    ),
                ),
                (
                    "code_range_end",
                    models.CharField(
                        blank=True,
                        help_text="Inclusive end of a CPT/HCPCS range",
                        max_length=10,
                    ),
                ),
                ("code_description", models.TextField(blank=True)),
                (
                    "pa_category",
                    models.CharField(
                        blank=True,
                        help_text="Category like 'Genetic Testing', 'Outpatient Surgery'",
                        max_length=200,
                    ),
                ),
                (
                    "requires_pa",
                    models.BooleanField(
                        default=True,
                        help_text="True if PA is required. Set False for entries that explicitly do NOT require PA.",
                    ),
                ),
                (
                    "notification_only",
                    models.BooleanField(
                        default=False,
                        help_text="True for codes that only require notification (not full PA review)",
                    ),
                ),
                (
                    "submission_channel",
                    models.TextField(
                        blank=True,
                        help_text="How to submit (e.g., 'UHCprovider.com / 866-889-8054')",
                    ),
                ),
                (
                    "criteria_reference",
                    models.TextField(
                        blank=True,
                        help_text="Pointer to coverage criteria (e.g., a UHC Medical Policy or Coverage Determination Guideline name)",
                    ),
                ),
                ("criteria_url", models.URLField(blank=True)),
                (
                    "source_document",
                    models.CharField(
                        blank=True,
                        help_text="Filename or title of the source PA requirement list",
                        max_length=300,
                    ),
                ),
                ("source_document_date", models.DateField(blank=True, null=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "insurance_company",
                    models.ForeignKey(
                        help_text="Payer that publishes this PA requirement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pa_requirements",
                        to="fighthealthinsurance.insurancecompany",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific plan this requirement applies to (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pa_requirements",
                        to="fighthealthinsurance.insuranceplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payer Prior Auth Requirement",
                "verbose_name_plural": "Payer Prior Auth Requirements",
                "indexes": [
                    models.Index(
                        fields=["insurance_company", "cpt_hcpcs_code"],
                        name="pa_req_company_code_idx",
                    ),
                    models.Index(
                        fields=[
                            "insurance_company",
                            "line_of_business",
                            "cpt_hcpcs_code",
                        ],
                        name="pa_req_co_lob_code_idx",
                    ),
                ],
            },
        ),
    ]
