# Generated by Django 5.1.1 on 2026-05-04 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0165_alter_ucrgeographicarea_id_alter_ucrlookup_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="insurancecompany",
            name="is_major_commercial_payer",
            field=models.BooleanField(
                default=False,
                help_text="True if this is a major national commercial carrier whose public medical policies should be prioritized as comparative industry evidence in appeals (Aetna, UnitedHealthcare, Cigna, Anthem, Humana, Kaiser, etc.). Used to order the comparative-payer section so it surfaces nationally recognized carriers ahead of regional BCBS affiliates.",
            ),
        ),
        migrations.AddField(
            model_name="insurancecompany",
            name="medical_policy_name",
            field=models.CharField(
                blank=True,
                help_text="Name the company uses for its medical-policy documents (e.g., 'Clinical Policy Bulletins', 'Coverage Policy', 'Medical Policy', 'Clinical UM Guideline')",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="insurancecompany",
            name="medical_policy_notes",
            field=models.TextField(
                blank=True,
                help_text="Short description of how this payer's medical policies are used / what they assert (e.g., medical-necessity criteria, experimental/investigational determinations).",
            ),
        ),
        migrations.AddField(
            model_name="insurancecompany",
            name="medical_policy_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the company's public medical/coverage/clinical-policy index",
            ),
        ),
        migrations.AddField(
            model_name="insurancecompany",
            name="medical_policy_url_is_static_index",
            field=models.BooleanField(
                default=False,
                help_text="True if medical_policy_url points to a static, directly-browsable index (an HTML page or PDF that lists policies and links to individual policy documents without requiring search or state selection). False (the default) means the URL is a search portal, requires state/region selection, or otherwise needs interactive navigation. Used to distinguish links that could be pre-fetched and parsed from links that are pointers only.",
            ),
        ),
        migrations.CreateModel(
            name="PayerPolicyEntry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        help_text="Policy title as listed in the payer's index (e.g., 'Acupuncture')",
                        max_length=500,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Direct URL to the individual policy document (PDF or HTML)",
                        max_length=2000,
                    ),
                ),
                (
                    "payer_policy_id",
                    models.CharField(
                        blank=True,
                        help_text="Payer-internal policy id (e.g. 'mm_0540', '0001'), if extractable",
                        max_length=100,
                    ),
                ),
                ("last_indexed", models.DateTimeField(auto_now=True)),
                (
                    "insurance_company",
                    models.ForeignKey(
                        help_text="The payer that publishes this policy",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_entries",
                        to="fighthealthinsurance.insurancecompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payer Policy Entry",
                "verbose_name_plural": "Payer Policy Entries",
                "indexes": [
                    models.Index(
                        fields=["insurance_company", "title"],
                        name="fighthealth_insuran_86fbc4_idx",
                    )
                ],
                "unique_together": {("insurance_company", "url")},
            },
        ),
    ]
