# Generated by Django 5.1.1 on 2026-05-04 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0166_insurancecompany_is_major_commercial_payer_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loststripesession",
            name="secure_token",
        ),
    ]
