# Generated by Django 5.1.1 on 2026-05-04 02:36

import fighthealthinsurance.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0167_remove_loststripesession_secure_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="loststripesession",
            name="secure_token",
            field=models.CharField(
                db_index=True,
                max_length=128,
                null=True,
            ),
        ),
    ]
