# Generated by Django A.B on YYYY-MM-DD HH:MM
from django.db import migrations
import uuid
from fighthealthinsurance.utils import sekret_gen


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("fighthealthinsurance", "LostStripeSession")
    for row in MyModel.objects.all():
        row.secure_token = str(sekret_gen())
        row.save(update_fields=["secure_token"])


class Migration(migrations.Migration):
    dependencies = [
        ("fighthealthinsurance", "0168_loststripesession_secure_token"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
