# Generated by Django 5.2.9 on 2026-05-04 02:42

import fighthealthinsurance.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0169_fix_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loststripesession",
            name="secure_token",
            field=models.CharField(
                db_index=True,
                default=fighthealthinsurance.utils.sekret_gen,
                max_length=128,
                unique=True,
            ),
        ),
    ]
