# Generated by Django 5.1.1 on 2026-05-04 02:52

import fighthealthinsurance.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0170_alter_loststripesession_secure_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denial",
            name="follow_up_semi_sekret",
            field=models.CharField(
                default=fighthealthinsurance.utils.sekret_gen, max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="denial",
            name="semi_sekret",
            field=models.CharField(
                default=fighthealthinsurance.utils.sekret_gen, max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="loststripesession",
            name="secure_token",
            field=models.CharField(
                db_index=True,
                default=fighthealthinsurance.utils.sekret_gen,
                max_length=256,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="mailinglistsubscriber",
            name="unsubscribe_token",
            field=models.CharField(
                default=fighthealthinsurance.utils.sekret_gen, max_length=256
            ),
        ),
    ]
