# Generated by Django 5.2.9 on 2026-06-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0181_alter_clinicaltrialquerydata_query"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelHealthAlertState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("last_alert_sent", models.DateTimeField()),
            ],
        ),
    ]
