# Generated by Django 5.2.9 on 2026-06-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0181_alter_clinicaltrialquerydata_query"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelHealthAlertState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("last_alert_sent", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="proposedappeal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="proposedappeal",
            name="model_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
    ]
