# Generated by Django 5.2.9 on 2026-06-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0184_denial_extract_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="demorequests",
            name="asn",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="demorequests",
            name="asn_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="demorequests",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loststripesession",
            name="asn",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="loststripesession",
            name="asn_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="loststripesession",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
