# Generated by Django 5.2.9 on 2026-06-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0185_demo_request_and_lost_session_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loststripesession",
            name="ip_address",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
