# Generated by Django 5.2.9 on 2026-06-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0186_loststripesession_ip_address_charfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demorequests",
            name="ip_address",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="denial",
            name="ip_address",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="ongoingchat",
            name="ip_address",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
