# Generated by Django 5.2.9 on 2026-06-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0187_ip_address_charfields"),
    ]

    operations = [
        migrations.AddField(
            model_name="interestedprofessional",
            name="proconnector_attempted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="interestedprofessional",
            name="proconnector_email_body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interestedprofessional",
            name="proconnector_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interestedprofessional",
            name="proconnector_skip_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interestedprofessional",
            name="proconnector_skipped",
            field=models.BooleanField(default=False),
        ),
    ]
