# Generated by Django 5.2.9 on 2026-06-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0187_ip_address_charfields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Plain-text message shown to every visitor in the site header. Line breaks are preserved."
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info (blue)"),
                            ("warning", "Warning (yellow)"),
                            ("danger", "Critical (red)"),
                        ],
                        default="warning",
                        help_text="Controls the banner color.",
                        max_length=16,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide the banner without deleting it.",
                    ),
                ),
                (
                    "dismissible",
                    models.BooleanField(
                        default=True,
                        help_text="Let visitors close the banner (it stays closed in their browser until you edit the message).",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional. If set, the banner automatically stops showing after this time. Leave blank to keep showing until you remove it.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
    ]
