# Generated by Django 5.2.9 on 2026-06-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0187_ip_address_charfields"),
    ]

    operations = [
        migrations.AddField(
            model_name="faxestosend",
            name="vendor_send_completed",
            field=models.BooleanField(default=False),
        ),
    ]
