# Generated by Django 5.2.9 on 2026-06-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0188_sitebanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposedappeal",
            name="synthesized",
            field=models.BooleanField(default=False, db_index=True),
        ),
        migrations.AddField(
            model_name="choosercandidate",
            name="synthesized",
            field=models.BooleanField(default=False),
        ),
    ]
