# Generated by Django 5.2.9 on 2026-06-21 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0190_interestedprofessional_proconnector_attempted_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledEmail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("to_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(default="", max_length=998)),
                ("template_name", models.CharField(max_length=100)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("cc", models.JSONField(blank=True, default=list)),
                (
                    "send_after",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "send_timezone",
                    models.CharField(default="America/Los_Angeles", max_length=64),
                ),
                ("timezone_is_specific", models.BooleanField(default=False)),
                ("purpose", models.CharField(blank=True, default="", max_length=64)),
                ("sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sent", "send_after"],
                        name="sched_email_sent_after_idx",
                    ),
                ],
            },
        ),
    ]
