# Generated by Django 5.2.9 on 2026-07-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0191_scheduledemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="faxestosend",
            name="vendor_send_completed",
            field=models.BooleanField(default=False),
        ),
    ]
