# Generated by Django 5.2.9 on 2026-07-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0191_scheduledemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="regulator",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Consumer assistance / complaint line for this regulator (e.g., 1-866-444-3272 for DOL EBSA)",
                max_length=40,
            ),
        ),
    ]
