# Generated by Django 5.2.9 on 2026-07-10 23:15

from django.db import migrations, models

# Existing deployments already have the seeded regulator rows, and
# `migrate` does not re-run `loaddata`, so backfill the new phone column
# for the known rows here. Match on stable identifiers (alt_name, or name
# for the HHS row which has no alt_name) and only fill blanks so any
# admin-entered value wins.
_PHONES_BY_ALT_NAME = {
    "ERISA": "1-866-444-3272",  # DOL EBSA consumer assistance
    "CMS": "1-800-633-4227",  # 1-800-MEDICARE
    "CDMC": "1-888-466-2219",  # CA DMHC Help Center
}
_PHONES_BY_NAME = {
    # HHS Office for Civil Rights toll-free line.
    "U.S. Dept. of Health and Human Services.": "1-800-368-1019",
}


def _seed_regulator_phones(apps, schema_editor):
    Regulator = apps.get_model("fighthealthinsurance", "Regulator")
    for alt_name, phone in _PHONES_BY_ALT_NAME.items():
        Regulator.objects.filter(alt_name=alt_name, phone="").update(phone=phone)
    for name, phone in _PHONES_BY_NAME.items():
        Regulator.objects.filter(name=name, phone="").update(phone=phone)


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0192_faxestosend_vendor_send_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="regulator",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Consumer assistance / complaint line for this regulator (e.g., 1-866-444-3272 for DOL EBSA)",
                max_length=40,
            ),
        ),
        migrations.RunPython(
            _seed_regulator_phones, reverse_code=migrations.RunPython.noop
        ),
    ]
