# Generated by Django 5.2.9 on 2026-07-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0192_faxestosend_vendor_send_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelBackendHealthCheckResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(db_index=True, max_length=64)),
                (
                    "deployment_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "environment",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=100)),
                ("model_name", models.CharField(db_index=True, max_length=200)),
                (
                    "internal_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("ok", models.BooleanField(default=False)),
                ("category", models.CharField(db_index=True, max_length=64)),
                ("error", models.TextField(blank=True, default="")),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("ui_registered", models.BooleanField(default=False)),
                ("reporting_registered", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["model_name", "-created_at"],
                        name="mbhc_model_created_idx",
                    )
                ],
            },
        ),
    ]
