# Generated by Django 5.2.9 on 2026-07-11 00:54

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0193_modelbackendhealthcheckresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorstInsuranceReport",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("period", models.CharField(max_length=7)),
                (
                    "methodology_version",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("window_start", models.DateField(blank=True, null=True)),
                ("window_end", models.DateField(blank=True, null=True)),
                ("weights", models.JSONField(blank=True, null=True)),
                ("thresholds", models.JSONField(blank=True, null=True)),
                ("sources", models.JSONField(blank=True, null=True)),
                ("state_statuses", models.JSONField(blank=True, null=True)),
                ("source_url", models.URLField(blank=True, default="", max_length=500)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("period",), name="worstins_report_period_uniq"
                    )
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "WorstInsuranceReport"
                ),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="WorstInsuranceRanking",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("state", models.CharField(max_length=2)),
                ("rank", models.IntegerField()),
                ("issuer_name", models.CharField(max_length=300)),
                ("issuer_slug", models.SlugField(max_length=300)),
                (
                    "group_affiliation",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("composite_score", models.FloatField()),
                ("weight_coverage", models.FloatField(blank=True, null=True)),
                ("member_months", models.BigIntegerField(blank=True, null=True)),
                ("metrics", models.JSONField(blank=True, null=True)),
                ("metrics_available", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "insurance_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worst_insurance_rankings",
                        to="fighthealthinsurance.insurancecompany",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rankings",
                        to="fighthealthinsurance.worstinsurancereport",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["state", "rank"], name="worstins_state_rank_idx"
                    ),
                    models.Index(
                        fields=["report", "state"], name="worstins_report_state_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("report", "state", "issuer_slug"),
                        name="worstins_rank_report_state_issuer_uniq",
                    )
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "WorstInsuranceRanking"
                ),
                models.Model,
            ),
        ),
    ]
