# Generated by Django 5.2.9 on 2026-07-28 22:43

import fighthealthinsurance.utils
from django.db import migrations, models


def backfill_unsubscribe_tokens(apps, schema_editor):
    """Give every pre-existing row its own unsubscribe token.

    ``AddField`` with a callable default evaluates that callable *once* and
    writes the same value to every existing row, so without this step the whole
    back catalogue would share a single token -- one person's unsubscribe link
    would resolve to somebody else's record. New rows are unaffected (the
    default runs per-insert); this only repairs the backfilled ones.
    """
    InterestedProfessional = apps.get_model(
        "fighthealthinsurance", "InterestedProfessional"
    )
    to_update = []
    for pro in InterestedProfessional.objects.all().iterator():
        pro.unsubscribe_token = fighthealthinsurance.utils.sekret_gen()
        to_update.append(pro)
        if len(to_update) >= 1000:
            InterestedProfessional.objects.bulk_update(to_update, ["unsubscribe_token"])
            to_update = []
    if to_update:
        InterestedProfessional.objects.bulk_update(to_update, ["unsubscribe_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0197_denial_candidate_denial_text_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="interestedprofessional",
            name="unsubscribe_token",
            field=models.CharField(
                default=fighthealthinsurance.utils.sekret_gen, max_length=256
            ),
        ),
        migrations.AddField(
            model_name="interestedprofessional",
            name="unsubscribed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="interestedprofessional",
            name="unsubscribed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            backfill_unsubscribe_tokens,
            # Reversing just drops the column, so there is nothing to undo.
            migrations.RunPython.noop,
        ),
    ]
