# Generated by Django 5.2.9 on 2026-07-30 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0197_denial_candidate_denial_text_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelCallAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generation_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "run_kind",
                    models.CharField(
                        blank=True, db_index=True, default="live", max_length=32
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=200
                    ),
                ),
                ("backend", models.CharField(blank=True, default="", max_length=300)),
                ("stage", models.CharField(blank=True, default="", max_length=32)),
                (
                    "context_level",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("infer_type", models.CharField(blank=True, default="", max_length=64)),
                ("outcome", models.CharField(db_index=True, max_length=64)),
                ("error_detail", models.TextField(blank=True, default="")),
                ("response_text", models.TextField(blank=True, null=True)),
                ("response_chars", models.IntegerField(blank=True, null=True)),
                ("prompt_tokens_est", models.IntegerField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "for_denial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_call_attempts",
                        to="fighthealthinsurance.denial",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["for_denial", "-created_at"],
                        name="mca_denial_created_idx",
                    ),
                    models.Index(
                        fields=["outcome", "-created_at"], name="mca_outcome_idx"
                    ),
                ],
            },
        ),
    ]
