# Generated by Django 5.2.9 on 2026-07-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0198_generic_context_purge_and_unique"),
        ("fighthealthinsurance", "0198_modelcallattempt"),
    ]

    operations = []
