# Generated by Django 5.2.9 on 2026-07-30 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0198_interestedprofessional_unsubscribe_token_and_more",
        ),
        ("fighthealthinsurance", "0199_merge_20260730_1939"),
        ("fighthealthinsurance", "0199_merge_20260730_2031"),
    ]

    operations = []
