# Generated by Django 5.2.9 on 2026-09-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0202_appealgenerationlease"),
        ("fighthealthinsurance", "0202_backfill_proposedappeal_fingerprints"),
    ]

    operations = []
