# Generated by Django 5.2.9 on 2026-09-04 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0203_merge_20260904_2157"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntakeJourneyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("intake_started", "Intake started"),
                            ("form_completed", "Form completed"),
                            ("nudge_claimed", "Abandonment nudge claimed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("acked_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("claimed_token", models.UUIDField(blank=True, null=True)),
                ("claimed_until", models.DateTimeField(blank=True, null=True)),
                ("attempted_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("claimed", "Claimed"),
                            ("skipped_completed", "Skipped: form completed"),
                            ("sent", "Sent"),
                            ("smtp_failed", "SMTP failed"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                (
                    "denial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake_events",
                        to="fighthealthinsurance.denial",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=models.Q(("acked_at__isnull", True)),
                        fields=["next_attempt_at", "id"],
                        name="intake_event_pending_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("denial", "event_type"),
                        name="uniq_intake_event_per_denial",
                    )
                ],
            },
        ),
    ]
