# Generated by Django 5.2.9 on 2026-09-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0208_dataremovaltotals"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposedappeal",
            name="built_for_state",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
