# Generated by Django 5.2.9 on 2026-09-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0208_dataremovaltotals"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="generated_questions_for",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
