# Generated by Django 5.2.9 on 2026-09-26 20:22
#
# One row per chat turn: which models raced, how each call ended, which one
# won, and which side-by-side answer the person picked. Metadata only, and
# deleted with its chat.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0213_proposedappeal_professional_pick"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatTurn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("failed", "Failed"),
                            ("timeout", "Timed out"),
                        ],
                        max_length=16,
                    ),
                ),
                ("use_external", models.BooleanField()),
                ("backends", models.JSONField(blank=True, default=list)),
                ("fallback_backends", models.JSONField(blank=True, default=list)),
                ("calls", models.JSONField(blank=True, default=list)),
                (
                    "winner_model",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("winner_score", models.FloatField(blank=True, null=True)),
                (
                    "winner_pass",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("winner_external", models.BooleanField(blank=True, null=True)),
                (
                    "runner_up_model",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("runner_up_score", models.FloatField(blank=True, null=True)),
                ("closely_tied", models.BooleanField(default=False)),
                ("rejected_repeats", models.PositiveIntegerField(default=0)),
                ("delivered_repeat", models.BooleanField(default=False)),
                ("retry_ran", models.BooleanField(default=False)),
                ("retry_used", models.BooleanField(default=False)),
                ("tool_passes", models.PositiveSmallIntegerField(default=0)),
                ("tool_rewrote", models.BooleanField(default=False)),
                ("fanout_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("turn_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("alternate_offered", models.BooleanField(default=False)),
                (
                    "alternate_model",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("alternate_cross_model", models.BooleanField(default=False)),
                (
                    "preferred",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No pick"),
                            ("primary", "Primary"),
                            ("alternate", "Alternate"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("preferred_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_turns",
                        to="fighthealthinsurance.ongoingchat",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["chat", "-created_at"], name="chatturn_chat_created_idx"
                    )
                ],
            },
        ),
    ]
