# Generated by Django 5.2.9 on 2026-09-26 21:17
#
# The chat routing policy table (append-only rows, newest wins; model names
# and numbers only), and on each chat turn how the primary pass started the
# outside models and the delay it used.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0214_chatturn"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoutingPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("temporal", "Temporal schedule"),
                            ("manual", "compute_chat_policy command"),
                        ],
                        max_length=16,
                    ),
                ),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("window_minutes", models.PositiveIntegerField()),
                ("turns_considered", models.PositiveIntegerField(default=0)),
                ("external_excluded", models.JSONField(blank=True, default=list)),
                ("external_delay_seconds", models.FloatField(default=0.0)),
                ("daily_call_caps", models.JSONField(blank=True, default=dict)),
                ("calls_today", models.JSONField(blank=True, default=dict)),
                ("exhausted", models.JSONField(blank=True, default=list)),
                ("internal_usable_rate", models.FloatField(blank=True, null=True)),
                (
                    "internal_ttu_p75_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=64)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="chatturn",
            name="external_delay_seconds",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="external_start",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No outside model asked"),
                    ("immediate", "Asked with ours"),
                    ("after_delay", "Started after the delay"),
                    ("early", "Started early: ours all failed"),
                    ("skipped", "Skipped: ours answered first"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
