# Generated by Django 5.2.9 on 2026-09-26 21:30
#
# Shadow scores on each chat turn row: TypeSafe's answers to three questions
# about the delivered reply and the second answer, the scorer string and an
# outcome. Numbers and labels only, never text.
#
# Numbered 0216 because another open branch adds a 0215. It depends on 0214
# only, so either can land first, and a merge migration joins the two once
# both have.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0214_chatturn"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatturn",
            name="shadow_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not scored"),
                    ("scored", "Scored"),
                    ("failed", "Failed"),
                    ("timeout", "Timed out"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="shadow_scorer",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="shadow_winner_answers",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="shadow_winner_verdict",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="shadow_winner_asks_again",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="shadow_second_answers",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="shadow_second_verdict",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="shadow_second_asks_again",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
