# Generated by Django 5.2.9 on 2026-09-27 12:00
#
# The live Jev check on our own chat reply, on each chat turn row: whether
# the primary pass held the outside models back for it, its outcome, Jev's
# four answers, the scorer string, how long it took and the judged model's
# label. Numbers and labels only, never text. Also the external_start value
# for outside models started because the check did not pass.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0215_chatroutingpolicy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatturn",
            name="external_start",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No outside model asked"),
                    ("immediate", "Asked with ours"),
                    ("after_delay", "Started after the delay"),
                    ("early", "Started early: ours all failed"),
                    (
                        "after_check",
                        "Started early: the check on ours did not pass",
                    ),
                    ("skipped", "Skipped: ours answered first"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="gate_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="gate_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not checked"),
                    ("pass", "Passed"),
                    ("fail", "Failed"),
                    ("error", "Error"),
                    ("timeout", "Timed out"),
                    ("skipped", "Nothing judged"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="gate_answers",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="gate_verdict",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="gate_asks_again",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="gate_promises",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="gate_scorer",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="gate_ms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="gate_model",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
