# Generated by Django 5.2.9 on 2026-09-27 12:00
#
# After a failed reply check, whether the judged reply was demoted below the
# outside models' answers, and whether it was still delivered. Two booleans
# on each chat turn row, never text.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0217_chatturn_reply_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatturn",
            name="gate_demoted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="gate_demoted_delivered",
            field=models.BooleanField(default=False),
        ),
    ]
