# Generated by Django 5.2.9 on 2026-09-27 18:00
#
# The reply check's tiers: a borderline outcome, Jev's "crucial moment"
# answer, the ranking that runs after a borderline check, and why a
# side-by-side was offered. Numbers and labels on each chat turn row, never
# text. Also joins the reply-check and budget branches of the graph.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0218_chatturn_gate_demoted"),
        ("fighthealthinsurance", "0220_merge_chat_policy_and_spend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatturn",
            name="gate_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not checked"),
                    ("pass", "Passed"),
                    ("borderline", "Borderline"),
                    ("fail", "Failed"),
                    ("error", "Error"),
                    ("timeout", "Timed out"),
                    ("skipped", "Nothing judged"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="alternate_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No side-by-side"),
                    ("tied", "Closely tied scores"),
                    ("crucial", "Crucial moment (Jev)"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="gate_crucial",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="rank_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not ranked"),
                    ("picked", "Jev picked"),
                    ("error", "Error"),
                    ("timeout", "Timed out"),
                    ("skipped", "Not sent"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="rank_ms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="rank_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatturn",
            name="rank_changed",
            field=models.BooleanField(default=False),
        ),
    ]
