# Generated by Django 5.2.9 on 2026-10-02 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0222_merge_jev_tiers_and_main"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="proposedappeal",
            name="prompt_version",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name="LetterPromptMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("original", "Original prompt for every letter"),
                            ("new", "New prompt for every letter"),
                            (
                                "split",
                                "Half and half: each draft is written with one at random",
                            ),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "changed_by_username",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
