# Generated by Django 5.2.9 on 2026-10-03 01:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0223_proposedappeal_prompt_version_letterpromptmode"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServingIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                ("backend", models.CharField(db_index=True, max_length=300)),
                ("model_id", models.CharField(max_length=200)),
                ("endpoint", models.CharField(blank=True, default="", max_length=200)),
                ("weights", models.CharField(blank=True, default="", max_length=500)),
                ("parent", models.CharField(blank=True, default="", max_length=500)),
                ("max_model_len", models.IntegerField(blank=True, null=True)),
                ("owned_by", models.CharField(blank=True, default="", max_length=100)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                (
                    "last_seen",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen", "-id"],
            },
        ),
        migrations.AddField(
            model_name="proposedappeal",
            name="serving",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="fighthealthinsurance.servingidentity",
            ),
        ),
    ]
