# Generated by Django 5.2.9 on 2026-10-03 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0223_proposedappeal_prompt_version_letterpromptmode"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntakeResumePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.CharField(max_length=32)),
                (
                    "token_digest",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("wrong_email_attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "denial",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake_resume_point",
                        to="fighthealthinsurance.denial",
                    ),
                ),
            ],
        ),
    ]
