# Generated by Django 5.2.9 on 2026-10-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0224_intakeresumepoint"),
        ("fighthealthinsurance", "0224_servingidentity_proposedappeal_serving"),
    ]

    operations = []
