# Generated by Django 5.2.9 on 2026-10-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0225_merge_servingidentity_intakeresumepoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantHandoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lookup", models.CharField(max_length=64, unique=True)),
                ("sealed", models.BinaryField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
