# Generated by Django 5.2.9 on 2026-10-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0226_assistanthandoff"),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="channel",
            field=models.CharField(
                choices=[("site", "Site"), ("assistant", "AI assistant")],
                db_default="site",
                default="site",
                max_length=16,
            ),
        ),
    ]
