# Generated by Django 5.2.9 on 2026-10-04 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0226_assistanthandoff"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("terms_version", models.DateField()),
                ("privacy_version", models.DateField()),
                ("boxes", models.JSONField()),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("site", "site"), ("assistant", "assistant")],
                        default="site",
                        max_length=16,
                    ),
                ),
                ("on_behalf", models.BooleanField(default=False)),
                (
                    "finish_in",
                    models.CharField(
                        choices=[("site", "site"), ("chat", "chat")],
                        default="site",
                        max_length=8,
                    ),
                ),
                (
                    "assistant_client",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "denial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_records",
                        to="fighthealthinsurance.denial",
                    ),
                ),
            ],
        ),
    ]
