# Generated by Django 5.2.9 on 2026-10-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0226_assistanthandoff"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpendReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("name", models.CharField(max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="denial",
            name="channel",
            field=models.CharField(
                choices=[("site", "Site"), ("assistant", "AI assistant")],
                db_default="site",
                default="site",
                max_length=16,
            ),
        ),
    ]
