# Generated by Django 5.2.9 on 2026-10-04 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0227_consentrecord"),
        ("fighthealthinsurance", "0227_denial_channel_and_spend_reservation"),
    ]

    operations = []
