# Generated by Django 5.2.9 on 2026-10-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0230_assistant_terms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intakejourneyevent",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("claimed", "Claimed"),
                    ("skipped_completed", "Skipped: form completed"),
                    ("sent", "Sent"),
                    ("smtp_failed", "SMTP failed"),
                    ("not_built", "Not sent: the email could not be built"),
                ],
                default="",
                max_length=24,
            ),
        ),
    ]
