# Generated by Django 5.2.9 on 2026-10-05 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0232_followup_subjects_plain"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LetterReviewPacket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("rule_version", models.CharField(max_length=100)),
                ("rule_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LetterReviewItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("slug", models.CharField(max_length=32)),
                ("prompt", models.TextField()),
                ("letter", models.TextField()),
                ("position", models.PositiveIntegerField()),
                (
                    "packet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="fighthealthinsurance.letterreviewpacket",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="LetterReviewReader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("handle", models.CharField(max_length=64)),
                (
                    "packet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readers",
                        to="fighthealthinsurance.letterreviewpacket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LetterReviewLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("fabricates", "Fabricates"),
                            ("flag", "Flag"),
                            ("clean", "Clean"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, default="", max_length=2000)),
                ("labeled_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="fighthealthinsurance.letterreviewitem",
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="fighthealthinsurance.letterreviewreader",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="letterreviewitem",
            name="readers",
            field=models.ManyToManyField(
                related_name="items", to="fighthealthinsurance.letterreviewreader"
            ),
        ),
        migrations.AddConstraint(
            model_name="letterreviewreader",
            constraint=models.UniqueConstraint(
                fields=("packet", "handle"), name="letter_review_reader_handle"
            ),
        ),
        migrations.AddConstraint(
            model_name="letterreviewreader",
            constraint=models.UniqueConstraint(
                fields=("packet", "user"), name="letter_review_reader_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="letterreviewlabel",
            constraint=models.UniqueConstraint(
                fields=("item", "reader"), name="letter_review_label_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="letterreviewitem",
            constraint=models.UniqueConstraint(
                fields=("packet", "key"), name="letter_review_item_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="letterreviewitem",
            constraint=models.UniqueConstraint(
                fields=("packet", "position"), name="letter_review_item_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="letterreviewitem",
            constraint=models.UniqueConstraint(
                fields=("packet", "slug"), name="letter_review_item_slug"
            ),
        ),
    ]
