# Generated by Django 5.2.9 on 2026-10-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fighthealthinsurance", "0234_assistantdraft_spend_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letterpromptmode",
            name="mode",
            field=models.CharField(
                choices=[
                    ("original", "Original prompt (v1) for every letter"),
                    ("new", "New prompt (v2) for every letter"),
                    (
                        "split",
                        "Half and half: each draft is written with v1 or v2 at random",
                    ),
                    ("sectioned", "Sectioned prompt (v3) for every letter"),
                    (
                        "thirds",
                        "Thirds: each draft is written with v1, v2 or v3 at random",
                    ),
                ],
                max_length=16,
            ),
        ),
    ]
