# Generated by Django 5.2.18 on 2026-10-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0237_letterreviewlabel_argues_against_reason_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMUsageDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calls", models.BigIntegerField(default=0)),
                ("usage_missing_calls", models.BigIntegerField(default=0)),
                ("prompt_tokens", models.BigIntegerField(default=0)),
                ("completion_tokens", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day", models.DateField()),
                ("surface", models.CharField(max_length=16)),
                ("task", models.CharField(max_length=24)),
                ("model", models.CharField(max_length=80)),
                ("tier", models.CharField(max_length=8)),
                ("network_class", models.CharField(max_length=16)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "day",
                            "surface",
                            "task",
                            "model",
                            "tier",
                            "network_class",
                        ),
                        name="llm_usage_daily_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LLMUsageNetworkDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calls", models.BigIntegerField(default=0)),
                ("usage_missing_calls", models.BigIntegerField(default=0)),
                ("prompt_tokens", models.BigIntegerField(default=0)),
                ("completion_tokens", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day", models.DateField()),
                ("surface", models.CharField(max_length=16)),
                ("network_class", models.CharField(max_length=16)),
                ("asn_name", models.CharField(blank=True, default="", max_length=80)),
                ("country", models.CharField(blank=True, default="", max_length=2)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "day",
                            "surface",
                            "network_class",
                            "asn_name",
                            "country",
                        ),
                        name="llm_usage_network_daily_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LLMUsageNetworkWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calls", models.BigIntegerField(default=0)),
                ("usage_missing_calls", models.BigIntegerField(default=0)),
                ("prompt_tokens", models.BigIntegerField(default=0)),
                ("completion_tokens", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("week_start", models.DateField()),
                ("key", models.CharField(max_length=64)),
                ("surface", models.CharField(max_length=16)),
                ("network_class", models.CharField(max_length=16)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("week_start", "key", "surface", "network_class"),
                        name="llm_usage_network_week_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LLMUsageNetworkWeekSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                ("surface", models.CharField(max_length=16)),
                ("network_class", models.CharField(max_length=16)),
                ("networks", models.PositiveIntegerField(default=0)),
                ("calls", models.BigIntegerField(default=0)),
                ("tokens", models.BigIntegerField(default=0)),
                ("top1_calls", models.BigIntegerField(default=0)),
                ("top10_calls", models.BigIntegerField(default=0)),
                ("top1_tokens", models.BigIntegerField(default=0)),
                ("top10_tokens", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("week_start", "surface", "network_class"),
                        name="llm_usage_network_week_summary_unique",
                    )
                ],
            },
        ),
    ]
