# Generated by Django 5.2.18 on 2026-10-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fighthealthinsurance",
            "0237_letterreviewlabel_argues_against_reason_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="denial",
            name="appeal_deadline_check",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.CreateModel(
            name="PubMedArticleJudgment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pmid", models.CharField(max_length=32)),
                ("treatment_key", models.CharField(max_length=16)),
                ("on_topic", models.FloatField()),
                ("supports", models.FloatField()),
                ("undermines", models.FloatField()),
                ("scorer", models.CharField(max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pmid", "treatment_key", "scorer"),
                        name="pubmed_judgment_uniq",
                    )
                ],
            },
        ),
    ]
