import asyncio
import datetime
from typing import Any, Callable, Coroutine, Dict, List, Optional, cast

from django.utils import timezone
from loguru import logger

from fighthealthinsurance.cms_coverage_api import get_cms_coverage_citations
from fighthealthinsurance.ecri_guidelines_helper import ECRIGuidelinesHelper
from fighthealthinsurance.extralink_context_helper import (
    ExtraLinkContextHelper,
)
from fighthealthinsurance.microsites import get_microsite
from fighthealthinsurance.ml.ml_router import ml_router
from fighthealthinsurance.models import (
    CMSCoverageCache,
    Denial,
    GenericContextGeneration,
)
from fighthealthinsurance.utils import best_within_timelimit

# Refresh CMS coverage cache entries that are older than this. NCD/LCD
# documents change rarely, so a long TTL is fine; we just don't want
# entries to live forever in case the public URLs or titles change.
_CMS_CACHE_TTL = datetime.timedelta(days=30)

# Refresh cached generic (procedure/diagnosis-only) ML citations older than
# this. Same reasoning as the CMS TTL: the underlying literature moves slowly,
# but cached blobs shouldn't be immortal — model/prompt improvements and link
# rot both argue for periodic regeneration. Rows with updated_at=None (from
# before the TTL field existed) are treated as stale.
_GENERIC_CACHE_TTL = datetime.timedelta(days=30)


def _citations_worth_caching(citations: List[str]) -> bool:
    """Gate the shared generic-citation cache on a "reasonable" ML result.

    A junk generation (empty list, blank strings, or one-liners like "N/A" /
    "no citations found") must not get pinned in the cache, where it would be
    served to every future patient with the same procedure/diagnosis until the
    TTL expires. Requirements: a non-empty list, every entry a non-blank
    string, and at least one entry long enough (>= 20 chars) to plausibly be a
    real citation. This gates only the cache write — the caller still receives
    whatever was generated.
    """
    if not citations:
        return False
    if not all(isinstance(c, str) and c.strip() for c in citations):
        return False
    return any(len(c.strip()) >= 20 for c in citations)


async def _denial_is_medicare_plan(denial: Optional[Denial]) -> bool:
    """Return True if the denial's plan_source indicates a Medicare plan.

    Medicare and Medicare Advantage denials get stronger CMS-binding
    framing in the citations we return.
    """
    if denial is None or denial.pk is None:
        return False
    try:
        return await denial.plan_source.filter(
            name__in=["Medicare Advantage", "Medicare Regular"]
        ).aexists()
    except Exception as e:
        logger.debug(f"Could not determine Medicare plan source: {e}")
        return False


class MLCitationsHelper:
    """Helper class for generating citations using ML models"""

    @staticmethod
    def make_score_fn(factor: Callable[[Any], float] = lambda _: 1.0):
        """
        Create a scoring function for citation results.

        Args:
            factor: A callable that takes an awaitable and returns a float multiplier

        Returns:
            A scoring function for use with best_within_timelimit
        """

        def score_fn(result: Optional[List[str]], awaitable: Any) -> float:
            multiplier = factor(awaitable)
            # Score the result based on a mixture of source and length
            if not result:
                return -1.0
            return float(len(result)) * multiplier

        return score_fn

    @classmethod
    async def generate_specific_citations(
        cls,
        denial: Denial,
        timeout: int = 60,
    ) -> List[str]:
        """
        Generates patient-specific citations for an insurance denial using ML models.

        Uses detailed patient context—including denial text, plan context, and health history—along with procedure and diagnosis to retrieve citations from ML backends. Returns an empty list if all patient-specific context fields are missing or if no suitable backends are available.

        Args:
            denial: The insurance denial object containing relevant context.
            timeout: Maximum time in seconds to wait for citation generation.

        Returns:
            A list of citation strings generated by ML models.
        """
        # Normalize inputs - trim whitespace and convert to lowercase
        procedure = denial.procedure.strip().lower() if denial.procedure else ""
        diagnosis = denial.diagnosis.strip().lower() if denial.diagnosis else ""
        denial_text = denial.denial_text
        plan_context = denial.plan_context
        patient_context = denial.health_history

        if (
            (not denial_text or denial_text == "")
            and (not plan_context or plan_context == "")
            and (not patient_context or patient_context == "")
        ):
            logger.debug(
                f"Specific citations for {denial}: skipping, no patient context"
            )
            return []
        logger.debug(f"Generating specific citations for {denial}")
        result: List[str] = []
        try:
            # Pass the denial's own external-model consent through: the full
            # citation backends are external (Perplexity), and this call sends
            # denial_text / health_history / plan_context to them, so a denial
            # whose user declined external models (use_external=False) must get
            # no backends here (the router returns [] and we bail below). For
            # consenting denials this keeps the path reachable, which is why
            # the router isn't left at its internal-only default.
            full_citation_backends = ml_router.full_find_citation_backends(
                use_external=denial.use_external
            )

            # Only proceed if we have backends to use
            if not full_citation_backends:
                logger.debug("No citation backends available for specific citations")
                return []

            # Create tasks for full backends
            full_awaitables = []
            for backend in full_citation_backends:
                full_awaitables.append(
                    backend.get_citations(
                        denial_text=denial_text,
                        procedure=procedure,
                        diagnosis=diagnosis,
                        patient_context=patient_context,
                        plan_context=plan_context,
                    )
                )

            # Get the best result within the timeout
            try:
                result = (
                    await best_within_timelimit(
                        full_awaitables,
                        score_fn=cls.make_score_fn(),
                        timeout=timeout,
                    )
                    or []
                )
                logger.debug(
                    f"Got best citations within time limit: {len(result)} results"
                )
                return result
            except Exception:
                logger.opt(exception=True).debug(
                    "Failed to get best citations within timelimit"
                )
                return []
        except Exception as e:
            logger.opt(exception=True).warning(
                f"Failed to generate specific citations: {e}"
            )
            return []

    @classmethod
    async def _get_supplemental_citations(
        cls,
        denial: Optional[Denial],
        procedure: str,
        diagnosis: str,
    ) -> List[str]:
        """Collect citations from non-ML sources for a procedure/diagnosis.

        Returns the concatenation of (in order):
        - microsite ``evidence_snippets`` (when the denial has a microsite_slug)
        - extralink citations for that microsite (top 3)
        - ECRI Guidelines Trust citations matched on procedure/diagnosis (top 3)
        """
        extras: List[str] = []
        if denial and denial.microsite_slug:
            try:
                microsite = get_microsite(denial.microsite_slug)
                if microsite and microsite.evidence_snippets:
                    extras.extend(microsite.evidence_snippets)
                extralink_citations = (
                    await ExtraLinkContextHelper.get_extralink_citations(
                        denial.microsite_slug,
                        max_citations=3,
                    )
                )
                if extralink_citations:
                    extras.extend(extralink_citations)
            except Exception as e:
                logger.opt(exception=True).warning(
                    f"Failed to load microsite evidence snippets/extralinks: {e}"
                )

        try:
            ecri_citations = await ECRIGuidelinesHelper.get_citations(
                procedure=procedure,
                diagnosis=diagnosis,
                max_citations=3,
            )
            if ecri_citations:
                extras.extend(ecri_citations)
        except Exception as e:
            logger.opt(exception=True).warning(
                f"Failed to load ECRI guideline citations: {e}"
            )
        return extras

    @classmethod
    async def generate_generic_citations(
        cls,
        denial: Optional[Denial] = None,
        procedure_opt: Optional[str] = None,
        diagnosis_opt: Optional[str] = None,
        timeout: int = 60,
    ) -> List[str]:
        """
        Generate generic citations using ML models based only on procedure and diagnosis.
        These are cached for reuse across multiple patients with the same procedure/diagnosis.

        If the denial has a microsite_slug, also includes the microsite's evidence_snippets.

        Args:
            denial: the denial
            timeout: Maximum time to wait for citation generation

        Returns:
            List of citation strings
        """
        # Normalize inputs - trim whitespace and convert to lowercase

        if denial:
            procedure = denial.procedure.strip().lower() if denial.procedure else ""
            diagnosis = denial.diagnosis.strip().lower() if denial.diagnosis else ""
        else:
            procedure = procedure_opt.strip().lower() if procedure_opt else ""
            diagnosis = diagnosis_opt.strip().lower() if diagnosis_opt else ""

        # Skip if we don't have enough information
        if not procedure and not diagnosis:
            logger.debug(f"Missing procedure or diagnosis for generic citations")
            return []

        # Check for existing cached citations first. Reads target the current
        # cache version only — parked/deprecated rows (version=-pk from the
        # dedupe migration) and rows from older cache generations are ignored.
        # .afirst() rather than .aget() so a pathological duplicate can never
        # raise MultipleObjectsReturned here.
        result: List[str] = []
        stale_context: Optional[List[str]] = None
        try:
            cached = await GenericContextGeneration.objects.filter(
                procedure=procedure,
                diagnosis=diagnosis,
                version=GenericContextGeneration.CURRENT_VERSION,
            ).afirst()

            if cached is not None:
                fresh = (
                    cached.updated_at is not None
                    and (timezone.now() - cached.updated_at) < _GENERIC_CACHE_TTL
                )
                if fresh:
                    logger.debug(
                        f"Found cached generic citations for {procedure}/{diagnosis} -- {cached.generated_context}"
                    )
                    # Create a new list to avoid modifying cached data
                    result = list(cached.generated_context)
                    extras = await cls._get_supplemental_citations(
                        denial=denial, procedure=procedure, diagnosis=diagnosis
                    )
                    if extras:
                        logger.debug(
                            f"Adding {len(extras)} supplemental citations to cached result"
                        )
                        result.extend(extras)
                    return result
                # Past the TTL (or predates it): regenerate, but keep the old
                # content as a fallback in case regeneration comes back empty.
                stale_context = list(cached.generated_context)
                logger.debug(
                    f"Cached generic citations for {procedure}/{diagnosis} are "
                    "stale; regenerating"
                )
            else:
                logger.debug(
                    f"No cached generic citations found for {procedure}/{diagnosis}"
                )
        except Exception as e:
            logger.opt(exception=True).warning(
                f"Error fetching cached generic citations: {e}"
            )

        # If no cached citations exist, generate them
        try:
            # Get the appropriate citation backends - only partial backends for generic citations
            partial_citation_backends = ml_router.partial_find_citation_backends()

            # Only proceed if we have backends to use
            if not partial_citation_backends:
                logger.debug("No citation backends available for generic citations")
                # Even without backends, serve the stale cache (if any) plus
                # supplemental evidence rather than nothing.
                extras = await cls._get_supplemental_citations(
                    denial=denial, procedure=procedure, diagnosis=diagnosis
                )
                return (stale_context or []) + extras

            # Create tasks for partial backends
            partial_awaitables = []
            for backend in partial_citation_backends:
                partial_awaitables.append(
                    backend.get_citations(
                        denial_text=None,
                        procedure=procedure,
                        diagnosis=diagnosis,
                        patient_context=None,
                        plan_context=None,
                    )
                )

            # Get the best result within the timeout
            try:
                logger.debug(
                    f"Generating best generic citations for {procedure}/{diagnosis} w/ {partial_awaitables}"
                )
                result = []
                try:
                    result = (
                        await best_within_timelimit(
                            partial_awaitables,
                            score_fn=cls.make_score_fn(),
                            timeout=timeout,
                        )
                        or []
                    )
                except Exception as e:
                    logger.opt(exception=True).debug(
                        f"Error in citation generation: {e}"
                    )
                    result = []

                # Snapshot the ML-only citations *before* appending
                # supplemental ones. We cache only the ML-only list so that a
                # later cache hit (which re-fetches and appends supplemental
                # citations itself) does not end up with the supplemental
                # citations duplicated.
                #
                # The partial backends receive ONLY procedure/diagnosis (no
                # denial_text / patient_context / plan_context — see the
                # get_citations call above), so nothing patient-specific can
                # land in this shared cache.
                ml_only = list(result)

                if stale_context and not _citations_worth_caching(ml_only):
                    # Regeneration produced nothing worth keeping (empty OR
                    # junk that the cache guard would reject); serve the
                    # known-good stale cached citations instead. The row's
                    # timestamp is left untouched so the next request retries
                    # generation. Using the same guard as the cache write
                    # keeps one definition of "bad result" — otherwise junk
                    # would be served over good stale content forever.
                    logger.debug(
                        f"Regeneration for {procedure}/{diagnosis} not worth "
                        "keeping; serving stale cached citations"
                    )
                    result = list(stale_context)

                extras = await cls._get_supplemental_citations(
                    denial=denial, procedure=procedure, diagnosis=diagnosis
                )
                if extras:
                    logger.debug(
                        f"Adding {len(extras)} supplemental citations to generated result"
                    )
                    result.extend(extras)

                # Cache the ML-only citations, but only when the generation
                # looks reasonable — junk must not get pinned for every future
                # patient with this procedure/diagnosis.
                if _citations_worth_caching(ml_only):
                    try:
                        # Upsert against the (procedure, diagnosis, version)
                        # UniqueConstraint (generic_ctx_proc_diag_ver_uniq),
                        # so concurrent cache misses collapse to a single row.
                        # Parked/deprecated rows live at other versions and
                        # never collide with this lookup.
                        await GenericContextGeneration.objects.aupdate_or_create(
                            procedure=procedure,
                            diagnosis=diagnosis,
                            version=GenericContextGeneration.CURRENT_VERSION,
                            defaults={
                                "generated_context": ml_only,
                                # Explicit timestamp: update_or_create defaults
                                # don't trigger auto_now, and the TTL reads
                                # key off this field.
                                "updated_at": timezone.now(),
                            },
                        )
                        logger.debug(
                            f"Stored cached generic citations for {procedure}/{diagnosis} -- {ml_only}"
                        )
                    except Exception as e:
                        logger.opt(exception=True).warning(
                            f"Error caching generic citations: {e}"
                        )

                return result
            except Exception:
                logger.opt(exception=True).debug(
                    "Failed to get best citations within timelimit"
                )
                return []
        except Exception as e:
            logger.opt(exception=True).warning(
                f"Failed to generate generic citations: {e}"
            )
            return []

    @classmethod
    async def generate_cms_coverage_citations(
        cls,
        denial: Optional[Denial] = None,
        procedure_opt: Optional[str] = None,
        diagnosis_opt: Optional[str] = None,
        max_results: int = 3,
    ) -> List[str]:
        """Pull CMS Medicare Coverage Database citations for procedure/diagnosis.

        Results are cached in CMSCoverageCache keyed by procedure+diagnosis
        with a 30-day TTL. Two parallel cached lists are kept — generic and
        Medicare-binding — and the right one is returned based on the
        denial's plan_source.

        Returns an empty list if procedure and diagnosis are both missing
        or the CMS API is unreachable.
        """
        if denial is not None:
            procedure = denial.procedure.strip().lower() if denial.procedure else ""
            diagnosis = denial.diagnosis.strip().lower() if denial.diagnosis else ""
        else:
            procedure = procedure_opt.strip().lower() if procedure_opt else ""
            diagnosis = diagnosis_opt.strip().lower() if diagnosis_opt else ""

        if not procedure and not diagnosis:
            return []

        medicare_plan = await _denial_is_medicare_plan(denial)
        cache_field = "medicare_citations" if medicare_plan else "generic_citations"
        timestamp_field = (
            "medicare_updated_at" if medicare_plan else "generic_updated_at"
        )

        cache_entry: Optional[CMSCoverageCache] = None
        try:
            cache_entry = await CMSCoverageCache.objects.filter(
                procedure=procedure, diagnosis=diagnosis
            ).afirst()
        except Exception as e:
            logger.debug(f"Could not read CMSCoverageCache: {e}")

        if cache_entry is not None:
            cached = getattr(cache_entry, cache_field) or []
            variant_updated_at = getattr(cache_entry, timestamp_field, None)
            fresh = (
                variant_updated_at is not None
                and (timezone.now() - variant_updated_at) < _CMS_CACHE_TTL
            )
            if cached and fresh:
                logger.debug(
                    f"Using cached CMS citations for {procedure}/{diagnosis} "
                    f"(medicare_plan={medicare_plan})"
                )
                return list(cached)[:max_results]

        try:
            citations = await get_cms_coverage_citations(
                procedure=procedure or None,
                diagnosis=diagnosis or None,
                medicare_plan=medicare_plan,
                max_results=max_results,
            )
        except Exception as e:
            logger.opt(exception=True).debug(f"CMS coverage citation fetch failed: {e}")
            citations = []

        if citations:
            # `aupdate_or_create` is atomic against the (procedure, diagnosis)
            # unique constraint, which closes the race where two concurrent
            # cache misses could otherwise create duplicate rows. We write
            # the variant timestamp explicitly because `aupdate` bypasses
            # `auto_now`.
            now = timezone.now()
            try:
                await CMSCoverageCache.objects.aupdate_or_create(
                    procedure=procedure,
                    diagnosis=diagnosis,
                    defaults={cache_field: citations, timestamp_field: now},
                )
            except Exception as e:
                logger.opt(exception=True).debug(
                    f"Failed to persist CMS coverage cache: {e}"
                )

        return citations

    @classmethod
    async def _generate_citations_for_denial(
        cls,
        denial: Denial,
        timeout: int = 45,
    ) -> List[str]:
        """
        Chooses the best citations for a denial object based on the available context.

        Args:
            denial: Denial

        Returns:
            List of citation strings
        """
        if denial.ml_citation_context and len(denial.ml_citation_context) > 0:
            return denial.ml_citation_context  # type: ignore

        # Run CMS Medicare Coverage Database lookup alongside the ML
        # backends. It hits a public API + DB cache, so it won't compete for
        # ML capacity, and we want its output to augment whatever the
        # backends produce rather than replace it.
        cms_task = asyncio.create_task(
            cls.generate_cms_coverage_citations(denial=denial)
        )

        try:
            model_timeout = timeout - 10

            no_context_awaitable = cls.generate_generic_citations(
                denial=denial,
                timeout=model_timeout,
            )

            # If we have context look for it otherwise short circuit:
            if (not denial.denial_text or len(denial.denial_text) < 5) and (
                not denial.health_history or len(denial.health_history) < 5
            ):
                ml_result = await no_context_awaitable
            else:
                context_awaitable = cls.generate_specific_citations(
                    denial=denial,
                    timeout=model_timeout,
                )

                def is_full_backend(awaitable: Coroutine) -> int:
                    if awaitable == context_awaitable:
                        return 2
                    return 1

                ml_result = (
                    await best_within_timelimit(
                        [no_context_awaitable, context_awaitable],
                        score_fn=cls.make_score_fn(is_full_backend),
                        timeout=timeout,
                    )
                    or []
                )
        except Exception as e:
            logger.opt(exception=True).warning(f"Failed to generate citations: {e}")
            ml_result = []

        try:
            cms_citations = await cms_task
        except Exception as e:
            logger.opt(exception=True).debug(f"CMS coverage task failed: {e}")
            cms_citations = []

        if cms_citations:
            # Append CMS citations after ML citations, dedup by exact string.
            seen = {c for c in ml_result if isinstance(c, str)}
            for c in cms_citations:
                if c not in seen:
                    ml_result.append(c)
                    seen.add(c)
        return ml_result

    @classmethod
    async def generate_citations_for_denial(
        cls, denial: Denial, speculative: bool
    ) -> List[str]:
        """
        Generate citations for a denial object if they don't already exist.
        Pulls the speculative/candidate value if nothing changed since computed.

        Args:
            denial: The Denial object to generate citations for
            speculative: Whether to store on the speculative field

        Returns:
            List of generated citation strings
        """
        # Check if we already have citations for this denial
        logger.debug(f"Generating citations for {denial}")
        citations: List[str] = []
        if (
            denial.ml_citation_context is not None
            and len(denial.ml_citation_context) > 0
        ):
            logger.debug(f"Citations already exist for denial {denial.denial_id}")
            return cast(List[str], denial.ml_citation_context)

        elif (
            denial.candidate_ml_citation_context
            and (
                not denial.procedure or (denial.candidate_procedure == denial.procedure)
            )
            and (
                not denial.diagnosis or (denial.candidate_diagnosis == denial.diagnosis)
            )
            and len(denial.candidate_ml_citation_context) > 0
        ):
            logger.debug(f"Using candidate citations for denial {denial.denial_id}")
            citations = cast(List[str], denial.candidate_ml_citation_context)

        else:
            # Setup timeout based on whether this is speculative or not
            timeout = 75 if speculative else 30

            try:
                if (
                    denial.denial_text
                    or denial.health_history
                    or denial.procedure
                    or denial.diagnosis
                ):
                    logger.debug(f"Generating citations for denial {denial.denial_id}")

                    citations = await cls._generate_citations_for_denial(
                        denial=denial,
                        timeout=timeout,
                    )

                    if citations:
                        logger.debug(
                            f"Generated {len(citations)} citations for denial {denial.denial_id}"
                        )
                else:
                    logger.debug("Nothing to generate citations for")
                    return []
            except Exception as e:
                logger.opt(exception=True).warning(
                    f"Error generating citations for denial {denial.denial_id}: {e}"
                )

        # Store citations in the denial object directly using aupdate
        if citations:
            # Atomically update the appropriate field
            if not speculative:
                await Denial.objects.filter(denial_id=denial.denial_id).aupdate(
                    ml_citation_context=citations
                )
            else:
                await Denial.objects.filter(denial_id=denial.denial_id).aupdate(
                    candidate_ml_citation_context=citations
                )
            logger.debug(
                f"Stored {len(citations)} citations for denial {denial.denial_id}"
            )

        return citations
