apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: fhi-pg
  namespace: totallylegitco
spec:
  instances: 3
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 30Gi
      storageClassName: encrypted-local-path
      volumeMode: Filesystem
  monitoring:
    enablePodMonitor: false
  superuserSecret:
    name: superuser-pg-secret
  affinity:
    enablePodAntiAffinity: true
  backup:
    barmanObjectStore:
      destinationPath: s3://fhi-pg-backup/
      endpointURL: http://s3.us-west-004.backblazeb2.com:9000
      s3Credentials:
        accessKeyId:
          name: pg-backup
          key: PG_ACCESS_KEY_ID
        secretAccessKey:
          name: pg-backup
          key: PG_ACCESS_SECRET_KEY
#  bootstrap:
#    initdb:
#      database: app
#      owner: app
#      secret:
#        name: fhi-pg-secret
  bootstrap:
    recovery:
      source: clusterBackup

  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: s3://fhi-pg-backup/
        endpointURL: http://s3.us-west-004.backblazeb2.com:9000
        s3Credentials:
          accessKeyId:
            name: pg-backup
            key: PG_ACCESS_KEY_ID
          secretAccessKey:
            name: pg-backup
            key: PG_ACCESS_SECRET_KEY
        wal:
          maxParallel: 20
---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: fhi-pg-backup
spec:
  cluster:
    name: fhi-pg
