import asyncio
import math
import re
import time
from dataclasses import replace
from typing import Any, Awaitable, Callable, Dict, List, Optional, Tuple, cast

from django.utils import timezone

# channels' database_sync_to_async (NOT asgiref's sync_to_async): chat runs
# outside the HTTP request cycle, so only its close_old_connections wrapping
# ever closes the DB connections these calls open.
from channels.db import database_sync_to_async
from loguru import logger

from fhi_users.models import User
from fighthealthinsurance import settings
from fighthealthinsurance.chat.chat_persistence import (
    apersist_chat_turn,
    apersist_microsite_context,
    is_internal_history_message,
    visible_history,
)
from fighthealthinsurance.chat.context_manager import (
    MISSING_CONTEXT_PREFIX,
    background_generate_summary,
    bound_summary_context,
    make_placeholder,
    prepare_history_for_llm,
    should_store_summary,
)
from fighthealthinsurance.chat.llm_client import (
    alternate_is_presentable,
    build_llm_calls,
    build_llm_calls_for_variants,
    create_response_scorer,
    find_repeated_reply,
    scores_closely_tied,
    user_requested_repeat,
)
from fighthealthinsurance.chat.message_preprocessor import (
    MessageVariant,
    prepare_user_message_variants,
)
from fighthealthinsurance.chat.document_processor import process_uploaded_document
from fighthealthinsurance.chat.document_search import get_document_context_for_message
from fighthealthinsurance.chat.retry_handler import (
    retry_llm_with_fallback,
    should_retry_response,
)
from fighthealthinsurance.chat.safety_filters import (
    CRISIS_RESOURCES,
    DELETE_DATA_RESPONSE,
    detect_crisis_keywords,
    detect_delete_data_request,
    llm_requested_delete_handoff,
)
from fighthealthinsurance.chat.tools import (
    AppealTool,
    ClinicalTrialsTool,
    DocFetcherTool,
    FinancialAssistanceTool,
    MedicaidEligibilityTool,
    MedicaidInfoTool,
    PaRequirementLookupTool,
    PriorAuthTool,
    PubMedTool,
    RxNormLookupTool,
    USPSTFLookupTool,
)
from fighthealthinsurance.extralink_context_helper import ExtraLinkContextHelper
from fighthealthinsurance.rag_client import get_rag_context_for_denial
from fighthealthinsurance.ml.ml_metrics import (
    record_chat_alternate_offered,
    record_chat_repeat,
    record_chat_turn,
)
from fighthealthinsurance.ml.ml_models import (
    RemoteModelLike,
    _env_float,
    remove_repeated_blocks,
    remove_repeated_sentences,
)
from fighthealthinsurance.reliability_events import capture_reliability_event
from fighthealthinsurance.ml.ml_router import ml_router
from fighthealthinsurance.models import (
    Appeal,
    ChatType,
    OngoingChat,
    PolicyDocument,
    PriorAuthRequest,
)
from fighthealthinsurance.microsites import get_microsite
from fighthealthinsurance.prompt_templates import (
    DELETE_DATA_INSTRUCTION,
    get_intro_template,
)
from fighthealthinsurance.clinicaltrials_tools import ClinicalTrialsTools
from fighthealthinsurance.pubmed_tools import PubMedTools
from fighthealthinsurance.rxnorm_tools import RxNormTools
from fighthealthinsurance.utils import (
    best_two_within_timelimit,
    fire_and_forget_in_new_threadpool,
)
from fighthealthinsurance.ml.ml_policy_doc_helper import MLPolicyDocHelper

# Policy analysis detection: only match the structured message generated by
# UnderstandPolicyView.form_valid(). This avoids false positives from normal
# chat messages that mention "summary of benefits" or "what is covered".
_POLICY_ANALYSIS_REGEX: re.Pattern[str] = re.compile(
    r"I've uploaded my insurance .+\r?\nPlease analyze this document",
    re.IGNORECASE | re.DOTALL,
)


def _detect_policy_analysis_request(text: str) -> bool:
    """Check if the message is the structured policy analysis request from the form."""
    return bool(_POLICY_ANALYSIS_REGEX.search(text))


# A user message at/below this length right after an assistant question gets
# the terse-reply bridge note (see handle_chat_message): terse answers are
# where models historically looped by re-asking instead of using the answer.
TERSE_REPLY_MAX_CHARS = 60


def _clean_reply(text: str) -> str:
    """Strip the model's self-repetition from a reply before it is shown.

    Shared by the primary answer and the side-by-side alternate: the two are
    displayed next to each other, so cleaning them differently would make the
    comparison the feature exists for unfair.
    """
    stripped = text.strip()
    cleaned = remove_repeated_blocks(stripped) or stripped
    return remove_repeated_sentences(cleaned) or cleaned


class ChatInterface:
    def __init__(
        self,
        send_json_message_func: Callable[[Dict[str, Any]], Awaitable[None]],
        chat: OngoingChat,
        user: User,
        # External models participate by default (matches the client-side
        # default; the consent-form toggle sends an explicit opt-out).
        use_external_models: bool = True,
        server_session_key: Optional[str] = None,
        state_hint: Optional[str] = None,
        debug_llm: bool = False,
    ):
        def wrap_send_json_message_func(message: Dict[str, Any]) -> Awaitable[None]:
            """Wraps the send_json_message_func to ensure it's always awaited."""
            if "chat_id" not in message:
                message["chat_id"] = str(chat.id)
            return send_json_message_func(message)

        self.send_json_message_func = wrap_send_json_message_func
        self.pubmed_tools = PubMedTools()
        # Single RxNormTools shared across RxNormLookupTool and PubMedTool
        # so they reuse the same client / cache view per chat session.
        self.rxnorm_tools = RxNormTools()
        self.clinical_trials_tools = ClinicalTrialsTools()
        self.chat: OngoingChat = chat
        self.user: User = user
        self.use_external_models: bool = use_external_models
        # The DJANGO session key from the WebSocket scope. Distinct from
        # chat.session_key, which anonymous clients generate themselves
        # (localStorage random string): server-side flows like the policy
        # upload store their artifacts under the Django session, so lookups
        # must try this key first.
        self.server_session_key: Optional[str] = server_session_key
        # Best-effort US-state guess derived from the connection's IP (see
        # fhi_users.audit.guess_us_state). Transient by design: it flows into
        # the LLM context as an UNCONFIRMED hint each turn but is never
        # persisted with the chat, so anonymous users' location is not stored.
        self.state_hint: Optional[str] = state_hint
        # When True (gated upstream to settings.DEBUG or staff users), each
        # turn also sends a debug_llm_input frame showing exactly what was
        # sent to the backend model.
        self.debug_llm: bool = debug_llm
        self._doc_fetch_count: list[int] = [0]
        # Runner-up answer from the most recent top-level LLM fan-out,
        # offered to the client as a side-by-side alternate when presentable
        # AND closely tied with the winner (see scores_closely_tied).
        self._candidate_alternate: Optional[str] = None
        # Per-session strike counts for backends whose candidates were
        # hard-rejected as repeats (label -> count). Shared with the scorer,
        # which decays a striking backend's base score so a looping model
        # stops winning every fan-out this session. In-memory only.
        self._repeat_offenders: Dict[str, int] = {}

    @staticmethod
    def _append_to_history(chat, role: str, content: str):
        """Append a message to chat history with a timestamp."""
        if not chat.chat_history:
            chat.chat_history = []
        chat.chat_history.append(
            {
                "role": role,
                "content": content,
                "timestamp": timezone.now().isoformat(),
            }
        )

    @property
    def is_patient(self) -> bool:
        return self.chat.chat_type == ChatType.PATIENT

    @property
    def is_professional(self) -> bool:
        return self.chat.chat_type == ChatType.PROFESSIONAL

    @property
    def is_trial_professional(self) -> bool:
        return self.chat.chat_type == ChatType.TRIAL_PROFESSIONAL

    async def send_error_message(self, message: str):
        """Sends an error message to the client."""
        await self.send_json_message_func(
            {"error": message, "chat_id": str(self.chat.id)}
        )

    async def send_status_message(self, message: str):
        """Sends a status message to the client."""
        logger.debug(f"Chat {self.chat.id} status: {message}")
        await self.send_json_message_func(
            {"status": message, "chat_id": str(self.chat.id)}
        )

    async def _turn_heartbeat(self) -> None:
        """Emit a status frame every FHI_CHAT_HEARTBEAT_SECONDS while a turn
        is being generated.

        Long tool/LLM turns can go minutes without a frame on the socket;
        idle-reaping proxies kill those connections and the user sees a
        spinner that never resolves. Cancelled by the caller when the turn
        finishes; the client already renders ``status`` frames as its loading
        state, so this needs no frontend changes.
        """
        interval = _env_float("FHI_CHAT_HEARTBEAT_SECONDS", 20.0)
        try:
            while True:
                await asyncio.sleep(interval)
                try:
                    await self.send_status_message("Still working on your reply...")
                except Exception:
                    # One failed send must not end heartbeats for the rest of
                    # the turn (a transient send error is exactly the flaky
                    # long-turn case this loop exists for). If the socket is
                    # truly gone the main turn surfaces that on its own send.
                    logger.debug(f"Heartbeat send failed for chat {self.chat.id}")
        except asyncio.CancelledError:
            pass

    async def send_message_to_client(
        self, message: str, alternate_content: Optional[str] = None
    ):
        """Sends a message to the client, optionally with a side-by-side
        alternate answer (rendered behind a toggle client-side; only the
        primary message is persisted in chat history)."""
        payload: Dict[str, Any] = {
            "content": message,
            "chat_id": str(self.chat.id),
            "role": "assistant",
        }
        if alternate_content:
            payload["alternate_content"] = alternate_content
        await self.send_json_message_func(payload)

    async def _get_user_info(self) -> str:
        """Generates a descriptive string for the user (either professional or patient)."""
        try:
            return cast(str, await database_sync_to_async(self.chat.summarize_user)())
        except Exception as e:
            logger.warning(f"Could not generate detailed user info: {e}")
            return "a user"

    async def _denial_context_for_chat(self, chat: OngoingChat) -> Optional[str]:
        """Build a short denial-context string (procedure/diagnosis) for a chat.

        Used to give document/long-paste summarization a hint about what the
        linked appeal is about. Returns None when there's no linked denial.
        """
        appeal = (
            await Appeal.objects.select_related("for_denial").filter(chat=chat).afirst()
        )
        if not appeal or not appeal.for_denial:
            return None
        linked_denial = appeal.for_denial
        parts = []
        if linked_denial.procedure or linked_denial.candidate_procedure:
            parts.append(
                f"Procedure: {linked_denial.procedure or linked_denial.candidate_procedure}"
            )
        if linked_denial.diagnosis or linked_denial.candidate_diagnosis:
            parts.append(
                f"Diagnosis: {linked_denial.diagnosis or linked_denial.candidate_diagnosis}"
            )
        return "; ".join(parts) if parts else None

    async def _call_llm_with_actions(
        self,
        model_backends: List[RemoteModelLike],
        current_message_for_llm: str,
        previous_context_summary: Optional[str],
        history_for_llm: List[Dict[str, str]],
        depth: int = 0,
        is_logged_in: bool = True,
        is_professional: bool = True,
        fallback_backends: Optional[List[RemoteModelLike]] = None,
        full_history: Optional[List[Dict[str, str]]] = None,
        user_message_for_scoring: Optional[str] = None,
        message_variants: Optional[List[MessageVariant]] = None,
    ) -> Tuple[Optional[str], Optional[str]]:
        """
        Calls the LLM, handles PubMed query requests if present and returns the response.
        Also processes special tokens for creating or updating Appeals and PriorAuthRequests.

        Args:
            model_backends: List of model backends to try
            current_message_for_llm: The current message to send
            previous_context_summary: Summary of previous context
            history_for_llm: Truncated history (last 20 messages)
            depth: Recursion depth for tool handling
            is_logged_in: Whether user is logged in
            is_professional: Whether user is a professional
            fallback_backends: Backup models to try if primary fails
            full_history: Full untruncated history (optional) - will also try with this
                         if provided and model context allows it
            user_message_for_scoring: The raw user message used by repetition-penalty
                scoring. Distinct from current_message_for_llm, which may be wrapped
                with intro-template content or the delete-data instruction. Defaults
                to current_message_for_llm when not provided.
            message_variants: Optional list of LLM-ready message variants (primary
                first, lower-scored long/Unicode alternatives after). When provided,
                calls are fanned out per variant and each variant's score_delta is
                applied so the primary path wins unless it fails. When None (e.g.
                recursive tool calls), the single current_message_for_llm is used.
        """
        if depth > 3:
            return None, None
        chat = self.chat
        history = history_for_llm

        # Fall back to the model-facing string for scoring when no raw user
        # message was supplied (e.g. recursive tool calls that already carry
        # the wrapped message and don't have access to the original).
        scoring_message = (
            user_message_for_scoring
            if user_message_for_scoring is not None
            else current_message_for_llm
        )

        # Did the user explicitly ask for a repeat? Derived from the RAW
        # message (scoring_message) BEFORE prompt wrapping -- the wrapped
        # current_message_for_llm contains system-injected text that itself
        # says "repeat", so testing it there would always match. Forwarded to
        # the backends so their per-backend self-heal loop doesn't fight the
        # user's request (the scorers make the same check independently).
        allow_repeat = user_requested_repeat(scoring_message)

        # Build LLM calls using the extracted module. When message variants are
        # supplied (top-level user turn), fan out per variant and apply each
        # variant's score delta; only the primary_original variant's calls keep
        # the is-primary scoring bonus. Otherwise (recursive tool calls) fall
        # back to the single wrapped message, preserving existing behavior.
        call_labels: Dict[Awaitable, str] = {}
        if message_variants:
            calls, call_scores, primary_calls = build_llm_calls_for_variants(
                model_backends=model_backends,
                variants=message_variants,
                previous_context_summary=previous_context_summary,
                history=history,
                is_professional=is_professional,
                is_logged_in=is_logged_in,
                full_history=full_history,
                allow_repeated_reply=allow_repeat,
                call_labels=call_labels,
            )
        else:
            calls, call_scores = build_llm_calls(
                model_backends=model_backends,
                current_message=current_message_for_llm,
                previous_context_summary=previous_context_summary,
                history=history,
                is_professional=is_professional,
                is_logged_in=is_logged_in,
                full_history=full_history,
                allow_repeated_reply=allow_repeat,
                call_labels=call_labels,
            )
            primary_calls = calls

        # Create scoring function using the extracted module. rejection_stats
        # is shared with the scorer so we can tell "no usable response" apart
        # from "responses arrived but all repeated a recent reply" -- the
        # latter retries with an explicit anti-repeat instruction.
        # call_labels + self._repeat_offenders let the scorer demote backends
        # that produced hard-rejected repeats earlier in this session, and
        # score_log records per-candidate final scores for debug reporting.
        rejection_stats: Dict[str, int] = {}
        score_log: Dict[Awaitable, float] = {}
        score_fn = create_response_scorer(
            call_scores,
            primary_calls=primary_calls,
            chat_history=chat.chat_history,
            current_message=scoring_message,
            rejection_stats=rejection_stats,
            call_labels=call_labels,
            repeat_offenders=self._repeat_offenders,
            score_log=score_log,
        )

        llm_pass_started = time.monotonic()
        picked_model: Optional[str] = None
        picked_score: Optional[float] = None
        runner_up_model: Optional[str] = None
        runner_up_score: Optional[float] = None
        runner_up_text: Optional[str] = None
        try:
            # Explicit overtime window: with the defaults (2x timeout) the
            # primary pass could take 90s and the retry pass 105s -- past the
            # 150s turn budget, so the budget killed retries that would have
            # succeeded. 30+30 here plus 35+40 in retry_llm_with_fallback
            # keeps the whole ladder inside the budget.
            best_two = await best_two_within_timelimit(
                calls,
                score_fn,
                timeout=30.0,
                extended_timeout=30.0,
            )
            response_text, context_part = (
                best_two.best if best_two.best is not None else (None, None)
            )
            if best_two.best is not None:
                picked_score = best_two.best_score
                if best_two.best_task is not None:
                    picked_model = call_labels.get(best_two.best_task)
            if best_two.runner_up is not None:
                runner_up_text = best_two.runner_up[0]
                runner_up_score = best_two.runner_up_score
                if best_two.runner_up_task is not None:
                    runner_up_model = call_labels.get(best_two.runner_up_task)
        except Exception as e:
            logger.warning(f"Primary models all failed: {e}")
            response_text = None
            context_part = None

        response_text = response_text or ""

        # Record rejected repeats for EVERY turn that had them, not only turns
        # that also needed a retry. The common success case is "an internal
        # backend looped, its candidates were hard-rejected, another backend's
        # answer won" -- which needs no retry, and used to leave the counter
        # flat while the ladder was working hard. That made the metric read as
        # "loops never happen" exactly when a backend started looping.
        saw_repeats = bool(rejection_stats.get("repeated_rejected"))
        if saw_repeats:
            # Counted once per turn (the stat itself is per candidate).
            record_chat_repeat("rejected_candidates")
            logger.info(
                f"Chat {chat.id}: primary pass rejected "
                f"{rejection_stats['repeated_rejected']} repeated "
                f"candidate replies"
            )

        # If primary models failed, use retry handler with fallback
        retry_used = False
        retry_debug: Dict[str, Any] = {}
        if should_retry_response(response_text):
            retry_response, retry_context = await retry_llm_with_fallback(
                model_backends=model_backends,
                current_message=current_message_for_llm,
                previous_context_summary=previous_context_summary,
                history=history,
                is_professional=is_professional,
                is_logged_in=is_logged_in,
                fallback_backends=fallback_backends,
                timeout=35.0,
                status_callback=self.send_status_message,
                chat_history=chat.chat_history,
                user_message_for_scoring=scoring_message,
                anti_repeat=saw_repeats,
                allow_repeated_reply=allow_repeat,
                debug_info=retry_debug,
            )
            if retry_response and len(retry_response.strip()) > 5:
                response_text = retry_response
                context_part = retry_context
                retry_used = True
                picked_model = retry_debug.get("retry_picked_model") or picked_model
                picked_score = retry_debug.get("retry_picked_score", picked_score)
                # The retry winner replaced the primary answer; the primary
                # pass's runner-up no longer describes a comparable pair.
                runner_up_text = None
                runner_up_model = None
                runner_up_score = None

        logger.debug(f"Using best result {response_text:.20}...")

        if not response_text:
            logger.debug("Got empty response from LLM")
            return None, None

        # Capture a presentable runner-up as a side-by-side alternate answer
        # -- but only when the top two scores are CLOSELY TIED (see
        # scores_closely_tied): when the winner is clearly better, showing a
        # second answer is noise; when the race was close, the user is the
        # right tiebreaker. Only for the top-level user turn (depth 0);
        # recursive tool calls must not clobber it. Cleared again below if
        # tool processing changes the primary response (action flows don't
        # get a raw alternate).
        closely_tied = False
        if depth == 0:
            self._candidate_alternate = None
            closely_tied = (
                picked_score is not None
                and runner_up_score is not None
                and scores_closely_tied(picked_score, runner_up_score)
            )
            if runner_up_text and closely_tied:
                if alternate_is_presentable(
                    runner_up_text,
                    response_text,
                    chat_history=chat.chat_history,
                    current_message=scoring_message,
                ):
                    self._candidate_alternate = runner_up_text.strip()
            elif runner_up_text:
                logger.debug(
                    f"Chat {chat.id}: runner-up not closely tied "
                    f"({runner_up_score} vs {picked_score}); no alternate"
                )

        # One compact selection line per LLM pass at INFO: this is the
        # production-debuggable record of which backend won and why the
        # alternates/retries behaved as they did (the debug frame below
        # only reaches DEBUG deployments and staff).
        elapsed_ms = int((time.monotonic() - llm_pass_started) * 1000)
        logger.info(
            f"Chat {chat.id}: picked {picked_model or 'unknown'}"
            f" (score={picked_score}) runner_up={runner_up_model}"
            f" (score={runner_up_score}, tied={closely_tied})"
            f" candidates={len(calls)} rejected_repeats="
            f"{rejection_stats.get('repeated_rejected', 0)}"
            f" retry_used={retry_used} elapsed_ms={elapsed_ms} depth={depth}"
        )
        if depth == 0 and self.debug_llm:
            # -inf (hard-rejected candidates) is not valid JSON -- json.dumps
            # emits `-Infinity`, which browser JSON.parse refuses, killing
            # the whole frame client-side. Map non-finite scores to None and
            # mark the rejection explicitly instead.
            scored_candidates = [
                {
                    "model": call_labels.get(task, "unknown"),
                    "score": score if math.isfinite(score) else None,
                    "rejected": not math.isfinite(score),
                }
                for task, score in score_log.items()
            ]
            await self.send_json_message_func(
                {
                    "debug_llm_result": {
                        "picked_model": picked_model,
                        "picked_score": picked_score,
                        "runner_up_model": runner_up_model,
                        "runner_up_score": runner_up_score,
                        "closely_tied": closely_tied,
                        "alternate_offered": bool(self._candidate_alternate),
                        "candidate_count": len(calls),
                        "scored_candidates": scored_candidates,
                        "rejected_repeats": rejection_stats.get("repeated_rejected", 0),
                        "repeat_offenders": dict(self._repeat_offenders),
                        "retry_used": retry_used,
                        "anti_repeat_retry": saw_repeats and retry_used,
                        "allow_repeated_reply": allow_repeat,
                        "elapsed_ms": elapsed_ms,
                    }
                }
            )
        response_before_tools = response_text

        # Process tool calls via modular tool handlers
        context = context_part or ""

        # Shared kwargs for recursive tools (medicaid, pubmed, doc fetcher).
        # history_for_llm is COPIED: several tools append the current
        # exchange to it in place before their recursive call, so sharing one
        # list let the first tool's appends garble the second tool's view of
        # the conversation.
        tool_kwargs = dict(
            model_backends=model_backends,
            current_message_for_llm=current_message_for_llm,
            previous_context_summary=previous_context_summary,
            history_for_llm=list(history_for_llm) if history_for_llm else [],
            depth=depth,
            is_logged_in=is_logged_in,
            is_professional=is_professional,
            fallback_backends=fallback_backends,
            full_history=full_history,
            user_message_for_scoring=scoring_message,
        )

        # Non-recursive tools: appeal, prior auth
        appeal_tool = AppealTool(self.send_status_message, self.send_error_message)
        response_text, context, _ = await appeal_tool.handle(
            response_text, context, chat=chat
        )

        prior_auth_tool = PriorAuthTool(
            self.send_status_message, self.send_error_message
        )
        response_text, context, _ = await prior_auth_tool.handle(
            response_text, context, chat=chat
        )

        # Recursive tools: medicaid eligibility, medicaid info, pubmed, doc fetcher
        medicaid_elig_tool = MedicaidEligibilityTool(
            self.send_status_message, self._call_llm_with_actions
        )
        response_text, context, _ = await medicaid_elig_tool.handle(
            response_text, context, **tool_kwargs
        )

        medicaid_info_tool = MedicaidInfoTool(
            self.send_status_message, self._call_llm_with_actions
        )
        response_text, context, _ = await medicaid_info_tool.handle(
            response_text, context, **tool_kwargs
        )

        # Run drug name normalization before PubMed so the LLM can
        # plug a canonical drug name into a follow-up pubmed_query.
        rxnorm_tool = RxNormLookupTool(
            self.send_status_message,
            rxnorm_tools=self.rxnorm_tools,
            call_llm_callback=self._call_llm_with_actions,
        )
        response_text, context, _ = await rxnorm_tool.handle(
            response_text, context, **tool_kwargs
        )

        pubmed_tool = PubMedTool(
            self.send_status_message,
            pubmed_tools=self.pubmed_tools,
            rxnorm_tools=self.rxnorm_tools,
            call_llm_callback=self._call_llm_with_actions,
        )
        response_text, context, _ = await pubmed_tool.handle(
            response_text, context, **tool_kwargs
        )

        uspstf_tool = USPSTFLookupTool(
            self.send_status_message, self._call_llm_with_actions
        )
        response_text, context, _ = await uspstf_tool.handle(
            response_text, context, **tool_kwargs
        )

        clinical_trials_tool = ClinicalTrialsTool(
            self.send_status_message,
            clinical_trials_tools=self.clinical_trials_tools,
            call_llm_callback=self._call_llm_with_actions,
        )
        response_text, context, _ = await clinical_trials_tool.handle(
            response_text, context, **tool_kwargs
        )

        doc_fetcher_tool = DocFetcherTool(
            self.send_status_message,
            call_llm_callback=self._call_llm_with_actions,
            fetch_count=self._doc_fetch_count,
            chat=self.chat,
        )
        response_text, context, _ = await doc_fetcher_tool.handle(
            response_text, context, **tool_kwargs
        )

        pa_requirement_tool = PaRequirementLookupTool(
            self.send_status_message,
            call_llm_callback=self._call_llm_with_actions,
        )
        response_text, context, _ = await pa_requirement_tool.handle(
            response_text, context, **tool_kwargs
        )

        financial_assistance_tool = FinancialAssistanceTool(
            self.send_status_message,
            call_llm_callback=self._call_llm_with_actions,
        )
        response_text, context, _ = await financial_assistance_tool.handle(
            response_text, context, **tool_kwargs
        )

        # Tool processing rewrote the reply (an action/tool flow ran): the
        # raw runner-up no longer corresponds to it, so drop the alternate.
        if depth == 0 and response_text != response_before_tools:
            self._candidate_alternate = None

        logger.debug(f"Return with context length {len(context) if context else 0}.")
        return response_text, context

    async def handle_chat_message(
        self,
        user_message: str,
        iterate_on_appeal: Optional[str] = None,
        iterate_on_prior_auth: Optional[str] = None,
        user: Optional[User] = None,
        is_document: bool = False,
        document_name: Optional[str] = None,
    ):
        """
        Handles an incoming chat message, interacts with LLMs, and manages chat history.
        """
        chat = self.chat
        # A stale alternate from a previous turn must never attach to this
        # turn's reply (early-return paths below don't go through the LLM).
        self._candidate_alternate = None

        # SAFETY: Check for crisis/self-harm indicators in user-authored messages.
        # Skip for document uploads — OCR'd clinical text often contains
        # phrases that match crisis patterns but aren't user distress signals.
        crisis_detected = not is_document and detect_crisis_keywords(user_message)
        if crisis_detected:
            logger.warning(
                f"Crisis keywords detected in chat {chat.id}, providing resources"
            )
            # Send crisis resources as a status/system message first
            # This ensures the user sees help resources immediately
            crisis_response = f"I noticed you might be going through a difficult time. Before we continue, I want to make sure you have access to support:\n\n{CRISIS_RESOURCES}\n\nI'm here to help with health insurance questions, but please reach out to these resources if you need immediate support."
            await self.send_message_to_client(crisis_response)
            # Log the crisis detection for monitoring
            logger.info(f"Crisis resources provided for chat {chat.id}")
            # Add to chat history (transactional merge against the fresh row)
            self.chat = chat = await apersist_chat_turn(
                chat,
                new_messages=[
                    {"role": "user", "content": user_message},
                    {"role": "assistant", "content": crisis_response},
                ],
            )
            # Don't continue with normal processing - let the user respond
            return

        # SAFETY: Check for data-deletion requests in user-authored messages.
        # We can't (and shouldn't) delete data from chat — direct the user to
        # the self-service /remove_data flow which verifies email ownership.
        # Skip for document uploads since OCR'd text often contains the word
        # "delete" out of context.
        if not is_document and detect_delete_data_request(user_message):
            logger.info(
                f"Delete-data request detected in chat {chat.id}, providing self-service link"
            )
            await self.send_message_to_client(DELETE_DATA_RESPONSE)
            # Transactional merge against the fresh row -- background-task
            # updates (summaries, microsite context) can't be clobbered.
            self.chat = chat = await apersist_chat_turn(
                chat,
                new_messages=[
                    {"role": "user", "content": user_message},
                    {"role": "assistant", "content": DELETE_DATA_RESPONSE},
                ],
            )
            return

        # Handle document uploads: store separately and replace with marker in chat
        if is_document and user_message:
            doc_name = document_name or "uploaded_document"
            char_count = len(user_message)
            logger.info(
                f"Document uploaded in chat {chat.id}: {doc_name} ({char_count} chars)"
            )

            denial_context = await self._denial_context_for_chat(chat)

            await process_uploaded_document(
                chat=chat,
                document_name=doc_name,
                full_text=user_message,
                denial_context=denial_context,
            )

            user_message = (
                f"I've uploaded a document: {doc_name} ({char_count:,} characters). "
                f"The document is being analyzed and its contents are available for reference."
            )
            await self.send_status_message(
                f"Document received: {doc_name}. Analyzing content in background..."
            )

        # Check if this is a new chat BEFORE any linking modifies chat_history
        is_new_chat = not bool(chat.chat_history)

        # Load microsite context on first interaction (before linking may return early)
        if is_new_chat and chat.microsite_slug:
            try:
                microsite = get_microsite(chat.microsite_slug)
                if microsite:

                    async def fetch_microsite_context():
                        """Fetch microsite context including RAG evidence."""
                        try:
                            # Send status message if PubMed search is available
                            if microsite.pubmed_search_terms:
                                safe_procedure = str(microsite.default_procedure)[:100]
                                await self.send_status_message(
                                    f"Searching medical literature for {safe_procedure}..."
                                )

                            # Fetch combined context (extralinks + PubMed) and RAG in parallel
                            combined_awaitable = microsite.get_combined_context(
                                pubmed_tools=(
                                    self.pubmed_tools
                                    if microsite.pubmed_search_terms
                                    else None
                                ),
                                max_extralink_docs=5,
                                max_extralink_chars=2000,
                                max_pubmed_terms=3,
                                max_pubmed_articles=20,
                            )

                            # Build a denial-like query from microsite info
                            rag_query_parts = [microsite.default_procedure]
                            if microsite.default_condition:
                                rag_query_parts.append(microsite.default_condition)
                            if microsite.common_denial_reasons:
                                rag_query_parts.append(
                                    microsite.common_denial_reasons[0]
                                )
                            rag_query = " - ".join(rag_query_parts)

                            # Try to get state from a linked denial if available
                            rag_state = None
                            if await chat.appeals.aexists():
                                # select_related caches for_denial so the
                                # attribute access below stays async-safe
                                # without a bridge.
                                appeal = await chat.appeals.select_related(
                                    "for_denial"
                                ).afirst()
                                if appeal and appeal.for_denial:
                                    rag_state = appeal.for_denial.state

                            rag_awaitable = get_rag_context_for_denial(
                                denial_text=rag_query,
                                state=rag_state,
                            )

                            results = await asyncio.gather(
                                combined_awaitable,
                                rag_awaitable,
                                return_exceptions=True,
                            )

                            combined_context = (
                                results[0] if isinstance(results[0], str) else None
                            )
                            rag_context = (
                                results[1] if isinstance(results[1], str) else None
                            )

                            all_context_parts = []
                            if combined_context:
                                all_context_parts.append(combined_context)
                            if rag_context:
                                all_context_parts.append(
                                    f"Medical guidelines and regulations:\n{rag_context}"
                                )
                                logger.info(
                                    f"RAG context added to chat for microsite {microsite.slug}"
                                )

                            if all_context_parts:
                                full_context = "\n\n".join(all_context_parts)
                                microsite_entry = f"Microsite context:\n{full_context}"
                                # Store via the transactional helper: this
                                # background task races the main turn's
                                # persist, and a read-modify-asave here was a
                                # classic lost-update writer. The helper also
                                # keeps the placeholder-safety rule (own entry
                                # rather than appending to a placeholder tag).
                                await apersist_microsite_context(chat, microsite_entry)

                                logger.info(
                                    f"Stored microsite context for {microsite.slug} in chat"
                                )

                            # Send completion message if PubMed search was performed
                            if microsite.pubmed_search_terms:
                                await self.send_status_message(
                                    "Medical literature search complete"
                                )
                        except Exception as e:
                            logger.opt(exception=True).warning(
                                f"Error loading microsite context: {e}"
                            )

                    await fire_and_forget_in_new_threadpool(fetch_microsite_context())
                else:
                    logger.warning(
                        f"Could not find microsite for slug {chat.microsite_slug}"
                    )
            except Exception as e:
                logger.warning(f"Error loading microsite for chat {chat.id}: {e}")

        # Check for policy document analysis request
        if _detect_policy_analysis_request(user_message):
            await self._handle_policy_analysis(chat, user_message)
            return

        # Handle chat ↔ appeal/prior auth linking if requested

        link_message = None
        user_facing_message = None
        # Note: We intentionally do NOT send the link message to the LLM/model immediately.
        # This allows the user to drive the next step, and avoids confusing the model with system state changes.
        # Also we require their is a pro user to enable linking.
        if iterate_on_appeal and user:
            await self.send_status_message("Linking appeal into chat")
            appeal = await database_sync_to_async(Appeal.get_optional_for_user)(
                user, id=iterate_on_appeal
            )
            if not appeal:
                await self.send_error_message(
                    "Appeal not found, or you do not have permission to access it."
                )
                return
            appeal_details = await database_sync_to_async(appeal.details)()
            if appeal.chat_id != chat.id:
                appeal.chat = chat
                await appeal.asave()
                link_message = f"Linked this chat to Appeal #{appeal.id} -- help the user iterate on {appeal_details}"
                user_facing_message = "I've linked this chat to your appeal. How can I help you iterate on it?"
            else:
                link_message = f"This chat is already linked to Appeal #{appeal.id} -- the current appeal text is {appeal_details}, help the user iterate on it"
                user_facing_message = "This chat is already linked to your appeal. How can I help you with it?"
        if iterate_on_prior_auth and user:
            await self.send_status_message(
                "Linking prior authorization request into chat"
            )
            prior_auth = await database_sync_to_async(
                PriorAuthRequest.get_optional_for_user
            )(user, id=iterate_on_prior_auth)
            if not prior_auth:
                await self.send_error_message(
                    "Prior Auth Request not found or you do not have permission to access it."
                )
                return
            # PriorAuthRequest.details() only reads local columns (unlike
            # Appeal.details(), which walks relations) — no bridge needed.
            prior_auth_details = prior_auth.details()
            if prior_auth.chat_id != chat.id:
                prior_auth.chat = chat
                await prior_auth.asave()
                link_message = f"Linked this chat to Prior Auth Request #{prior_auth.id}, details are {prior_auth_details}"
                user_facing_message = "I've linked this chat to your prior authorization request. How can I help you with it?"
            else:
                link_message = f"This chat is already linked to Prior Auth Request #{prior_auth.id}, current details are {prior_auth_details}"
                user_facing_message = "This chat is already linked to your prior authorization request. How can I help you with it?"
        if link_message and user_facing_message:
            await asyncio.sleep(0.01)
            # Transactional merge against the fresh row (see apersist_chat_turn).
            # The link note is context for the LLM, not something the user
            # typed: flag it internal so replays don't render it as a user
            # bubble (see _is_internal_history_message).
            self.chat = chat = await apersist_chat_turn(
                chat,
                new_messages=[
                    {"role": "user", "content": link_message, "internal": True},
                    {"role": "assistant", "content": user_facing_message},
                ],
            )
            await self.send_message_to_client(user_facing_message)
            return

        # Get primary and fallback models based on user preference
        primary_models, fallback_models = ml_router.get_chat_backends_with_fallback(
            use_external=self.use_external_models
        )
        if not primary_models:
            await self.send_error_message(
                "Sorry, no language models are currently available."
            )
            return

        # Refresh from the DB so background-task updates (summaries, microsite
        # context) are visible for this LLM call. A full refetch is safe here:
        # every path that mutated chat state above either persisted through
        # the transactional helper (and rebound self.chat) or returned early.
        try:
            self.chat = chat = await OngoingChat.objects.aget(id=chat.id)
        except OngoingChat.DoesNotExist:
            logger.warning(f"Chat {chat.id} vanished before LLM call; keeping copy")

        current_llm_context = None
        if chat.summary_for_next_call and len(chat.summary_for_next_call) > 0:
            current_llm_context = chat.summary_for_next_call[-1]
            # Include the previous context summary so the model has continuity
            # across summarization boundaries (e.g. microsite context, PubMed).
            if len(chat.summary_for_next_call) > 1:
                prev_summary = chat.summary_for_next_call[-2]
                if prev_summary and str(prev_summary).strip():
                    current_llm_context = (
                        f"Previous context summary:\n{prev_summary}\n\n"
                        f"Most recent context summary:\n{current_llm_context}"
                    )
            # Bound the accreted context: summaries nest labels over long
            # chats ("Earlier conversation summary: ... Additional context:
            # ...") and an unbounded blob both crowds out the actual history
            # and degrades weaker models into replaying old turns.
            current_llm_context = bound_summary_context(
                current_llm_context,
                int(_env_float("FHI_CHAT_MAX_SUMMARY_CHARS", 6000.0)),
            )

        # Build message variants: the original/primary path plus lower-scored
        # long-message and weird-Unicode alternatives. A normal short message
        # yields a single primary_original variant, so the wrapped input, stored
        # history, and scoring stay identical to sending the raw message.
        message_variants = prepare_user_message_variants(
            user_message,
            is_document=is_document,
            document_name=document_name,
        )

        # Long paste detected (and not already an explicit upload): preserve the
        # full original in document storage and switch history/scoring to a
        # compact marker, so we neither bloat chat_history nor fan the huge text
        # out to every backend.
        long_paste_variant = next(
            (v for v in message_variants if v.metadata.get("store_full_text")),
            None,
        )
        if long_paste_variant is not None and not is_document:
            char_count = long_paste_variant.metadata.get(
                "char_count", len(user_message)
            )
            doc_name = long_paste_variant.metadata.get(
                "document_name",
                f"pasted_message_{int(timezone.now().timestamp())}.txt",
            )
            logger.info(
                f"Long pasted message in chat {chat.id}: storing {char_count} chars "
                f"as {doc_name} for reference"
            )
            denial_context = await self._denial_context_for_chat(chat)
            await process_uploaded_document(
                chat=chat,
                document_name=doc_name,
                full_text=user_message,
                denial_context=denial_context,
            )
            await self.send_status_message(
                f"Long message received ({char_count:,} chars). "
                f"Stored for reference and analyzing in background..."
            )
            # From here on, history + scoring use the compact marker.
            user_message = long_paste_variant.display_text or user_message

        # Determine how to wrap a variant's text for the LLM (intro template on
        # new chats, delete-data instruction on ongoing turns), then apply it to
        # every variant. The trial banner is a one-time side effect for new chats.
        if is_new_chat:
            if self.is_trial_professional:
                trial_banner = {
                    "role": "system",
                    "content": "⚠️ You're using a free trial version. Responses may be slower, and features like linked appeals and prior auths require a full professional account.\n\nWant full access? [Create a free account →](/signup)",
                    "timestamp": timezone.now().isoformat(),
                }
                # We don't add the trial banner to the history since it needs to
                # go user -> agent -> user.
                await self.send_json_message_func(trial_banner)

            user_info_str = await self._get_user_info()
            template = get_intro_template(self.chat.chat_type)

            def wrap_for_llm(text: str) -> str:
                return template.format(user_info=user_info_str, message=text)

        else:
            # Terse-reply bridge: short answers like "CA" or "yes 2 people"
            # right after we asked a question are exactly where models fell
            # into re-asking loops -- they'd ignore the terse reply and
            # re-send the previous message. Make the linkage explicit so the
            # model treats the reply as the answer to its own question.
            terse_bridge = ""
            stripped_message = (user_message or "").strip()
            if (
                stripped_message
                and len(stripped_message) <= TERSE_REPLY_MAX_CHARS
                and not is_document
            ):
                last_assistant_reply = next(
                    (
                        m.get("content")
                        for m in reversed(chat.chat_history or [])
                        if m.get("role") == "assistant" and m.get("content")
                    ),
                    None,
                )
                if last_assistant_reply and "?" in last_assistant_reply:
                    terse_bridge = (
                        "\n\n[Note from the system, not the user: this short "
                        "reply answers the question(s) in your previous "
                        "message. Combine it with the conversation history "
                        "and take the next step -- do not re-ask questions it "
                        "answers and do not repeat your previous message.]"
                    )

            def wrap_for_llm(text: str) -> str:
                # Re-inject the delete-data handoff instruction on every ongoing
                # turn. The intro template (which contains it) only fires for new
                # chats, so without this the sentinel fallback would silently
                # stop working past the first message.
                return f"{DELETE_DATA_INSTRUCTION}\n\n{text}{terse_bridge}"

        llm_message_variants = [
            replace(v, text_for_llm=wrap_for_llm(v.text_for_llm))
            for v in message_variants
        ]
        # Prefer the primary variant for the single-message fields (recursion,
        # tool calls); fall back to the best alternative for long pastes.
        primary_variant = next(
            (v for v in llm_message_variants if v.kind == "primary_original"),
            llm_message_variants[0],
        )
        llm_input_message = primary_variant.text_for_llm

        # Prepare history for LLM using the context manager
        # This handles truncation, summarization, and full history preservation
        (
            history_for_llm,
            full_history_for_llm,
            summarized_context,
        ) = await prepare_history_for_llm(
            chat_history=chat.chat_history,
            existing_summary=current_llm_context,
            summarize_callback=self.send_status_message,
        )

        # Summary entries added this turn. Persistence appends these to the
        # FRESH row inside a transaction (apersist_chat_turn), so we track
        # them separately from the in-memory list, which may be stale.
        turn_summaries: List[Optional[str]] = []

        # Store the updated summary if it changed
        if should_store_summary(chat.summary_for_next_call, summarized_context):
            if not chat.summary_for_next_call:
                chat.summary_for_next_call = []
            chat.summary_for_next_call.append(summarized_context)
            turn_summaries.append(summarized_context)
            logger.info(f"Stored updated summary for chat {chat.id}")

        final_response_text = None
        final_context_part = None

        # Inject uploaded document context into the LLM call. Guarded: a
        # failure searching stored documents must degrade to "no doc context"
        # rather than kill the whole turn.
        doc_context_str = None
        try:
            doc_context_str = await get_document_context_for_message(
                chat.id, user_message
            )
        except Exception as e:
            logger.warning(f"Skipping document context for chat {chat.id}: {e}")
        if doc_context_str:
            summarized_context = (
                f"{doc_context_str}\n\n{summarized_context}"
                if summarized_context
                else doc_context_str
            )

        # Transient IP-derived location hint (never persisted): lets the
        # model skip the "which state are you in?" round-trip when the guess
        # is right, while the wording keeps it explicitly unconfirmed so the
        # model verifies rather than assumes when the state matters.
        if self.state_hint:
            state_hint_context = (
                f"Possible user location based on network information "
                f"(an UNCONFIRMED guess that can be wrong, e.g. VPNs or "
                f"shared networks): {self.state_hint}. If the user's state "
                f"matters for your answer (for example Medicaid questions), "
                f"confirm it with the user -- for instance 'It looks like "
                f"you might be in {self.state_hint}, is that right?' -- "
                f"instead of assuming. Do NOT put this guess in your context "
                f"summary unless the user confirms it: the summary is stored "
                f"with the chat, and an unconfirmed network-derived location "
                f"must not be."
            )
            summarized_context = (
                f"{summarized_context}\n\n{state_hint_context}"
                if summarized_context
                else state_hint_context
            )

        if self.is_trial_professional:
            await asyncio.sleep(0.5)  # Half a second delay for trial users.

        # Note: Medicaid queries are now handled through the tool calling system
        # The model can call the medicaid_info tool when needed using the format:
        # **medicaid_info {"state": "StateName", "topic": "", "limit": 5}**
        # (The double asterisks around the entire tool call are required)
        # USPSTF preventive recommendations: **uspstf_lookup {"query": "...", "grade": "A"}**

        # Persist the user's message BEFORE generation. Channels cancels the
        # consumer's coroutine on disconnect, and persistence used to happen
        # only after the LLM returned -- so a network blip mid-turn silently
        # erased the user's message from history (CancelledError skips the
        # failure-path persist too). The final persist below merges against
        # fresh state with tail-dedup, so this never duplicates the message.
        # Deliberately NOT rebinding self.chat/chat: scoring and history prep
        # treat chat.chat_history as the PRE-turn history (the current
        # message travels separately). Guarded: persistence problems must
        # not block the turn -- worst case we fall back to the old
        # persist-at-end behavior.
        # Once pre-persisted, the end-of-turn persists must NOT resubmit the
        # user message: with two connections racing on one chat, the other
        # turn's pre-persist can merge into this message ("A" -> "A B"), and
        # resubmitting "A" against that merged tail would append it AGAIN
        # ("A B A") instead of deduping.
        user_message_prepersisted = False
        if user_message and user_message.strip():
            try:
                await apersist_chat_turn(
                    chat,
                    new_messages=[{"role": "user", "content": user_message}],
                )
                user_message_prepersisted = True
            except OngoingChat.DoesNotExist:
                logger.warning(
                    f"Chat {chat.id} vanished before the turn started; "
                    f"continuing unpersisted"
                )
            except Exception:
                logger.opt(exception=True).warning(
                    f"Could not pre-persist user message for chat {chat.id}; "
                    f"continuing (will persist at turn end)"
                )

        # Debug visibility: show exactly what is being sent to the backend
        # model for this turn. Gated upstream (settings.DEBUG or staff), and
        # the content is the requesting user's own conversation, so sending
        # it back over their socket exposes nothing new. Also logged
        # server-side (sizes only -- message content is PHI).
        if self.debug_llm:
            debug_payload = {
                "message_for_llm": llm_input_message,
                "context_summary": summarized_context,
                "history_message_count": len(history_for_llm),
                "full_history_message_count": (
                    len(full_history_for_llm) if full_history_for_llm else 0
                ),
                "message_variants": [v.kind for v in llm_message_variants],
                "state_hint": self.state_hint,
            }
            await self.send_json_message_func({"debug_llm_input": debug_payload})
        logger.debug(
            f"Chat {chat.id}: sending turn to LLM "
            f"(message_chars={len(llm_input_message)}, "
            f"context_chars={len(summarized_context) if summarized_context else 0}, "
            f"history_msgs={len(history_for_llm)}, "
            f"full_history_msgs={len(full_history_for_llm) if full_history_for_llm else 0})"
        )

        # Overall wall-clock budget for this turn's LLM + tool work, plus a
        # heartbeat so the user (and any idle-reaping proxy between us) sees
        # traffic while a long turn is still working. Without the budget a
        # wedged backend chain could hold the turn open indefinitely with the
        # client showing a spinner forever.
        turn_budget = _env_float("FHI_CHAT_TURN_BUDGET", 150.0)
        turn_timed_out = False
        heartbeat_task = asyncio.create_task(self._turn_heartbeat())
        try:
            response_text, context_part = await asyncio.wait_for(
                self._call_llm_with_actions(
                    primary_models,
                    llm_input_message,
                    summarized_context,
                    history_for_llm,
                    is_logged_in=(self.user is not None and self.user.is_authenticated),
                    is_professional=self.is_professional or self.is_trial_professional,
                    fallback_backends=fallback_models if fallback_models else None,
                    full_history=full_history_for_llm,  # Also try with full history if model supports it
                    user_message_for_scoring=user_message,
                    message_variants=llm_message_variants,
                ),
                timeout=turn_budget,
            )

            if response_text and response_text.strip():
                cleaned = _clean_reply(response_text)
                if llm_requested_delete_handoff(cleaned):
                    logger.info(
                        f"LLM emitted delete-data sentinel in chat {chat.id}, swapping in canned response"
                    )
                    cleaned = DELETE_DATA_RESPONSE
                final_response_text = cleaned
                final_context_part = context_part
                # Observability for the loop-prevention ladder: a delivered
                # reply that STILL repeats a recent reply means every rung
                # (hard rejection, anti-repeat retry) produced only repeats.
                # Should stay rare -- alert on this counter growing.
                if (
                    final_response_text
                    and not user_requested_repeat(user_message)
                    and find_repeated_reply(
                        final_response_text, chat.chat_history, user_message
                    )
                ):
                    record_chat_repeat("delivered_repeat")
                    logger.warning(
                        f"Chat {chat.id}: delivering a reply that repeats a "
                        f"recent reply (all anti-repeat rungs exhausted)"
                    )
        except asyncio.TimeoutError:
            logger.error(
                f"Chat turn exceeded its {turn_budget:.0f}s budget for chat "
                f"{chat.id}; giving up on this turn"
            )
            # Recorded here as "timeout"; the shared failure branch below
            # checks this flag so the same turn isn't also counted "failed".
            turn_timed_out = True
            record_chat_turn("timeout")
        except Exception as e:
            logger.opt(exception=True).error(
                f"Chat generation failed for chat {chat.id}: {e}"
            )
            logger.debug(f"Models tried for failed chat {chat.id}: {primary_models}")
        finally:
            heartbeat_task.cancel()

        if final_response_text:
            if should_store_summary(chat.summary_for_next_call, final_context_part):
                if not chat.summary_for_next_call:
                    chat.summary_for_next_call = []
                chat.summary_for_next_call.append(final_context_part)
                turn_summaries.append(final_context_part)

            # If model didn't return a context summary, store a placeholder and
            # fire a background task to generate one
            background_summary_task = None
            if final_response_text and not final_context_part:
                if not chat.summary_for_next_call:
                    chat.summary_for_next_call = []
                # The counter only needs to make the placeholder tag unique;
                # +2 accounts for the user/assistant pair persisted below.
                history_len = (len(chat.chat_history) if chat.chat_history else 0) + 2
                placeholder = make_placeholder(history_len)
                chat.summary_for_next_call.append(placeholder)
                turn_summaries.append(placeholder)
                background_summary_task = background_generate_summary(
                    chat.id, placeholder
                )

            # Persist against the fresh row (transactional re-read + merge) so
            # concurrent writers -- background summaries, the microsite fetch,
            # a second tab -- can't be clobbered by this stale in-memory
            # object. Duplicate detection and consecutive-user-message merging
            # happen in the helper, against the fresh tail. Rebind to the
            # merged row so later turns and replays see the true state.
            # Guarded: the chat row can vanish mid-turn (data deletion); the
            # user still gets the generated reply, it just isn't persisted.
            try:
                # The user message is only resubmitted when the pre-persist
                # failed -- see user_message_prepersisted above for why.
                end_of_turn_messages = [
                    {"role": "assistant", "content": final_response_text}
                ]
                if not user_message_prepersisted:
                    end_of_turn_messages.insert(
                        0, {"role": "user", "content": user_message}
                    )
                self.chat = chat = await apersist_chat_turn(
                    chat,
                    new_messages=end_of_turn_messages,
                    new_summaries=turn_summaries,
                )
            except OngoingChat.DoesNotExist:
                logger.warning(
                    f"Chat {chat.id} vanished before the turn could be "
                    f"persisted; delivering the reply unpersisted"
                )
                background_summary_task = None

            # Launch background summary after save so the task can read the latest history
            if background_summary_task is not None:
                await fire_and_forget_in_new_threadpool(background_summary_task)
            record_chat_turn("ok")
            # Side-by-side alternate answer (ChatGPT-style "here's another
            # take"): cleaned like the primary, dropped if cleaning leaves it
            # too similar to what we're already sending. Ephemeral -- only
            # the primary reply is persisted, so replays show one answer.
            alternate_content = self._candidate_alternate
            self._candidate_alternate = None
            if alternate_content:
                alt_cleaned = _clean_reply(alternate_content)
                # A runner-up that also asked for the delete-data handoff must
                # never be shown: the primary gets swapped for the approved
                # DELETE_DATA_RESPONSE, so an unswapped alternate would sit
                # beside it either leaking the raw sentinel or making
                # model-authored promises about deleting the user's data.
                if alt_cleaned and llm_requested_delete_handoff(alt_cleaned):
                    logger.info(
                        f"Chat {chat.id}: dropping alternate that requested the "
                        f"delete-data handoff"
                    )
                    alt_cleaned = ""
                if alt_cleaned and alternate_is_presentable(
                    alt_cleaned,
                    final_response_text,
                    chat_history=chat.chat_history,
                    current_message=user_message,
                ):
                    alternate_content = alt_cleaned
                    record_chat_alternate_offered()
                    logger.info(f"Chat {chat.id}: offering an alternate answer")
                else:
                    alternate_content = None
            await self.send_message_to_client(
                final_response_text, alternate_content=alternate_content
            )
        else:
            # The turn failed after the user already committed their message:
            # persist it anyway so a reconnect/replay doesn't erase what they
            # typed (previously the whole turn was dropped on failure). Only
            # resubmitted when the pre-persist failed -- see
            # user_message_prepersisted above.
            try:
                self.chat = chat = await apersist_chat_turn(
                    chat,
                    new_messages=(
                        []
                        if user_message_prepersisted
                        else [{"role": "user", "content": user_message}]
                    ),
                    new_summaries=turn_summaries,
                )
            except Exception:
                logger.opt(exception=True).error(
                    f"Could not persist user message for failed turn in chat {chat.id}"
                )
            # Provide more helpful error message based on context
            err_msg = (
                "Sorry, all available models (including backup models) are currently "
                "experiencing issues. Please try again in a few moments. "
                "If the problem persists, try refreshing the page or starting a new chat."
            )
            if not self.use_external_models:
                err_msg = (
                    "Sorry, our primary models are currently busy or experiencing issues. "
                    "You can enable 'Use backup models' in settings to allow fallback to "
                    "additional model providers when our primary models are unavailable."
                )
            logger.error(
                f"Failed to generate response for user_message: '{user_message}' in chat {chat.id} "
                f"after trying all models. use_external_models={self.use_external_models}"
            )
            if not turn_timed_out:
                record_chat_turn("failed")
            capture_reliability_event(
                "chat_turn_total_failure",
                chat_id=str(chat.id),
                use_external_models=self.use_external_models,
                message_chars=len(user_message or ""),
            )
            await self.send_error_message(err_msg)

    # Legacy prefixes of internal (LLM-context-only) user-role messages that
    # predate the explicit "internal" flag; matched so old chats don't replay
    # them either.
    @classmethod
    def _is_internal_history_message(cls, message: Dict[str, Any]) -> bool:
        """Messages stored purely as LLM context (e.g. the appeal-linking
        notes recorded with role=user) must not replay as user bubbles."""
        return is_internal_history_message(message)

    async def replay_chat_history(self):
        """Sends the existing chat history to the client, minus internal
        LLM-context-only messages (which would render as user bubbles the
        user never typed)."""
        chat = self.chat
        await self.send_json_message_func(
            {"messages": visible_history(chat.chat_history)}
        )

    async def _handle_policy_analysis(
        self, chat: OngoingChat, user_message: str
    ) -> None:
        """
        Handle policy document analysis request.
        Looks for associated policy documents and triggers chunked parallel analysis.
        Always sends a response (success or error) so the caller can return immediately.
        """
        try:
            policy_doc: Optional[PolicyDocument] = None
            # PolicyDocument rows are keyed by the DJANGO session key (the
            # upload happens in a regular HTTP view), while chat.session_key
            # is a client-generated localStorage string -- the two never
            # match for anonymous users, which left this handoff dead. Try
            # the server session key first, then the chat's own key.
            candidate_keys = [
                k for k in (self.server_session_key, chat.session_key) if k
            ]

            from django.contrib.sessions.backends.db import SessionStore

            def _get_session_doc_id(sk: str) -> Optional[str]:
                session = SessionStore(session_key=sk)
                return session.get("policy_document_id")

            for session_key in candidate_keys:
                doc_id = await database_sync_to_async(_get_session_doc_id)(session_key)
                if doc_id:
                    policy_doc = await PolicyDocument.objects.filter(
                        id=doc_id,
                        session_key=session_key,
                    ).afirst()
                if not policy_doc:
                    policy_doc = (
                        await PolicyDocument.objects.filter(session_key=session_key)
                        .order_by("-created_at")
                        .afirst()
                    )
                    logger.debug(
                        f"Policy doc session_key fallback: doc_id={policy_doc.id if policy_doc else None}"
                    )
                if policy_doc:
                    break

            if not policy_doc:
                logger.debug("No policy document found for session")
                await self.send_error_message(
                    "I couldn't find the uploaded policy document for this chat. "
                    "Please re-upload it from the Understand My Policy page."
                )
                return

            logger.info(f"Analyzing policy document {policy_doc.id}")
            await self.send_status_message(
                f"Analyzing your {policy_doc.get_document_type_display()} document..."
            )

            # Extract user's specific question from the message if present
            user_question = None
            question_match = re.search(
                r"My question:\s*(.+?)(?:\n\s*\n|(?:\n)?Please analyze\b|$)",
                user_message,
                re.DOTALL,
            )
            if question_match:
                user_question = re.sub(r"\s+", " ", question_match.group(1)).strip()

            # Progress callback for countdown display
            async def _progress_callback(remaining: int, total: int) -> None:
                if total == 0:
                    await self.send_status_message("Finalizing analysis...")
                elif total == 1 and remaining == 1:
                    await self.send_status_message(
                        "Combining findings into final analysis..."
                    )
                elif remaining == total:
                    await self.send_status_message(
                        f"Launching {total} analysis agents..."
                    )
                else:
                    await self.send_status_message(
                        f"Analyzing policy — {remaining} of {total} agents remaining..."
                    )

            # Get or create analysis with progress updates
            analysis = await MLPolicyDocHelper.get_or_create_analysis(
                policy_doc, user_question, progress_callback=_progress_callback
            )

            if analysis:
                formatted_analysis = MLPolicyDocHelper.format_analysis_for_chat(
                    analysis
                )

                # Persist turn + analysis context transactionally against the
                # fresh row (replaces the old refetch-modify-asave, which
                # could still clobber a writer landing between the two).
                self.chat = chat = await apersist_chat_turn(
                    chat,
                    new_messages=[
                        {"role": "user", "content": user_message},
                        {"role": "assistant", "content": formatted_analysis},
                    ],
                    new_summaries=[
                        f"Policy document analysis ({policy_doc.get_document_type_display()}, id={policy_doc.id}):\n{formatted_analysis[:4000]}"
                    ],
                )

                await self.send_status_message("Policy analysis complete!")
                await self.send_message_to_client(formatted_analysis)
            else:
                await self.send_error_message(
                    "Could not analyze the policy document. Please try again or contact support."
                )

        except Exception as e:
            logger.opt(exception=True).warning(
                f"Error handling policy analysis for chat {chat.id}: {e}"
            )
            await self.send_error_message(
                "There was an error analyzing your policy document. "
                "Please try again or continue with your question."
            )
