import asyncio
import re
from dataclasses import replace
from typing import Any, Awaitable, Callable, Dict, List, Optional, Tuple, cast

from django.utils import timezone

# channels' database_sync_to_async (NOT asgiref's sync_to_async): chat runs
# outside the HTTP request cycle, so only its close_old_connections wrapping
# ever closes the DB connections these calls open.
from channels.db import database_sync_to_async
from loguru import logger

from fhi_users.models import User
from fighthealthinsurance import settings
from fighthealthinsurance.chat.chat_persistence import (
    apersist_chat_turn,
    apersist_microsite_context,
)
from fighthealthinsurance.chat.context_manager import (
    MISSING_CONTEXT_PREFIX,
    background_generate_summary,
    make_placeholder,
    prepare_history_for_llm,
    should_store_summary,
)
from fighthealthinsurance.chat.llm_client import (
    build_llm_calls,
    build_llm_calls_for_variants,
    create_response_scorer,
)
from fighthealthinsurance.chat.message_preprocessor import (
    MessageVariant,
    prepare_user_message_variants,
)
from fighthealthinsurance.chat.document_processor import process_uploaded_document
from fighthealthinsurance.chat.document_search import get_document_context_for_message
from fighthealthinsurance.chat.retry_handler import (
    retry_llm_with_fallback,
    should_retry_response,
)
from fighthealthinsurance.chat.safety_filters import (
    CRISIS_RESOURCES,
    DELETE_DATA_RESPONSE,
    detect_crisis_keywords,
    detect_delete_data_request,
    llm_requested_delete_handoff,
)
from fighthealthinsurance.chat.tools import (
    AppealTool,
    ClinicalTrialsTool,
    DocFetcherTool,
    FinancialAssistanceTool,
    MedicaidEligibilityTool,
    MedicaidInfoTool,
    PaRequirementLookupTool,
    PriorAuthTool,
    PubMedTool,
    RxNormLookupTool,
    USPSTFLookupTool,
)
from fighthealthinsurance.extralink_context_helper import ExtraLinkContextHelper
from fighthealthinsurance.rag_client import get_rag_context_for_denial
from fighthealthinsurance.ml.ml_metrics import record_chat_turn
from fighthealthinsurance.ml.ml_models import (
    RemoteModelLike,
    _env_float,
    remove_repeated_blocks,
    remove_repeated_sentences,
)
from fighthealthinsurance.reliability_events import capture_reliability_event
from fighthealthinsurance.ml.ml_router import ml_router
from fighthealthinsurance.models import (
    Appeal,
    ChatType,
    OngoingChat,
    PolicyDocument,
    PriorAuthRequest,
)
from fighthealthinsurance.microsites import get_microsite
from fighthealthinsurance.prompt_templates import (
    DELETE_DATA_INSTRUCTION,
    get_intro_template,
)
from fighthealthinsurance.clinicaltrials_tools import ClinicalTrialsTools
from fighthealthinsurance.pubmed_tools import PubMedTools
from fighthealthinsurance.rxnorm_tools import RxNormTools
from fighthealthinsurance.utils import (
    best_within_timelimit,
    fire_and_forget_in_new_threadpool,
)
from fighthealthinsurance.ml.ml_policy_doc_helper import MLPolicyDocHelper

# Policy analysis detection: only match the structured message generated by
# UnderstandPolicyView.form_valid(). This avoids false positives from normal
# chat messages that mention "summary of benefits" or "what is covered".
_POLICY_ANALYSIS_REGEX: re.Pattern[str] = re.compile(
    r"I've uploaded my insurance .+\r?\nPlease analyze this document",
    re.IGNORECASE | re.DOTALL,
)


def _detect_policy_analysis_request(text: str) -> bool:
    """Check if the message is the structured policy analysis request from the form."""
    return bool(_POLICY_ANALYSIS_REGEX.search(text))


class ChatInterface:
    def __init__(
        self,
        send_json_message_func: Callable[[Dict[str, Any]], Awaitable[None]],
        chat: OngoingChat,
        user: User,
        use_external_models: bool = False,
        server_session_key: Optional[str] = None,
    ):
        def wrap_send_json_message_func(message: Dict[str, Any]) -> Awaitable[None]:
            """Wraps the send_json_message_func to ensure it's always awaited."""
            if "chat_id" not in message:
                message["chat_id"] = str(chat.id)
            return send_json_message_func(message)

        self.send_json_message_func = wrap_send_json_message_func
        self.pubmed_tools = PubMedTools()
        # Single RxNormTools shared across RxNormLookupTool and PubMedTool
        # so they reuse the same client / cache view per chat session.
        self.rxnorm_tools = RxNormTools()
        self.clinical_trials_tools = ClinicalTrialsTools()
        self.chat: OngoingChat = chat
        self.user: User = user
        self.use_external_models: bool = use_external_models
        # The DJANGO session key from the WebSocket scope. Distinct from
        # chat.session_key, which anonymous clients generate themselves
        # (localStorage random string): server-side flows like the policy
        # upload store their artifacts under the Django session, so lookups
        # must try this key first.
        self.server_session_key: Optional[str] = server_session_key
        self._doc_fetch_count: list[int] = [0]

    @staticmethod
    def _append_to_history(chat, role: str, content: str):
        """Append a message to chat history with a timestamp."""
        if not chat.chat_history:
            chat.chat_history = []
        chat.chat_history.append(
            {
                "role": role,
                "content": content,
                "timestamp": timezone.now().isoformat(),
            }
        )

    @property
    def is_patient(self) -> bool:
        return self.chat.chat_type == ChatType.PATIENT

    @property
    def is_professional(self) -> bool:
        return self.chat.chat_type == ChatType.PROFESSIONAL

    @property
    def is_trial_professional(self) -> bool:
        return self.chat.chat_type == ChatType.TRIAL_PROFESSIONAL

    async def send_error_message(self, message: str):
        """Sends an error message to the client."""
        await self.send_json_message_func(
            {"error": message, "chat_id": str(self.chat.id)}
        )

    async def send_status_message(self, message: str):
        """Sends a status message to the client."""
        logger.debug(f"Chat {self.chat.id} status: {message}")
        await self.send_json_message_func(
            {"status": message, "chat_id": str(self.chat.id)}
        )

    async def _turn_heartbeat(self) -> None:
        """Emit a status frame every FHI_CHAT_HEARTBEAT_SECONDS while a turn
        is being generated.

        Long tool/LLM turns can go minutes without a frame on the socket;
        idle-reaping proxies kill those connections and the user sees a
        spinner that never resolves. Cancelled by the caller when the turn
        finishes; the client already renders ``status`` frames as its loading
        state, so this needs no frontend changes.
        """
        interval = _env_float("FHI_CHAT_HEARTBEAT_SECONDS", 20.0)
        try:
            while True:
                await asyncio.sleep(interval)
                await self.send_status_message("Still working on your reply...")
        except asyncio.CancelledError:
            pass
        except Exception:
            # A failed heartbeat send means the socket is likely gone; the
            # main turn will surface that on its own send.
            logger.debug(f"Heartbeat send failed for chat {self.chat.id}")

    async def send_message_to_client(self, message: str):
        """Sends a message to the client."""
        await self.send_json_message_func(
            {"content": message, "chat_id": str(self.chat.id), "role": "assistant"}
        )

    async def _get_user_info(self) -> str:
        """Generates a descriptive string for the user (either professional or patient)."""
        try:
            return cast(str, await database_sync_to_async(self.chat.summarize_user)())
        except Exception as e:
            logger.warning(f"Could not generate detailed user info: {e}")
            return "a user"

    async def _denial_context_for_chat(self, chat: OngoingChat) -> Optional[str]:
        """Build a short denial-context string (procedure/diagnosis) for a chat.

        Used to give document/long-paste summarization a hint about what the
        linked appeal is about. Returns None when there's no linked denial.
        """
        appeal = (
            await Appeal.objects.select_related("for_denial").filter(chat=chat).afirst()
        )
        if not appeal or not appeal.for_denial:
            return None
        linked_denial = appeal.for_denial
        parts = []
        if linked_denial.procedure or linked_denial.candidate_procedure:
            parts.append(
                f"Procedure: {linked_denial.procedure or linked_denial.candidate_procedure}"
            )
        if linked_denial.diagnosis or linked_denial.candidate_diagnosis:
            parts.append(
                f"Diagnosis: {linked_denial.diagnosis or linked_denial.candidate_diagnosis}"
            )
        return "; ".join(parts) if parts else None

    async def _call_llm_with_actions(
        self,
        model_backends: List[RemoteModelLike],
        current_message_for_llm: str,
        previous_context_summary: Optional[str],
        history_for_llm: List[Dict[str, str]],
        depth: int = 0,
        is_logged_in: bool = True,
        is_professional: bool = True,
        fallback_backends: Optional[List[RemoteModelLike]] = None,
        full_history: Optional[List[Dict[str, str]]] = None,
        user_message_for_scoring: Optional[str] = None,
        message_variants: Optional[List[MessageVariant]] = None,
    ) -> Tuple[Optional[str], Optional[str]]:
        """
        Calls the LLM, handles PubMed query requests if present and returns the response.
        Also processes special tokens for creating or updating Appeals and PriorAuthRequests.

        Args:
            model_backends: List of model backends to try
            current_message_for_llm: The current message to send
            previous_context_summary: Summary of previous context
            history_for_llm: Truncated history (last 20 messages)
            depth: Recursion depth for tool handling
            is_logged_in: Whether user is logged in
            is_professional: Whether user is a professional
            fallback_backends: Backup models to try if primary fails
            full_history: Full untruncated history (optional) - will also try with this
                         if provided and model context allows it
            user_message_for_scoring: The raw user message used by repetition-penalty
                scoring. Distinct from current_message_for_llm, which may be wrapped
                with intro-template content or the delete-data instruction. Defaults
                to current_message_for_llm when not provided.
            message_variants: Optional list of LLM-ready message variants (primary
                first, lower-scored long/Unicode alternatives after). When provided,
                calls are fanned out per variant and each variant's score_delta is
                applied so the primary path wins unless it fails. When None (e.g.
                recursive tool calls), the single current_message_for_llm is used.
        """
        if depth > 3:
            return None, None
        chat = self.chat
        history = history_for_llm

        # Fall back to the model-facing string for scoring when no raw user
        # message was supplied (e.g. recursive tool calls that already carry
        # the wrapped message and don't have access to the original).
        scoring_message = (
            user_message_for_scoring
            if user_message_for_scoring is not None
            else current_message_for_llm
        )

        # Build LLM calls using the extracted module. When message variants are
        # supplied (top-level user turn), fan out per variant and apply each
        # variant's score delta; only the primary_original variant's calls keep
        # the is-primary scoring bonus. Otherwise (recursive tool calls) fall
        # back to the single wrapped message, preserving existing behavior.
        if message_variants:
            calls, call_scores, primary_calls = build_llm_calls_for_variants(
                model_backends=model_backends,
                variants=message_variants,
                previous_context_summary=previous_context_summary,
                history=history,
                is_professional=is_professional,
                is_logged_in=is_logged_in,
                full_history=full_history,
            )
        else:
            calls, call_scores = build_llm_calls(
                model_backends=model_backends,
                current_message=current_message_for_llm,
                previous_context_summary=previous_context_summary,
                history=history,
                is_professional=is_professional,
                is_logged_in=is_logged_in,
                full_history=full_history,
            )
            primary_calls = calls

        # Create scoring function using the extracted module
        score_fn = create_response_scorer(
            call_scores,
            primary_calls=primary_calls,
            chat_history=chat.chat_history,
            current_message=scoring_message,
        )

        try:
            best_call = await best_within_timelimit(
                calls,
                score_fn,
                timeout=30.0,
            )
            response_text, context_part = (
                best_call if best_call is not None else (None, None)
            )
        except Exception as e:
            logger.warning(f"Primary models all failed: {e}")
            response_text = None
            context_part = None

        response_text = response_text or ""

        # If primary models failed, use retry handler with fallback
        if should_retry_response(response_text):
            retry_response, retry_context = await retry_llm_with_fallback(
                model_backends=model_backends,
                current_message=current_message_for_llm,
                previous_context_summary=previous_context_summary,
                history=history,
                is_professional=is_professional,
                is_logged_in=is_logged_in,
                fallback_backends=fallback_backends,
                timeout=35.0,
                status_callback=self.send_status_message,
                chat_history=chat.chat_history,
                user_message_for_scoring=scoring_message,
            )
            if retry_response and len(retry_response.strip()) > 5:
                response_text = retry_response
                context_part = retry_context

        logger.debug(f"Using best result {response_text:.20}...")

        if not response_text:
            logger.debug("Got empty response from LLM")
            return None, None

        # Process tool calls via modular tool handlers
        context = context_part or ""

        # Shared kwargs for recursive tools (medicaid, pubmed, doc fetcher).
        # history_for_llm is COPIED: several tools append the current
        # exchange to it in place before their recursive call, so sharing one
        # list let the first tool's appends garble the second tool's view of
        # the conversation.
        tool_kwargs = dict(
            model_backends=model_backends,
            current_message_for_llm=current_message_for_llm,
            previous_context_summary=previous_context_summary,
            history_for_llm=list(history_for_llm) if history_for_llm else [],
            depth=depth,
            is_logged_in=is_logged_in,
            is_professional=is_professional,
            fallback_backends=fallback_backends,
            full_history=full_history,
            user_message_for_scoring=scoring_message,
        )

        # Non-recursive tools: appeal, prior auth
        appeal_tool = AppealTool(self.send_status_message, self.send_error_message)
        response_text, context, _ = await appeal_tool.handle(
            response_text, context, chat=chat
        )

        prior_auth_tool = PriorAuthTool(
            self.send_status_message, self.send_error_message
        )
        response_text, context, _ = await prior_auth_tool.handle(
            response_text, context, chat=chat
        )

        # Recursive tools: medicaid eligibility, medicaid info, pubmed, doc fetcher
        medicaid_elig_tool = MedicaidEligibilityTool(
            self.send_status_message, self._call_llm_with_actions
        )
        response_text, context, _ = await medicaid_elig_tool.handle(
            response_text, context, **tool_kwargs
        )

        medicaid_info_tool = MedicaidInfoTool(
            self.send_status_message, self._call_llm_with_actions
        )
        response_text, context, _ = await medicaid_info_tool.handle(
            response_text, context, **tool_kwargs
        )

        # Run drug name normalization before PubMed so the LLM can
        # plug a canonical drug name into a follow-up pubmed_query.
        rxnorm_tool = RxNormLookupTool(
            self.send_status_message,
            rxnorm_tools=self.rxnorm_tools,
            call_llm_callback=self._call_llm_with_actions,
        )
        response_text, context, _ = await rxnorm_tool.handle(
            response_text, context, **tool_kwargs
        )

        pubmed_tool = PubMedTool(
            self.send_status_message,
            pubmed_tools=self.pubmed_tools,
            rxnorm_tools=self.rxnorm_tools,
            call_llm_callback=self._call_llm_with_actions,
        )
        response_text, context, _ = await pubmed_tool.handle(
            response_text, context, **tool_kwargs
        )

        uspstf_tool = USPSTFLookupTool(
            self.send_status_message, self._call_llm_with_actions
        )
        response_text, context, _ = await uspstf_tool.handle(
            response_text, context, **tool_kwargs
        )

        clinical_trials_tool = ClinicalTrialsTool(
            self.send_status_message,
            clinical_trials_tools=self.clinical_trials_tools,
            call_llm_callback=self._call_llm_with_actions,
        )
        response_text, context, _ = await clinical_trials_tool.handle(
            response_text, context, **tool_kwargs
        )

        doc_fetcher_tool = DocFetcherTool(
            self.send_status_message,
            call_llm_callback=self._call_llm_with_actions,
            fetch_count=self._doc_fetch_count,
            chat=self.chat,
        )
        response_text, context, _ = await doc_fetcher_tool.handle(
            response_text, context, **tool_kwargs
        )

        pa_requirement_tool = PaRequirementLookupTool(
            self.send_status_message,
            call_llm_callback=self._call_llm_with_actions,
        )
        response_text, context, _ = await pa_requirement_tool.handle(
            response_text, context, **tool_kwargs
        )

        financial_assistance_tool = FinancialAssistanceTool(
            self.send_status_message,
            call_llm_callback=self._call_llm_with_actions,
        )
        response_text, context, _ = await financial_assistance_tool.handle(
            response_text, context, **tool_kwargs
        )

        logger.debug(f"Return with context length {len(context) if context else 0}.")
        return response_text, context

    async def handle_chat_message(
        self,
        user_message: str,
        iterate_on_appeal: Optional[str] = None,
        iterate_on_prior_auth: Optional[str] = None,
        user: Optional[User] = None,
        is_document: bool = False,
        document_name: Optional[str] = None,
    ):
        """
        Handles an incoming chat message, interacts with LLMs, and manages chat history.
        """
        chat = self.chat

        # SAFETY: Check for crisis/self-harm indicators in user-authored messages.
        # Skip for document uploads — OCR'd clinical text often contains
        # phrases that match crisis patterns but aren't user distress signals.
        crisis_detected = not is_document and detect_crisis_keywords(user_message)
        if crisis_detected:
            logger.warning(
                f"Crisis keywords detected in chat {chat.id}, providing resources"
            )
            # Send crisis resources as a status/system message first
            # This ensures the user sees help resources immediately
            crisis_response = f"I noticed you might be going through a difficult time. Before we continue, I want to make sure you have access to support:\n\n{CRISIS_RESOURCES}\n\nI'm here to help with health insurance questions, but please reach out to these resources if you need immediate support."
            await self.send_message_to_client(crisis_response)
            # Log the crisis detection for monitoring
            logger.info(f"Crisis resources provided for chat {chat.id}")
            # Add to chat history (transactional merge against the fresh row)
            self.chat = chat = await apersist_chat_turn(
                chat,
                new_messages=[
                    {"role": "user", "content": user_message},
                    {"role": "assistant", "content": crisis_response},
                ],
            )
            # Don't continue with normal processing - let the user respond
            return

        # SAFETY: Check for data-deletion requests in user-authored messages.
        # We can't (and shouldn't) delete data from chat — direct the user to
        # the self-service /remove_data flow which verifies email ownership.
        # Skip for document uploads since OCR'd text often contains the word
        # "delete" out of context.
        if not is_document and detect_delete_data_request(user_message):
            logger.info(
                f"Delete-data request detected in chat {chat.id}, providing self-service link"
            )
            await self.send_message_to_client(DELETE_DATA_RESPONSE)
            # Transactional merge against the fresh row -- background-task
            # updates (summaries, microsite context) can't be clobbered.
            self.chat = chat = await apersist_chat_turn(
                chat,
                new_messages=[
                    {"role": "user", "content": user_message},
                    {"role": "assistant", "content": DELETE_DATA_RESPONSE},
                ],
            )
            return

        # Handle document uploads: store separately and replace with marker in chat
        if is_document and user_message:
            doc_name = document_name or "uploaded_document"
            char_count = len(user_message)
            logger.info(
                f"Document uploaded in chat {chat.id}: {doc_name} ({char_count} chars)"
            )

            denial_context = await self._denial_context_for_chat(chat)

            await process_uploaded_document(
                chat=chat,
                document_name=doc_name,
                full_text=user_message,
                denial_context=denial_context,
            )

            user_message = (
                f"I've uploaded a document: {doc_name} ({char_count:,} characters). "
                f"The document is being analyzed and its contents are available for reference."
            )
            await self.send_status_message(
                f"Document received: {doc_name}. Analyzing content in background..."
            )

        # Check if this is a new chat BEFORE any linking modifies chat_history
        is_new_chat = not bool(chat.chat_history)

        # Load microsite context on first interaction (before linking may return early)
        if is_new_chat and chat.microsite_slug:
            try:
                microsite = get_microsite(chat.microsite_slug)
                if microsite:

                    async def fetch_microsite_context():
                        """Fetch microsite context including RAG evidence."""
                        try:
                            # Send status message if PubMed search is available
                            if microsite.pubmed_search_terms:
                                safe_procedure = str(microsite.default_procedure)[:100]
                                await self.send_status_message(
                                    f"Searching medical literature for {safe_procedure}..."
                                )

                            # Fetch combined context (extralinks + PubMed) and RAG in parallel
                            combined_awaitable = microsite.get_combined_context(
                                pubmed_tools=(
                                    self.pubmed_tools
                                    if microsite.pubmed_search_terms
                                    else None
                                ),
                                max_extralink_docs=5,
                                max_extralink_chars=2000,
                                max_pubmed_terms=3,
                                max_pubmed_articles=20,
                            )

                            # Build a denial-like query from microsite info
                            rag_query_parts = [microsite.default_procedure]
                            if microsite.default_condition:
                                rag_query_parts.append(microsite.default_condition)
                            if microsite.common_denial_reasons:
                                rag_query_parts.append(
                                    microsite.common_denial_reasons[0]
                                )
                            rag_query = " - ".join(rag_query_parts)

                            # Try to get state from a linked denial if available
                            rag_state = None
                            if await chat.appeals.aexists():
                                # select_related caches for_denial so the
                                # attribute access below stays async-safe
                                # without a bridge.
                                appeal = await chat.appeals.select_related(
                                    "for_denial"
                                ).afirst()
                                if appeal and appeal.for_denial:
                                    rag_state = appeal.for_denial.state

                            rag_awaitable = get_rag_context_for_denial(
                                denial_text=rag_query,
                                state=rag_state,
                            )

                            results = await asyncio.gather(
                                combined_awaitable,
                                rag_awaitable,
                                return_exceptions=True,
                            )

                            combined_context = (
                                results[0] if isinstance(results[0], str) else None
                            )
                            rag_context = (
                                results[1] if isinstance(results[1], str) else None
                            )

                            all_context_parts = []
                            if combined_context:
                                all_context_parts.append(combined_context)
                            if rag_context:
                                all_context_parts.append(
                                    f"Medical guidelines and regulations:\n{rag_context}"
                                )
                                logger.info(
                                    f"RAG context added to chat for microsite {microsite.slug}"
                                )

                            if all_context_parts:
                                full_context = "\n\n".join(all_context_parts)
                                microsite_entry = f"Microsite context:\n{full_context}"
                                # Store via the transactional helper: this
                                # background task races the main turn's
                                # persist, and a read-modify-asave here was a
                                # classic lost-update writer. The helper also
                                # keeps the placeholder-safety rule (own entry
                                # rather than appending to a placeholder tag).
                                await apersist_microsite_context(chat, microsite_entry)

                                logger.info(
                                    f"Stored microsite context for {microsite.slug} in chat"
                                )

                            # Send completion message if PubMed search was performed
                            if microsite.pubmed_search_terms:
                                await self.send_status_message(
                                    "Medical literature search complete"
                                )
                        except Exception as e:
                            logger.opt(exception=True).warning(
                                f"Error loading microsite context: {e}"
                            )

                    await fire_and_forget_in_new_threadpool(fetch_microsite_context())
                else:
                    logger.warning(
                        f"Could not find microsite for slug {chat.microsite_slug}"
                    )
            except Exception as e:
                logger.warning(f"Error loading microsite for chat {chat.id}: {e}")

        # Check for policy document analysis request
        if _detect_policy_analysis_request(user_message):
            await self._handle_policy_analysis(chat, user_message)
            return

        # Handle chat ↔ appeal/prior auth linking if requested

        link_message = None
        user_facing_message = None
        # Note: We intentionally do NOT send the link message to the LLM/model immediately.
        # This allows the user to drive the next step, and avoids confusing the model with system state changes.
        # Also we require their is a pro user to enable linking.
        if iterate_on_appeal and user:
            await self.send_status_message("Linking appeal into chat")
            appeal = await database_sync_to_async(Appeal.get_optional_for_user)(
                user, id=iterate_on_appeal
            )
            if not appeal:
                await self.send_error_message(
                    "Appeal not found, or you do not have permission to access it."
                )
                return
            appeal_details = await database_sync_to_async(appeal.details)()
            if appeal.chat_id != chat.id:
                appeal.chat = chat
                await appeal.asave()
                link_message = f"Linked this chat to Appeal #{appeal.id} -- help the user iterate on {appeal_details}"
                user_facing_message = "I've linked this chat to your appeal. How can I help you iterate on it?"
            else:
                link_message = f"This chat is already linked to Appeal #{appeal.id} -- the current appeal text is {appeal_details}, help the user iterate on it"
                user_facing_message = "This chat is already linked to your appeal. How can I help you with it?"
        if iterate_on_prior_auth and user:
            await self.send_status_message(
                "Linking prior authorization request into chat"
            )
            prior_auth = await database_sync_to_async(
                PriorAuthRequest.get_optional_for_user
            )(user, id=iterate_on_prior_auth)
            if not prior_auth:
                await self.send_error_message(
                    "Prior Auth Request not found or you do not have permission to access it."
                )
                return
            # PriorAuthRequest.details() only reads local columns (unlike
            # Appeal.details(), which walks relations) — no bridge needed.
            prior_auth_details = prior_auth.details()
            if prior_auth.chat_id != chat.id:
                prior_auth.chat = chat
                await prior_auth.asave()
                link_message = f"Linked this chat to Prior Auth Request #{prior_auth.id}, details are {prior_auth_details}"
                user_facing_message = "I've linked this chat to your prior authorization request. How can I help you with it?"
            else:
                link_message = f"This chat is already linked to Prior Auth Request #{prior_auth.id}, current details are {prior_auth_details}"
                user_facing_message = "This chat is already linked to your prior authorization request. How can I help you with it?"
        if link_message and user_facing_message:
            await asyncio.sleep(0.01)
            # Transactional merge against the fresh row (see apersist_chat_turn)
            self.chat = chat = await apersist_chat_turn(
                chat,
                new_messages=[
                    {"role": "user", "content": link_message},
                    {"role": "assistant", "content": user_facing_message},
                ],
            )
            await self.send_message_to_client(user_facing_message)
            return

        # Get primary and fallback models based on user preference
        primary_models, fallback_models = ml_router.get_chat_backends_with_fallback(
            use_external=self.use_external_models
        )
        if not primary_models:
            await self.send_error_message(
                "Sorry, no language models are currently available."
            )
            return

        # Refresh from the DB so background-task updates (summaries, microsite
        # context) are visible for this LLM call. A full refetch is safe here:
        # every path that mutated chat state above either persisted through
        # the transactional helper (and rebound self.chat) or returned early.
        try:
            self.chat = chat = await OngoingChat.objects.aget(id=chat.id)
        except OngoingChat.DoesNotExist:
            logger.warning(f"Chat {chat.id} vanished before LLM call; keeping copy")

        current_llm_context = None
        if chat.summary_for_next_call and len(chat.summary_for_next_call) > 0:
            current_llm_context = chat.summary_for_next_call[-1]
            # Include the previous context summary so the model has continuity
            # across summarization boundaries (e.g. microsite context, PubMed).
            if len(chat.summary_for_next_call) > 1:
                prev_summary = chat.summary_for_next_call[-2]
                if prev_summary and str(prev_summary).strip():
                    current_llm_context = (
                        f"Previous context summary:\n{prev_summary}\n\n"
                        f"Most recent context summary:\n{current_llm_context}"
                    )

        # Build message variants: the original/primary path plus lower-scored
        # long-message and weird-Unicode alternatives. A normal short message
        # yields a single primary_original variant, so the wrapped input, stored
        # history, and scoring stay identical to sending the raw message.
        message_variants = prepare_user_message_variants(
            user_message,
            is_document=is_document,
            document_name=document_name,
        )

        # Long paste detected (and not already an explicit upload): preserve the
        # full original in document storage and switch history/scoring to a
        # compact marker, so we neither bloat chat_history nor fan the huge text
        # out to every backend.
        long_paste_variant = next(
            (v for v in message_variants if v.metadata.get("store_full_text")),
            None,
        )
        if long_paste_variant is not None and not is_document:
            char_count = long_paste_variant.metadata.get(
                "char_count", len(user_message)
            )
            doc_name = long_paste_variant.metadata.get(
                "document_name",
                f"pasted_message_{int(timezone.now().timestamp())}.txt",
            )
            logger.info(
                f"Long pasted message in chat {chat.id}: storing {char_count} chars "
                f"as {doc_name} for reference"
            )
            denial_context = await self._denial_context_for_chat(chat)
            await process_uploaded_document(
                chat=chat,
                document_name=doc_name,
                full_text=user_message,
                denial_context=denial_context,
            )
            await self.send_status_message(
                f"Long message received ({char_count:,} chars). "
                f"Stored for reference and analyzing in background..."
            )
            # From here on, history + scoring use the compact marker.
            user_message = long_paste_variant.display_text or user_message

        # Determine how to wrap a variant's text for the LLM (intro template on
        # new chats, delete-data instruction on ongoing turns), then apply it to
        # every variant. The trial banner is a one-time side effect for new chats.
        if is_new_chat:
            if self.is_trial_professional:
                trial_banner = {
                    "role": "system",
                    "content": "⚠️ You're using a free trial version. Responses may be slower, and features like linked appeals and prior auths require a full professional account.\n\nWant full access? [Create a free account →](/signup)",
                    "timestamp": timezone.now().isoformat(),
                }
                # We don't add the trial banner to the history since it needs to
                # go user -> agent -> user.
                await self.send_json_message_func(trial_banner)

            user_info_str = await self._get_user_info()
            template = get_intro_template(self.chat.chat_type)

            def wrap_for_llm(text: str) -> str:
                return template.format(user_info=user_info_str, message=text)

        else:

            def wrap_for_llm(text: str) -> str:
                # Re-inject the delete-data handoff instruction on every ongoing
                # turn. The intro template (which contains it) only fires for new
                # chats, so without this the sentinel fallback would silently
                # stop working past the first message.
                return f"{DELETE_DATA_INSTRUCTION}\n\n{text}"

        llm_message_variants = [
            replace(v, text_for_llm=wrap_for_llm(v.text_for_llm))
            for v in message_variants
        ]
        # Prefer the primary variant for the single-message fields (recursion,
        # tool calls); fall back to the best alternative for long pastes.
        primary_variant = next(
            (v for v in llm_message_variants if v.kind == "primary_original"),
            llm_message_variants[0],
        )
        llm_input_message = primary_variant.text_for_llm

        # Prepare history for LLM using the context manager
        # This handles truncation, summarization, and full history preservation
        (
            history_for_llm,
            full_history_for_llm,
            summarized_context,
        ) = await prepare_history_for_llm(
            chat_history=chat.chat_history,
            existing_summary=current_llm_context,
            summarize_callback=self.send_status_message,
        )

        # Summary entries added this turn. Persistence appends these to the
        # FRESH row inside a transaction (apersist_chat_turn), so we track
        # them separately from the in-memory list, which may be stale.
        turn_summaries: List[Optional[str]] = []

        # Store the updated summary if it changed
        if should_store_summary(chat.summary_for_next_call, summarized_context):
            if not chat.summary_for_next_call:
                chat.summary_for_next_call = []
            chat.summary_for_next_call.append(summarized_context)
            turn_summaries.append(summarized_context)
            logger.info(f"Stored updated summary for chat {chat.id}")

        final_response_text = None
        final_context_part = None

        # Inject uploaded document context into the LLM call. Guarded: a
        # failure searching stored documents must degrade to "no doc context"
        # rather than kill the whole turn.
        doc_context_str = None
        try:
            doc_context_str = await get_document_context_for_message(
                chat.id, user_message
            )
        except Exception as e:
            logger.warning(f"Skipping document context for chat {chat.id}: {e}")
        if doc_context_str:
            summarized_context = (
                f"{doc_context_str}\n\n{summarized_context}"
                if summarized_context
                else doc_context_str
            )

        if self.is_trial_professional:
            await asyncio.sleep(0.5)  # Half a second delay for trial users.

        # Note: Medicaid queries are now handled through the tool calling system
        # The model can call the medicaid_info tool when needed using the format:
        # **medicaid_info {"state": "StateName", "topic": "", "limit": 5}**
        # (The double asterisks around the entire tool call are required)
        # USPSTF preventive recommendations: **uspstf_lookup {"query": "...", "grade": "A"}**

        # Overall wall-clock budget for this turn's LLM + tool work, plus a
        # heartbeat so the user (and any idle-reaping proxy between us) sees
        # traffic while a long turn is still working. Without the budget a
        # wedged backend chain could hold the turn open indefinitely with the
        # client showing a spinner forever.
        turn_budget = _env_float("FHI_CHAT_TURN_BUDGET", 150.0)
        heartbeat_task = asyncio.create_task(self._turn_heartbeat())
        try:
            response_text, context_part = await asyncio.wait_for(
                self._call_llm_with_actions(
                    primary_models,
                    llm_input_message,
                    summarized_context,
                    history_for_llm,
                    is_logged_in=(self.user is not None and self.user.is_authenticated),
                    is_professional=self.is_professional or self.is_trial_professional,
                    fallback_backends=fallback_models if fallback_models else None,
                    full_history=full_history_for_llm,  # Also try with full history if model supports it
                    user_message_for_scoring=user_message,
                    message_variants=llm_message_variants,
                ),
                timeout=turn_budget,
            )

            if response_text and response_text.strip():
                cleaned = remove_repeated_blocks(response_text.strip())
                cleaned = remove_repeated_sentences(cleaned) or cleaned
                if llm_requested_delete_handoff(cleaned):
                    logger.info(
                        f"LLM emitted delete-data sentinel in chat {chat.id}, swapping in canned response"
                    )
                    cleaned = DELETE_DATA_RESPONSE
                final_response_text = cleaned
                final_context_part = context_part
        except asyncio.TimeoutError:
            logger.error(
                f"Chat turn exceeded its {turn_budget:.0f}s budget for chat "
                f"{chat.id}; giving up on this turn"
            )
            record_chat_turn("timeout")
        except Exception as e:
            logger.opt(exception=True).error(
                f"Chat generation failed for chat {chat.id}: {e}"
            )
            logger.debug(f"Models tried for failed chat {chat.id}: {primary_models}")
        finally:
            heartbeat_task.cancel()

        if final_response_text:
            if should_store_summary(chat.summary_for_next_call, final_context_part):
                if not chat.summary_for_next_call:
                    chat.summary_for_next_call = []
                chat.summary_for_next_call.append(final_context_part)
                turn_summaries.append(final_context_part)

            # If model didn't return a context summary, store a placeholder and
            # fire a background task to generate one
            background_summary_task = None
            if final_response_text and not final_context_part:
                if not chat.summary_for_next_call:
                    chat.summary_for_next_call = []
                # The counter only needs to make the placeholder tag unique;
                # +2 accounts for the user/assistant pair persisted below.
                history_len = (len(chat.chat_history) if chat.chat_history else 0) + 2
                placeholder = make_placeholder(history_len)
                chat.summary_for_next_call.append(placeholder)
                turn_summaries.append(placeholder)
                background_summary_task = background_generate_summary(
                    chat.id, placeholder
                )

            # Persist against the fresh row (transactional re-read + merge) so
            # concurrent writers -- background summaries, the microsite fetch,
            # a second tab -- can't be clobbered by this stale in-memory
            # object. Duplicate detection and consecutive-user-message merging
            # happen in the helper, against the fresh tail. Rebind to the
            # merged row so later turns and replays see the true state.
            self.chat = chat = await apersist_chat_turn(
                chat,
                new_messages=[
                    {"role": "user", "content": user_message},
                    {"role": "assistant", "content": final_response_text},
                ],
                new_summaries=turn_summaries,
            )

            # Launch background summary after save so the task can read the latest history
            if background_summary_task is not None:
                await fire_and_forget_in_new_threadpool(background_summary_task)
            record_chat_turn("ok")
            await self.send_message_to_client(final_response_text)
        else:
            # The turn failed after the user already committed their message:
            # persist it anyway so a reconnect/replay doesn't erase what they
            # typed (previously the whole turn was dropped on failure).
            try:
                self.chat = chat = await apersist_chat_turn(
                    chat,
                    new_messages=[{"role": "user", "content": user_message}],
                    new_summaries=turn_summaries,
                )
            except Exception:
                logger.opt(exception=True).error(
                    f"Could not persist user message for failed turn in chat {chat.id}"
                )
            # Provide more helpful error message based on context
            err_msg = (
                "Sorry, all available models (including backup models) are currently "
                "experiencing issues. Please try again in a few moments. "
                "If the problem persists, try refreshing the page or starting a new chat."
            )
            if not self.use_external_models:
                err_msg = (
                    "Sorry, our primary models are currently busy or experiencing issues. "
                    "You can enable 'Use backup models' in settings to allow fallback to "
                    "additional model providers when our primary models are unavailable."
                )
            logger.error(
                f"Failed to generate response for user_message: '{user_message}' in chat {chat.id} "
                f"after trying all models. use_external_models={self.use_external_models}"
            )
            record_chat_turn("failed")
            capture_reliability_event(
                "chat_turn_total_failure",
                chat_id=str(chat.id),
                use_external_models=self.use_external_models,
                message_chars=len(user_message or ""),
            )
            await self.send_error_message(err_msg)

    async def replay_chat_history(self):
        """Sends the existing chat history to the client."""
        chat = self.chat
        history: Optional[List[Dict[str, Any]]] = chat.chat_history
        await self.send_json_message_func({"messages": chat.chat_history})

    async def _handle_policy_analysis(
        self, chat: OngoingChat, user_message: str
    ) -> None:
        """
        Handle policy document analysis request.
        Looks for associated policy documents and triggers chunked parallel analysis.
        Always sends a response (success or error) so the caller can return immediately.
        """
        try:
            policy_doc: Optional[PolicyDocument] = None
            # PolicyDocument rows are keyed by the DJANGO session key (the
            # upload happens in a regular HTTP view), while chat.session_key
            # is a client-generated localStorage string -- the two never
            # match for anonymous users, which left this handoff dead. Try
            # the server session key first, then the chat's own key.
            candidate_keys = [
                k for k in (self.server_session_key, chat.session_key) if k
            ]

            from django.contrib.sessions.backends.db import SessionStore

            def _get_session_doc_id(sk: str) -> Optional[str]:
                session = SessionStore(session_key=sk)
                return session.get("policy_document_id")

            for session_key in candidate_keys:
                doc_id = await database_sync_to_async(_get_session_doc_id)(session_key)
                if doc_id:
                    policy_doc = await PolicyDocument.objects.filter(
                        id=doc_id,
                        session_key=session_key,
                    ).afirst()
                if not policy_doc:
                    policy_doc = (
                        await PolicyDocument.objects.filter(session_key=session_key)
                        .order_by("-created_at")
                        .afirst()
                    )
                    logger.debug(
                        f"Policy doc session_key fallback: doc_id={policy_doc.id if policy_doc else None}"
                    )
                if policy_doc:
                    break

            if not policy_doc:
                logger.debug("No policy document found for session")
                await self.send_error_message(
                    "I couldn't find the uploaded policy document for this chat. "
                    "Please re-upload it from the Understand My Policy page."
                )
                return

            logger.info(f"Analyzing policy document {policy_doc.id}")
            await self.send_status_message(
                f"Analyzing your {policy_doc.get_document_type_display()} document..."
            )

            # Extract user's specific question from the message if present
            user_question = None
            question_match = re.search(
                r"My question:\s*(.+?)(?:\n\s*\n|(?:\n)?Please analyze\b|$)",
                user_message,
                re.DOTALL,
            )
            if question_match:
                user_question = re.sub(r"\s+", " ", question_match.group(1)).strip()

            # Progress callback for countdown display
            async def _progress_callback(remaining: int, total: int) -> None:
                if total == 0:
                    await self.send_status_message("Finalizing analysis...")
                elif total == 1 and remaining == 1:
                    await self.send_status_message(
                        "Combining findings into final analysis..."
                    )
                elif remaining == total:
                    await self.send_status_message(
                        f"Launching {total} analysis agents..."
                    )
                else:
                    await self.send_status_message(
                        f"Analyzing policy — {remaining} of {total} agents remaining..."
                    )

            # Get or create analysis with progress updates
            analysis = await MLPolicyDocHelper.get_or_create_analysis(
                policy_doc, user_question, progress_callback=_progress_callback
            )

            if analysis:
                formatted_analysis = MLPolicyDocHelper.format_analysis_for_chat(
                    analysis
                )

                # Persist turn + analysis context transactionally against the
                # fresh row (replaces the old refetch-modify-asave, which
                # could still clobber a writer landing between the two).
                self.chat = chat = await apersist_chat_turn(
                    chat,
                    new_messages=[
                        {"role": "user", "content": user_message},
                        {"role": "assistant", "content": formatted_analysis},
                    ],
                    new_summaries=[
                        f"Policy document analysis ({policy_doc.get_document_type_display()}, id={policy_doc.id}):\n{formatted_analysis[:4000]}"
                    ],
                )

                await self.send_status_message("Policy analysis complete!")
                await self.send_message_to_client(formatted_analysis)
            else:
                await self.send_error_message(
                    "Could not analyze the policy document. Please try again or contact support."
                )

        except Exception as e:
            logger.opt(exception=True).warning(
                f"Error handling policy analysis for chat {chat.id}: {e}"
            )
            await self.send_error_message(
                "There was an error analyzing your policy document. "
                "Please try again or continue with your question."
            )
