# Generated by Django 5.1.5 on 2025-03-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0032_alter_userdomain_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdomain",
            name="stripe_customer_id",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
