# Generated by Django 5.1.6 on 2025-03-14 21:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0032_alter_userdomain_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resettoken",
            name="token",
            field=models.CharField(
                default=uuid.uuid4(),
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4(),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="verificationtoken",
            name="token",
            field=models.CharField(
                default=uuid.uuid4(),
                max_length=255,
            ),
        ),
    ]
