# Generated by Django 5.1.5 on 2025-03-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0033_userdomain_stripe_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionaluser",
            name="display_name",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="usercontactinfo",
            name="address1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="usercontactinfo",
            name="address2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="usercontactinfo",
            name="city",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="usercontactinfo",
            name="phone_number",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="usercontactinfo",
            name="state",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="usercontactinfo",
            name="zipcode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="business_name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="display_name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
