# Generated by Django 5.1.5 on 2025-03-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0034_alter_professionaluser_display_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdomain",
            name="pending",
            field=models.BooleanField(default=False),
        ),
    ]
