# Generated by Django 5.1.5 on 2025-03-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0035_userdomain_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdomain",
            name="beta",
            field=models.BooleanField(default=False),
        ),
    ]
