# Generated by Django 5.1.5 on 2025-03-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0036_userdomain_beta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdomain",
            name="address1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="city",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="cover_template_string",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="default_procedure",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="state",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
