# Generated by Django 5.1.5 on 2025-04-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0037_alter_userdomain_address1_alter_userdomain_city_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="professionaldomainrelation",
            old_name="active",
            new_name="active_domain_relation",
        ),
        migrations.RenameField(
            model_name="professionaldomainrelation",
            old_name="pending",
            new_name="pending_domain_relation",
        ),
    ]
