# Generated by Django 5.1.5 on 2025-04-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fhi_users",
            "0038_rename_active_professionaldomainrelation_active_domain_relation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="professionaldomainrelation",
            name="professional_type",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
