# Generated by Django 5.1.5 on 2025-04-12 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0039_alter_professionaldomainrelation_professional_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingProStripeCheckoutSession",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("stripe_session_id", models.CharField(max_length=255, unique=True)),
                (
                    "django_session_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email", models.EmailField(max_length=254)),
                ("visible_phone_number", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fhi_users.userdomain",
                    ),
                ),
                (
                    "professional_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fhi_users.professionaluser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stripe Checkout Session",
                "verbose_name_plural": "Stripe Checkout Sessions",
                "indexes": [
                    models.Index(fields=["email"], name="fhi_users_p_email_ec97fe_idx"),
                    models.Index(
                        fields=["stripe_session_id"],
                        name="fhi_users_p_stripe__21bd8a_idx",
                    ),
                    models.Index(
                        fields=["django_session_id"],
                        name="fhi_users_p_django__f8e466_idx",
                    ),
                ],
            },
        ),
    ]
