# Generated by Django 5.1.5 on 2025-05-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0040_pendingprostripecheckoutsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionaluser",
            name="credentials",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
