# Generated by Django 5.2.9 on 2025-12-17 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0041_professionaluser_credentials"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIAccessLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("consumer", "consumer"),
                            ("professional", "professional"),
                            ("anonymous", "anonymous"),
                        ],
                        default="anonymous",
                        max_length=20,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, null=True
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "login_success"),
                            ("login_failed", "login_failed"),
                            ("logout", "logout"),
                            ("password_changed", "password_changed"),
                            ("password_reset_requested", "password_reset_requested"),
                            ("password_reset_completed", "password_reset_completed"),
                            ("email_verified", "email_verified"),
                            ("mfa_enabled", "mfa_enabled"),
                            ("mfa_disabled", "mfa_disabled"),
                            ("account_created", "account_created"),
                            ("account_activated", "account_activated"),
                            ("account_deactivated", "account_deactivated"),
                            ("account_deleted", "account_deleted"),
                            ("professional_created", "professional_created"),
                            ("professional_accepted", "professional_accepted"),
                            ("professional_rejected", "professional_rejected"),
                            ("professional_suspended", "professional_suspended"),
                            ("admin_granted", "admin_granted"),
                            ("admin_revoked", "admin_revoked"),
                            ("domain_joined", "domain_joined"),
                            ("domain_left", "domain_left"),
                            ("api_access", "api_access"),
                            ("bulk_export", "bulk_export"),
                            ("search_performed", "search_performed"),
                            ("permission_denied", "permission_denied"),
                            ("rate_limited", "rate_limited"),
                            ("suspicious_activity", "suspicious_activity"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "asn_number",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("asn_org", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "network_type",
                    models.CharField(
                        choices=[
                            ("residential", "residential"),
                            ("business", "business"),
                            ("datacenter", "datacenter"),
                            ("vpn", "vpn"),
                            ("proxy", "proxy"),
                            ("tor", "tor"),
                            ("mobile", "mobile"),
                            ("education", "education"),
                            ("government", "government"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=2, null=True
                    ),
                ),
                (
                    "state_region",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("user_agent_full", models.TextField(blank=True, null=True)),
                (
                    "user_agent_browser",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "user_agent_os",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_mobile", models.BooleanField(blank=True, null=True)),
                ("is_bot", models.BooleanField(default=False)),
                (
                    "request_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "request_method",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "http_referer",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("details", models.JSONField(blank=True, null=True)),
                ("endpoint", models.CharField(db_index=True, max_length=255)),
                (
                    "http_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "resource_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("resource_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "search_query",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_audit_logs",
                        to="fhi_users.userdomain",
                    ),
                ),
                (
                    "professional_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_audit_logs",
                        to="fhi_users.professionaluser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Access Log",
                "verbose_name_plural": "API Access Logs",
                "indexes": [
                    models.Index(
                        fields=["timestamp", "event_type"],
                        name="fhi_users_a_timesta_540f38_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="fhi_users_a_user_id_d2f065_idx",
                    ),
                    models.Index(
                        fields=["asn_number", "timestamp"],
                        name="fhi_users_a_asn_num_a3039d_idx",
                    ),
                    models.Index(
                        fields=["network_type", "timestamp"],
                        name="fhi_users_a_network_2f7195_idx",
                    ),
                    models.Index(
                        fields=["endpoint", "timestamp"],
                        name="fhi_users_a_endpoin_05c39a_idx",
                    ),
                    models.Index(
                        fields=["domain", "endpoint", "timestamp"],
                        name="fhi_users_a_domain__002fc0_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "timestamp"],
                        name="fhi_users_a_resourc_5c8848_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuthAuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("consumer", "consumer"),
                            ("professional", "professional"),
                            ("anonymous", "anonymous"),
                        ],
                        default="anonymous",
                        max_length=20,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, null=True
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "login_success"),
                            ("login_failed", "login_failed"),
                            ("logout", "logout"),
                            ("password_changed", "password_changed"),
                            ("password_reset_requested", "password_reset_requested"),
                            ("password_reset_completed", "password_reset_completed"),
                            ("email_verified", "email_verified"),
                            ("mfa_enabled", "mfa_enabled"),
                            ("mfa_disabled", "mfa_disabled"),
                            ("account_created", "account_created"),
                            ("account_activated", "account_activated"),
                            ("account_deactivated", "account_deactivated"),
                            ("account_deleted", "account_deleted"),
                            ("professional_created", "professional_created"),
                            ("professional_accepted", "professional_accepted"),
                            ("professional_rejected", "professional_rejected"),
                            ("professional_suspended", "professional_suspended"),
                            ("admin_granted", "admin_granted"),
                            ("admin_revoked", "admin_revoked"),
                            ("domain_joined", "domain_joined"),
                            ("domain_left", "domain_left"),
                            ("api_access", "api_access"),
                            ("bulk_export", "bulk_export"),
                            ("search_performed", "search_performed"),
                            ("permission_denied", "permission_denied"),
                            ("rate_limited", "rate_limited"),
                            ("suspicious_activity", "suspicious_activity"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "asn_number",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("asn_org", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "network_type",
                    models.CharField(
                        choices=[
                            ("residential", "residential"),
                            ("business", "business"),
                            ("datacenter", "datacenter"),
                            ("vpn", "vpn"),
                            ("proxy", "proxy"),
                            ("tor", "tor"),
                            ("mobile", "mobile"),
                            ("education", "education"),
                            ("government", "government"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=2, null=True
                    ),
                ),
                (
                    "state_region",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("user_agent_full", models.TextField(blank=True, null=True)),
                (
                    "user_agent_browser",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "user_agent_os",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_mobile", models.BooleanField(blank=True, null=True)),
                ("is_bot", models.BooleanField(default=False)),
                (
                    "request_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "request_method",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "http_referer",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "attempted_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "failure_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_audit_logs",
                        to="fhi_users.userdomain",
                    ),
                ),
                (
                    "professional_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_audit_logs",
                        to="fhi_users.professionaluser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Authentication Audit Log",
                "verbose_name_plural": "Authentication Audit Logs",
                "indexes": [
                    models.Index(
                        fields=["timestamp", "event_type"],
                        name="fhi_users_a_timesta_188b8f_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="fhi_users_a_user_id_5ff9bf_idx",
                    ),
                    models.Index(
                        fields=["asn_number", "timestamp"],
                        name="fhi_users_a_asn_num_7f243c_idx",
                    ),
                    models.Index(
                        fields=["network_type", "timestamp"],
                        name="fhi_users_a_network_ea690a_idx",
                    ),
                    models.Index(
                        fields=["attempted_email", "timestamp"],
                        name="fhi_users_a_attempt_55d4af_idx",
                    ),
                    models.Index(
                        fields=["domain", "timestamp"],
                        name="fhi_users_a_domain__e4024a_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="fhi_users_a_ip_addr_6d57d0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProfessionalActivityLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("consumer", "consumer"),
                            ("professional", "professional"),
                            ("anonymous", "anonymous"),
                        ],
                        default="anonymous",
                        max_length=20,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, null=True
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "login_success"),
                            ("login_failed", "login_failed"),
                            ("logout", "logout"),
                            ("password_changed", "password_changed"),
                            ("password_reset_requested", "password_reset_requested"),
                            ("password_reset_completed", "password_reset_completed"),
                            ("email_verified", "email_verified"),
                            ("mfa_enabled", "mfa_enabled"),
                            ("mfa_disabled", "mfa_disabled"),
                            ("account_created", "account_created"),
                            ("account_activated", "account_activated"),
                            ("account_deactivated", "account_deactivated"),
                            ("account_deleted", "account_deleted"),
                            ("professional_created", "professional_created"),
                            ("professional_accepted", "professional_accepted"),
                            ("professional_rejected", "professional_rejected"),
                            ("professional_suspended", "professional_suspended"),
                            ("admin_granted", "admin_granted"),
                            ("admin_revoked", "admin_revoked"),
                            ("domain_joined", "domain_joined"),
                            ("domain_left", "domain_left"),
                            ("api_access", "api_access"),
                            ("bulk_export", "bulk_export"),
                            ("search_performed", "search_performed"),
                            ("permission_denied", "permission_denied"),
                            ("rate_limited", "rate_limited"),
                            ("suspicious_activity", "suspicious_activity"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "asn_number",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("asn_org", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "network_type",
                    models.CharField(
                        choices=[
                            ("residential", "residential"),
                            ("business", "business"),
                            ("datacenter", "datacenter"),
                            ("vpn", "vpn"),
                            ("proxy", "proxy"),
                            ("tor", "tor"),
                            ("mobile", "mobile"),
                            ("education", "education"),
                            ("government", "government"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=2, null=True
                    ),
                ),
                (
                    "state_region",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("user_agent_full", models.TextField(blank=True, null=True)),
                (
                    "user_agent_browser",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "user_agent_os",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_mobile", models.BooleanField(blank=True, null=True)),
                ("is_bot", models.BooleanField(default=False)),
                (
                    "request_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "request_method",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "http_referer",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("details", models.JSONField(blank=True, null=True)),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_audit_logs",
                        to="fhi_users.userdomain",
                    ),
                ),
                (
                    "performed_by_professional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_by_activity_logs",
                        to="fhi_users.professionaluser",
                    ),
                ),
                (
                    "performed_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "professional_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_audit_logs",
                        to="fhi_users.professionaluser",
                    ),
                ),
                (
                    "target_professional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_activity_logs",
                        to="fhi_users.professionaluser",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Professional Activity Log",
                "verbose_name_plural": "Professional Activity Logs",
                "indexes": [
                    models.Index(
                        fields=["timestamp", "event_type"],
                        name="fhi_users_p_timesta_43237a_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="fhi_users_p_user_id_1ace62_idx",
                    ),
                    models.Index(
                        fields=["asn_number", "timestamp"],
                        name="fhi_users_p_asn_num_169625_idx",
                    ),
                    models.Index(
                        fields=["network_type", "timestamp"],
                        name="fhi_users_p_network_c54ff6_idx",
                    ),
                    models.Index(
                        fields=["professional_user", "timestamp"],
                        name="fhi_users_p_profess_ea9933_idx",
                    ),
                    models.Index(
                        fields=["performed_by_user", "timestamp"],
                        name="fhi_users_p_perform_9dcf2f_idx",
                    ),
                    models.Index(
                        fields=["target_user", "timestamp"],
                        name="fhi_users_p_target__3d66bf_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SuspiciousActivityLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("trigger_type", models.CharField(db_index=True, max_length=50)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("asn_number", models.PositiveIntegerField(blank=True, null=True)),
                ("asn_org", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField()),
                ("evidence", models.JSONField(blank=True, null=True)),
                ("reviewed", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspicious_activity_logs",
                        to="fhi_users.userdomain",
                    ),
                ),
                (
                    "professional_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspicious_activity_logs",
                        to="fhi_users.professionaluser",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_suspicious_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspicious_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Suspicious Activity Log",
                "verbose_name_plural": "Suspicious Activity Logs",
                "indexes": [
                    models.Index(
                        fields=["timestamp", "severity"],
                        name="fhi_users_s_timesta_92b76d_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="fhi_users_s_user_id_77c71b_idx",
                    ),
                    models.Index(
                        fields=["trigger_type", "timestamp"],
                        name="fhi_users_s_trigger_4e2f31_idx",
                    ),
                    models.Index(
                        fields=["reviewed", "severity"],
                        name="fhi_users_s_reviewe_34dd0e_idx",
                    ),
                ],
            },
        ),
    ]
