# Generated by Django 5.2.9 on 2025-12-22 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fhi_users", "0042_auditlog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="fhi_users_a_user_id_f77f8c_idx",
            old_name="fhi_users_a_user_id_abc123_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="fhi_users_a_event_t_bb2a8d_idx",
            old_name="fhi_users_a_event_t_def456_idx",
        ),
    ]
