# Generated by Django 5.2.9 on 2025-12-17 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("fhi_users", "0042_audit_logs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectActivityContext",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("object_id", models.CharField(db_index=True, max_length=100)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("view", "Viewed"),
                            ("delete", "Deleted"),
                            ("export", "Exported"),
                        ],
                        default="create",
                        max_length=20,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("consumer", "consumer"),
                            ("professional", "professional"),
                            ("anonymous", "anonymous"),
                        ],
                        default="anonymous",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("asn_number", models.PositiveIntegerField(blank=True, null=True)),
                ("asn_org", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "network_type",
                    models.CharField(
                        choices=[
                            ("residential", "residential"),
                            ("business", "business"),
                            ("datacenter", "datacenter"),
                            ("vpn", "vpn"),
                            ("proxy", "proxy"),
                            ("tor", "tor"),
                            ("mobile", "mobile"),
                            ("education", "education"),
                            ("government", "government"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("country_code", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "state_region",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("user_agent_full", models.TextField(blank=True, null=True)),
                (
                    "user_agent_browser",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "user_agent_os",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_mobile", models.BooleanField(blank=True, null=True)),
                ("is_bot", models.BooleanField(default=False)),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_contexts",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="object_activity_contexts",
                        to="fhi_users.userdomain",
                    ),
                ),
                (
                    "professional_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="object_activity_contexts",
                        to="fhi_users.professionaluser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="object_activity_contexts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Object Activity Context",
                "verbose_name_plural": "Object Activity Contexts",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="fhi_users_o_content_a66fc1_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="fhi_users_o_user_id_a17a95_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="fhi_users_o_timesta_4207af_idx"
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="fhi_users_o_action_323d84_idx",
                    ),
                ],
            },
        ),
    ]
