name: Run CI

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - "**"

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install tesseract ocr
        run: sudo apt-get install -y tesseract-ocr

      - name: Install dependencies
        run: pip install tox tox-gh-actions

      - name: Check npm build
        run:
          cd fighthealthinsurance/static/js; npm i; npm run build

      - name: Check style
        run:
          tox -e black

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ['310']
        django: ['41', '42']
        include:
          - python: '310'
            django: '41'

    name: Run the test suite (Python ${{ matrix.python }}, Django ${{ matrix.django }})
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install tesseract ocr
        run: sudo apt-get install -y tesseract-ocr

      - name: Install dependencies
        run: pip install tox tox-gh-actions

      - name: Check npm build
        run:
          cd fighthealthinsurance/static/js; npm i; npm run build

      - name: Run tests
        run: tox -e py${{ matrix.python }}-django${{ matrix.django }}
        env:
          FARTS: "farts"
          GOOGLE_CLIENT_SECRETS_TEXT: ${{ secrets.GOOGLE_CLIENT_SECRETS_TEXT }}
