name: Run CI

on:
  push:
    branches:
      - '**'
    pull_request:
      paths:
        - '**'
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ['3.10']
        django: ['4.1', '4.2']
        include:
          - python: '3.10'
            django: '4.1'
     
    name: Run the test suite (Python ${{ matrix.python }}, Django ${{ matrix.django }})
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install tesseract ocr
        run: sudo apt-get install -y tesseract-ocr

      - name: Install dependencies
        run: pip install tox tox-gh-actions

      - name: Check npm build
        run:
          cd fighthealthinsurance/static/js; npm i; npm run build

      - name: Run tests
        run: tox
        env:
          DJANGO: ${{ matrix.django }}
          FARTS: "farts"
          GOOGLE_CLIENT_SECRETS_TEXT: ${{ secrets.GOOGLE_CLIENT_SECRETS_TEXT }}
