name: Run CI

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - "**"

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv tool install tox

      - name: Check style
        run:
          tox -e black

  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv tool install tox

      - name: Check types
        run:
          tox -e mypy

  npm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3

      - name: Check npm build
        run:
          cd fighthealthinsurance/static/js && npm i && npm run build && npm cache clean --force


  tests-sync:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ['310']
        django: ['50']
        include:
          - python: '310'
            django: '50'

    name: Run the sync test suite (Python ${{ matrix.python }}, Django ${{ matrix.django }})
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install system level packages
        run: sudo apt-get update && sudo apt-get install -y tesseract-ocr texlive && sudo apt-get clean

      - uses: actions/setup-python@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv tool install tox

      - name: Install
        uses: pandoc/actions/setup@v1
        with:
          version: 2.19

      - name: Build npm js (needed for the e2e tests in django)
        run:
          cd fighthealthinsurance/static/js && npm i && npm run build && npm cache clean --force

      - name: Run tests
        run: tox -e py${{ matrix.python }}-django${{ matrix.django }}-sync
        env:
          FARTS: "farts"
          GOOGLE_CLIENT_SECRETS_TEXT: ${{ secrets.GOOGLE_CLIENT_SECRETS_TEXT }}
          STRIPE_TEST_SECRET_KEY: ${{ secrets.STRIPE_TEST_SECRET_KEY }}

  tests-async:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ['310']
        django: ['50']
        include:
          - python: '310'
            django: '50'

    name: Run the async test suite (Python ${{ matrix.python }}, Django ${{ matrix.django }})
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install system level packages
        run: sudo apt-get update && sudo apt-get install -y tesseract-ocr texlive && sudo apt-get clean

      - uses: actions/setup-python@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv tool install tox

      - name: Install
        uses: pandoc/actions/setup@v1
        with:
          version: 2.19

      - name: Build npm js (needed for the e2e tests in django)
        run:
          cd fighthealthinsurance/static/js && npm i && npm run build && npm cache clean --force

      - name: Setup DB (long story)
        run: uv venv && source .venv/bin/activate && uv pip install -r requirements.txt && ./manage.py makemigrations && ./manage.py migrate && ENVIRONMENT=Test ./manage.py migrate

      - name: Run tests
        run: ENVIRONMENT=Test tox -e py${{ matrix.python }}-django${{ matrix.django }}-async
        env:
          FARTS: "farts"
          GOOGLE_CLIENT_SECRETS_TEXT: ${{ secrets.GOOGLE_CLIENT_SECRETS_TEXT }}
          STRIPE_TEST_SECRET_KEY: ${{ secrets.STRIPE_TEST_SECRET_KEY }}
          NOSTRIPE: true
